import type { Exercise } from '../types/exercise'

// Präpositionen mit Akkusativ
// durch, für, gegen, ohne, um, bis, entlang, wider, je

const exercises: Exercise[] = [
  {
    id: 'de-grammar-prap-akk-list-001',
    type: 'multiselect',
    topic: 'Präpositionen Akkusativ',
    subtopic: 'identify Akkusativ prepositions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Which prepositions always take Akkusativ? (Select all that apply)',
    options: ['durch', 'für', 'mit', 'gegen', 'ohne', 'nach'],
    answers: [0, 1, 3, 4],
    explanation: '"durch", "für", "gegen", "ohne" always take Akkusativ. "mit" takes Dativ. "nach" takes Dativ.',
    grammarNote: 'Akkusativ prepositions: durch, für, gegen, ohne, um, bis, entlang, wider',
    tags: ['präpositionen', 'akkusativ', 'identification'],
  },
  {
    id: 'de-grammar-prap-akk-durch-001',
    type: 'selection',
    topic: 'Präpositionen Akkusativ',
    subtopic: 'durch',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete with the correct form: "Er läuft durch ___ Park."',
    options: ['den', 'dem', 'der', 'des'],
    answer: 0,
    explanation: '"durch" + Akkusativ. "der Park" (masc.) → Akkusativ = "den". "Er läuft durch den Park."',
    tags: ['präpositionen', 'akkusativ', 'durch'],
  },
  {
    id: 'de-grammar-prap-akk-fur-001',
    type: 'selection',
    topic: 'Präpositionen Akkusativ',
    subtopic: 'für',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete: "Das Geschenk ist für ___ Mutter."',
    options: ['die', 'der', 'das', 'dem'],
    answer: 0,
    explanation: '"für" + Akkusativ. "die Mutter" (fem.) → Akkusativ = "die" (unchanged for feminine). "Das Geschenk ist für die Mutter."',
    tags: ['präpositionen', 'akkusativ', 'für'],
  },
  {
    id: 'de-grammar-prap-akk-ohne-001',
    type: 'free-type',
    topic: 'Präpositionen Akkusativ',
    subtopic: 'ohne',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Fill in: "Ich trinke Kaffee ohne ___." (Milch, die Milch)',
    answers: ['Milch', 'die Milch'],
    caseSensitive: false,
    hint: '"ohne" + Akkusativ. Feminine Akkusativ = die (or without article)',
    explanation: '"ohne" takes Akkusativ. "die Milch" → Akkusativ = "die Milch". "Ich trinke Kaffee ohne Milch."',
    tags: ['präpositionen', 'akkusativ', 'ohne'],
  },
  {
    id: 'de-grammar-prap-akk-gegen-001',
    type: 'selection',
    topic: 'Präpositionen Akkusativ',
    subtopic: 'gegen',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Which sentence uses "gegen" correctly?',
    options: [
      'Er kämpft gegen den Feind.',
      'Er kämpft gegen dem Feind.',
      'Er kämpft gegen der Feind.',
      'Er kämpft gegen des Feindes.',
    ],
    answer: 0,
    explanation: '"gegen" + Akkusativ. "der Feind" (masc.) → Akkusativ = "den Feind".',
    tags: ['präpositionen', 'akkusativ', 'gegen'],
  },
  {
    id: 'de-grammar-prap-akk-um-001',
    type: 'selection',
    topic: 'Präpositionen Akkusativ',
    subtopic: 'um',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'What case does "um" require? "Er geht um ___ Ecke."',
    options: ['die (Akkusativ)', 'der (Dativ)', 'dem (Dativ)', 'den (Akkusativ, masc.)'],
    answer: 0,
    explanation: '"um" + Akkusativ. "die Ecke" (fem.) → Akkusativ = "die Ecke". "Er geht um die Ecke." (He goes around the corner.)',
    tags: ['präpositionen', 'akkusativ', 'um'],
  },
  {
    id: 'de-grammar-prap-akk-bis-001',
    type: 'selection',
    topic: 'Präpositionen Akkusativ',
    subtopic: 'bis',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'What does "bis" typically combine with?',
    options: [
      'Place names or time expressions (usually without article)',
      'All nouns with Akkusativ article',
      'Dative nouns',
      'Genitive nouns',
    ],
    answer: 0,
    explanation: '"bis" takes Akkusativ but usually combines with place names or time expressions without article: "bis Berlin", "bis Montag", "bis nächste Woche". When an article is needed, another preposition follows: "bis zum Bahnhof" (bis + zu + Dativ).',
    tags: ['präpositionen', 'akkusativ', 'bis'],
  },
]

export default exercises
