import type { Exercise } from '../types/exercise'

// Nebensätze (Subordinate Clauses)
// Key rule: verb goes to the END of the Nebensatz
// If Nebensatz comes first: main clause starts with verb (inversion)
// Types: causal (weil), concessive (obwohl), conditional (wenn/falls), temporal (als/wenn/bevor/nachdem), final (damit/um…zu)

const exercises: Exercise[] = [
  {
    id: 'de-grammar-neben-verb-end-001',
    type: 'selection',
    topic: 'Nebensätze',
    subtopic: 'verb at end',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Where does the verb go in a Nebensatz (subordinate clause)?',
    options: [
      'At the very end of the Nebensatz',
      'Right after the subordinating conjunction',
      'At the beginning of the Nebensatz',
      'In the same position as in a main clause',
    ],
    answer: 0,
    explanation: 'In a Nebensatz, the finite verb moves to the final position. "Ich weiß, dass er Deutsch SPRICHT." (spricht = end)',
    grammarNote: 'Nebensatz word order: conjunction + subject + … + verb(s)\nComplex: …+infinitive+main-verb or …+partizip2+auxiliary',
    tags: ['nebensätze', 'word-order', 'verb-end'],
  },
  {
    id: 'de-grammar-neben-inversion-001',
    type: 'selection',
    topic: 'Nebensätze',
    subtopic: 'inversion when Nebensatz is first',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Which is correct when the Nebensatz comes first?',
    options: [
      'Weil es regnet, bleibe ich zu Hause.',
      'Weil es regnet, ich bleibe zu Hause.',
      'Weil regnet es, bleibe ich zu Hause.',
      'Weil es regnet ich bleibe zu Hause.',
    ],
    answer: 0,
    explanation: 'When Nebensatz leads, the main clause inverts (verb first): "Weil es regnet, [verb] bleibe [subject] ich zu Hause." = verb–subject in main clause.',
    tags: ['nebensätze', 'inversion', 'word-order'],
  },
  {
    id: 'de-grammar-neben-bevor-001',
    type: 'selection',
    topic: 'Nebensätze',
    subtopic: 'temporal — bevor',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Choose the correct "bevor"-clause:',
    options: [
      'Ich dusche mich, bevor ich frühstücke.',
      'Ich dusche mich, bevor ich frühstücke nicht.',
      'Bevor ich frühstücke, dusche ich mich nicht.',
      'Ich dusche, bevor frühstücke ich.',
    ],
    answer: 0,
    explanation: '"bevor" (before) is subordinating → verb to end: "bevor ich FRÜHSTÜCKE". "Ich dusche mich, bevor ich frühstücke."',
    tags: ['nebensätze', 'temporal', 'bevor'],
  },
  {
    id: 'de-grammar-neben-nachdem-001',
    type: 'selection',
    topic: 'Nebensätze',
    subtopic: 'temporal — nachdem',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Choose the correct "nachdem"-clause. "Nachdem er ___, ging er ins Bett." (essen, Perfekt)',
    options: [
      'gegessen hatte',
      'gegessen hat',
      'aß',
      'hatte gegessen',
    ],
    answer: 0,
    explanation: '"nachdem" usually takes Plusquamperfekt (one step further in the past). The auxiliary goes to the very end: "nachdem er gegessen HATTE."',
    grammarNote: '"nachdem" + Plusquamperfekt → main clause in Präteritum/Perfekt',
    tags: ['nebensätze', 'temporal', 'nachdem', 'plusquamperfekt'],
  },
  {
    id: 'de-grammar-neben-damit-001',
    type: 'selection',
    topic: 'Nebensätze',
    subtopic: 'final — damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Which sentence uses "damit" (so that) correctly?',
    options: [
      'Ich lerne Deutsch, damit ich in Deutschland arbeiten kann.',
      'Ich lerne Deutsch, damit ich kann in Deutschland arbeiten.',
      'Ich lerne Deutsch, damit ich arbeiten in Deutschland kann.',
      'Damit ich in Deutschland kann arbeiten, lerne Deutsch ich.',
    ],
    answer: 0,
    explanation: '"damit" (so that) is subordinating → modal verb goes to end: "damit ich … KANN". "Ich lerne Deutsch, damit ich in Deutschland arbeiten kann."',
    tags: ['nebensätze', 'final', 'damit'],
  },
  {
    id: 'de-grammar-neben-modal-end-001',
    type: 'selection',
    topic: 'Nebensätze',
    subtopic: 'modal verb in Nebensatz',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Choose the correct word order: "Ich weiß, dass er gut Deutsch ___ ___ ."',
    options: [
      'sprechen kann',
      'kann sprechen',
      'spricht kann',
      'kann spricht',
    ],
    answer: 0,
    explanation: 'In a Nebensatz with a modal: Infinitiv + Modal (conjugated) at the very end. "dass er gut Deutsch sprechen KANN."',
    tags: ['nebensätze', 'modal-verb', 'word-order'],
  },
  {
    id: 'de-grammar-neben-perfekt-order-001',
    type: 'selection',
    topic: 'Nebensätze',
    subtopic: 'Perfekt in Nebensatz',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Choose correct word order: "Ich glaube, dass er das Buch ___ ___ ."',
    options: [
      'gelesen hat',
      'hat gelesen',
      'gelesen hatte',
      'liest hat',
    ],
    answer: 0,
    explanation: 'Perfekt in Nebensatz: Partizip II + auxiliary AT THE END: "dass er das Buch gelesen HAT".',
    tags: ['nebensätze', 'perfekt', 'word-order'],
  },
]

export default exercises
