import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-grammar-possessive-pronouns-selection-001',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'possessive-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form of mein.',
    context: 'Masculine, nominative',
    options: ['mein', 'meine', 'meinen', 'meinem'],
    answer: 0,
    explanation: 'Masculine nominative with mein takes mein.',
    tags: ['pronouns', 'possessive', 'nominative', 'masculine'],
  },
  {
    id: 'de-grammar-possessive-pronouns-selection-002',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'possessive-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form of mein.',
    context: 'Masculine, accusative',
    options: ['mein', 'meine', 'meinen', 'meinem'],
    answer: 2,
    explanation: 'Masculine accusative with mein takes meinen.',
    tags: ['pronouns', 'possessive', 'accusative', 'masculine'],
  },
  {
    id: 'de-grammar-possessive-pronouns-selection-003',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'possessive-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form of mein.',
    context: 'Feminine, dative',
    options: ['meine', 'meiner', 'meinem', 'meinen'],
    answer: 1,
    explanation: 'Feminine dative with mein takes meiner.',
    tags: ['pronouns', 'possessive', 'dative', 'feminine'],
  },
  {
    id: 'de-grammar-possessive-pronouns-selection-004',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'possessive-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form of mein.',
    context: 'Neuter, genitive',
    options: ['mein', 'meines', 'meinem', 'meine'],
    answer: 1,
    explanation: 'Neuter genitive with mein takes meines.',
    tags: ['pronouns', 'possessive', 'genitive', 'neuter'],
  },
  {
    id: 'de-grammar-possessive-pronouns-selection-005',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'possessive-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form of mein.',
    context: 'Plural, dative',
    options: ['meine', 'meiner', 'meinem', 'meinen'],
    answer: 3,
    explanation: 'Plural dative with mein takes meinen.',
    tags: ['pronouns', 'possessive', 'dative', 'plural'],
  },
  {
    id: 'de-grammar-possessive-pronouns-selection-006',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'possessive-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct phrase.',
    context: 'I see my dog.',
    options: ['ich sehe mein Hund', 'ich sehe meinen Hund', 'ich sehe meinem Hund', 'ich sehe meines Hund'],
    answer: 1,
    explanation: 'Hund is masculine and the direct object is accusative: meinen Hund.',
    tags: ['pronouns', 'possessive', 'accusative', 'context'],
  },
  {
    id: 'de-grammar-possessive-pronouns-selection-007',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'possessive-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct phrase.',
    context: 'I help my friend. (female)',
    options: ['ich helfe meine Freundin', 'ich helfe meinen Freundin', 'ich helfe meiner Freundin', 'ich helfe meinem Freundin'],
    answer: 2,
    explanation: 'Freundin is feminine and helfen takes the dative: meiner Freundin.',
    tags: ['pronouns', 'possessive', 'dative', 'context'],
  },
  {
    id: 'de-grammar-possessive-pronouns-selection-008',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'possessive-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct phrase.',
    context: 'The color of my house',
    options: ['die Farbe mein Haus', 'die Farbe meines Hauses', 'die Farbe meinem Haus', 'die Farbe meinen Hauses'],
    answer: 1,
    explanation: 'A genitive relationship requires meines Hauses.',
    tags: ['pronouns', 'possessive', 'genitive', 'context'],
  },
  {
    id: 'de-grammar-possessive-pronouns-freetype-001',
    type: 'free-type',
    topic: 'pronouns',
    subtopic: 'possessive-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the correct form of mein.',
    context: 'Feminine, nominative ->',
    answers: ['meine'],
    explanation: 'Feminine nominative with mein takes meine.',
    tags: ['pronouns', 'possessive', 'nominative', 'freetype'],
  },
  {
    id: 'de-grammar-possessive-pronouns-freetype-002',
    type: 'free-type',
    topic: 'pronouns',
    subtopic: 'possessive-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the correct form of mein.',
    context: 'Plural, genitive ->',
    answers: ['meiner'],
    explanation: 'Plural genitive with mein takes meiner.',
    tags: ['pronouns', 'possessive', 'genitive', 'freetype'],
  },
  {
    id: 'de-grammar-possessive-pronouns-multiselect-001',
    type: 'multiselect',
    topic: 'pronouns',
    subtopic: 'possessive-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Select all valid dative forms of mein from the list.',
    options: ['meinem', 'meiner', 'meinen', 'meine', 'mein'],
    answers: [0, 1, 2],
    explanation: 'Dative forms are meinem for masculine and neuter, meiner for feminine, and meinen for plural.',
    tags: ['pronouns', 'possessive', 'dative', 'multiselect'],
  },
]

export default exercises
