import type { Exercise } from '../types/exercise'

// Wechselpräpositionen (Two-way Prepositions)
// an, auf, hinter, in, neben, über, unter, vor, zwischen
// Rule: Akkusativ = movement/direction (wohin?); Dativ = location/state (wo?)

const exercises: Exercise[] = [
  {
    id: 'de-grammar-wechsel-rule-001',
    type: 'selection',
    topic: 'Wechselpräpositionen',
    subtopic: 'Akkusativ vs Dativ rule',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'When do Wechselpräpositionen take Akkusativ?',
    options: [
      'With movement/direction (wohin? — where to?)',
      'With location/state (wo? — where?)',
      'Always with verbs of motion',
      'Randomly, depending on the verb',
    ],
    answer: 0,
    explanation: 'Akkusativ = movement INTO/ONTO a place (wohin?). Dativ = static location (wo?). "Er legt das Buch auf den Tisch." (wohin → Akk.) vs "Das Buch liegt auf dem Tisch." (wo → Dat.)',
    grammarNote: 'Wechselpräpositionen: an, auf, hinter, in, neben, über, unter, vor, zwischen\nAkk (wohin?): legen, stellen, hängen, setzen\nDat (wo?): liegen, stehen, hängen, sitzen',
    tags: ['wechselpräpositionen', 'rule', 'akkusativ', 'dativ'],
  },
  {
    id: 'de-grammar-wechsel-in-ort-001',
    type: 'selection',
    topic: 'Wechselpräpositionen',
    subtopic: 'in — location',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete (location — wo?): "Das Buch liegt in ___ Tasche." (die Tasche = fem.)',
    options: ['der', 'die', 'dem', 'den'],
    answer: 0,
    explanation: '"Wo?" → Dativ. "die Tasche" (fem.) → Dativ = "der Tasche". "Das Buch liegt in der Tasche."',
    tags: ['wechselpräpositionen', 'in', 'dativ', 'location'],
  },
  {
    id: 'de-grammar-wechsel-in-richtung-001',
    type: 'selection',
    topic: 'Wechselpräpositionen',
    subtopic: 'in — direction',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete (direction — wohin?): "Ich lege das Buch in ___ Tasche." (die Tasche = fem.)',
    options: ['die', 'der', 'dem', 'den'],
    answer: 0,
    explanation: '"Wohin?" → Akkusativ. "die Tasche" (fem.) → Akkusativ = "die Tasche". "Ich lege das Buch in die Tasche."',
    tags: ['wechselpräpositionen', 'in', 'akkusativ', 'direction'],
  },
  {
    id: 'de-grammar-wechsel-an-001',
    type: 'selection',
    topic: 'Wechselpräpositionen',
    subtopic: 'an',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct answer: "Er hängt das Bild an ___ Wand." (die Wand = fem., direction)',
    options: ['die', 'der', 'den', 'dem'],
    answer: 0,
    explanation: '"Hängen" here = action (hanging it onto the wall) → Wohin? → Akkusativ. "die Wand" (fem.) → Akk. = "die Wand".',
    tags: ['wechselpräpositionen', 'an', 'akkusativ'],
  },
  {
    id: 'de-grammar-wechsel-an-location-001',
    type: 'selection',
    topic: 'Wechselpräpositionen',
    subtopic: 'an — location',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct answer: "Das Bild hängt an ___ Wand." (die Wand = fem., state)',
    options: ['der', 'die', 'den', 'dem'],
    answer: 0,
    explanation: '"hängen" here = state (the picture IS hanging there) → Wo? → Dativ. "die Wand" (fem.) → Dat. = "der Wand".',
    tags: ['wechselpräpositionen', 'an', 'dativ'],
  },
  {
    id: 'de-grammar-wechsel-auf-001',
    type: 'selection',
    topic: 'Wechselpräpositionen',
    subtopic: 'auf',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete (location): "Die Katze sitzt auf ___ Tisch." (der Tisch = masc.)',
    options: ['dem', 'den', 'der', 'des'],
    answer: 0,
    explanation: '"Wo?" → Dativ. "der Tisch" (masc.) → Dativ = "dem Tisch".',
    tags: ['wechselpräpositionen', 'auf', 'dativ'],
  },
  {
    id: 'de-grammar-wechsel-contractions-001',
    type: 'multiselect',
    topic: 'Wechselpräpositionen',
    subtopic: 'contractions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Which contractions are correct? (Select all that apply)',
    options: ['in + dem = im', 'an + dem = am', 'auf + dem = aufm', 'in + das = ins'],
    answers: [0, 1, 3],
    explanation: '"im" (in+dem), "am" (an+dem), "ins" (in+das) are standard contractions. "auf+dem" does NOT contract to "aufm".',
    grammarNote: 'Common contractions: im (in+dem), ins (in+das), am (an+dem), ans (an+das), aufs (auf+das)',
    tags: ['wechselpräpositionen', 'contractions'],
  },
  {
    id: 'de-grammar-wechsel-unter-001',
    type: 'free-type',
    topic: 'Wechselpräpositionen',
    subtopic: 'unter',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Fill in (direction): "Die Katze läuft unter ___ Tisch." (der Tisch, masc. — wohin?)',
    answers: ['den Tisch', 'den'],
    caseSensitive: false,
    hint: '"wohin?" → Akkusativ. "der Tisch" masc. → Akkusativ = "den Tisch".',
    explanation: '"Wohin?" → Akkusativ. "der Tisch" (masc.) → Akk. = "den Tisch". "Die Katze läuft unter den Tisch."',
    tags: ['wechselpräpositionen', 'unter', 'akkusativ'],
  },
]

export default exercises
