import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-grammar-article-drill-selection-001',
    type: 'selection',
    topic: 'articles',
    subtopic: 'noun-article-memorization',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct article.',
    context: '___ Tisch',
    options: ['der', 'die', 'das'],
    answer: 0,
    explanation: 'Tisch is masculine: der Tisch.',
    tags: ['articles', 'memorization', 'masculine'],
  },
  {
    id: 'de-grammar-article-drill-selection-002',
    type: 'selection',
    topic: 'articles',
    subtopic: 'noun-article-memorization',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct article.',
    context: '___ Stadt',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Stadt is feminine: die Stadt.',
    tags: ['articles', 'memorization', 'feminine'],
  },
  {
    id: 'de-grammar-article-drill-selection-003',
    type: 'selection',
    topic: 'articles',
    subtopic: 'noun-article-memorization',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct article.',
    context: '___ Kind',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Kind is neuter: das Kind.',
    tags: ['articles', 'memorization', 'neuter'],
  },
  {
    id: 'de-grammar-article-drill-selection-004',
    type: 'selection',
    topic: 'articles',
    subtopic: 'noun-article-memorization',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article.',
    context: '___ Apfel',
    options: ['der', 'die', 'das'],
    answer: 0,
    explanation: 'Apfel is masculine: der Apfel.',
    tags: ['articles', 'memorization', 'masculine'],
  },
  {
    id: 'de-grammar-article-drill-selection-005',
    type: 'selection',
    topic: 'articles',
    subtopic: 'noun-article-memorization',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article.',
    context: '___ Hand',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Hand is feminine: die Hand.',
    tags: ['articles', 'memorization', 'feminine'],
  },
  {
    id: 'de-grammar-article-drill-selection-006',
    type: 'selection',
    topic: 'articles',
    subtopic: 'noun-article-memorization',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article.',
    context: '___ Brot',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Brot is neuter: das Brot.',
    tags: ['articles', 'memorization', 'neuter'],
  },
  {
    id: 'de-grammar-article-drill-selection-007',
    type: 'selection',
    topic: 'articles',
    subtopic: 'noun-article-memorization',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article.',
    context: '___ Kaffee',
    options: ['der', 'die', 'das'],
    answer: 0,
    explanation: 'Kaffee is masculine: der Kaffee.',
    tags: ['articles', 'memorization', 'masculine'],
  },
  {
    id: 'de-grammar-article-drill-selection-008',
    type: 'selection',
    topic: 'articles',
    subtopic: 'noun-article-memorization',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article.',
    context: '___ Schule',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Schule is feminine: die Schule.',
    tags: ['articles', 'memorization', 'feminine'],
  },
  {
    id: 'de-grammar-article-drill-selection-009',
    type: 'selection',
    topic: 'articles',
    subtopic: 'noun-article-memorization',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article.',
    context: '___ Wasser',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Wasser is neuter: das Wasser.',
    tags: ['articles', 'memorization', 'neuter'],
  },
  {
    id: 'de-grammar-article-drill-freetype-001',
    type: 'free-type',
    topic: 'articles',
    subtopic: 'noun-article-memorization',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the correct article.',
    context: '___ Hund',
    answers: ['der'],
    explanation: 'Hund is masculine: der Hund.',
    tags: ['articles', 'memorization', 'freetype'],
  },
  {
    id: 'de-grammar-article-drill-freetype-002',
    type: 'free-type',
    topic: 'articles',
    subtopic: 'noun-article-memorization',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the correct article.',
    context: '___ Uhr',
    answers: ['die'],
    explanation: 'Uhr is feminine: die Uhr.',
    tags: ['articles', 'memorization', 'freetype'],
  },
  {
    id: 'de-grammar-article-drill-freetype-003',
    type: 'free-type',
    topic: 'articles',
    subtopic: 'noun-article-memorization',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the correct article.',
    context: '___ Haus',
    answers: ['das'],
    explanation: 'Haus is neuter: das Haus.',
    tags: ['articles', 'memorization', 'freetype'],
  },
  {
    id: 'de-grammar-article-drill-multiselect-001',
    type: 'multiselect',
    topic: 'articles',
    subtopic: 'noun-article-memorization',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Select all feminine nouns.',
    options: ['Stadt', 'Hand', 'Wasser', 'Tisch', 'Schule', 'Uhr'],
    answers: [0, 1, 4, 5],
    explanation: 'Stadt, Hand, Schule, and Uhr are feminine nouns.',
    tags: ['articles', 'memorization', 'multiselect'],
  },
]

export default exercises
