import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-grammar-verb-prepositions-selection-001',
    type: 'selection',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct preposition.',
    context: 'Ich warte ___ den Bus.',
    options: ['auf', 'mit', 'an', 'von'],
    answer: 0,
    explanation: 'The verb phrase is "warten auf" + accusative.',
    grammarNote: 'Many German verbs require a fixed preposition and a fixed case.',
    tags: ['verb-prepositions', 'akkusativ', 'warten-auf'],
  },
  {
    id: 'de-grammar-verb-prepositions-selection-002',
    type: 'selection',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct article.',
    context: 'Ich warte auf ___ Bus.',
    options: ['der', 'den', 'dem', 'des'],
    answer: 1,
    explanation: '"warten auf" takes the accusative, so "den Bus" is correct.',
    tags: ['verb-prepositions', 'akkusativ', 'article-choice'],
  },
  {
    id: 'de-grammar-verb-prepositions-selection-003',
    type: 'selection',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct preposition.',
    context: 'Er interessiert sich ___ moderne Kunst.',
    options: ['mit', 'fur', 'an', 'von'],
    answer: 1,
    explanation: 'The verb phrase is "sich interessieren fur" + accusative.',
    tags: ['verb-prepositions', 'akkusativ', 'interessieren-fur'],
  },
  {
    id: 'de-grammar-verb-prepositions-selection-004',
    type: 'selection',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct article.',
    context: 'Sie denkt oft an ___ Prufung.',
    options: ['die', 'der', 'den', 'dem'],
    answer: 0,
    explanation: '"denken an" takes the accusative, so "an die Prufung" is correct.',
    tags: ['verb-prepositions', 'akkusativ', 'denken-an'],
  },
  {
    id: 'de-grammar-verb-prepositions-selection-005',
    type: 'selection',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct preposition.',
    context: 'Wir sprechen ___ dem neuen Kollegen.',
    options: ['uber', 'mit', 'auf', 'fur'],
    answer: 1,
    explanation: 'The verb phrase is "sprechen mit" + dative.',
    tags: ['verb-prepositions', 'dativ', 'sprechen-mit'],
  },
  {
    id: 'de-grammar-verb-prepositions-selection-006',
    type: 'selection',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct article.',
    context: 'Wir sprechen mit ___ neuen Kollegen.',
    options: ['der', 'den', 'dem', 'des'],
    answer: 2,
    explanation: '"sprechen mit" takes the dative, so "mit dem Kollegen" is correct.',
    tags: ['verb-prepositions', 'dativ', 'article-choice'],
  },
  {
    id: 'de-grammar-verb-prepositions-selection-007',
    type: 'selection',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct preposition.',
    context: 'Sie trauumt ___ einem Haus am Meer.',
    options: ['auf', 'um', 'von', 'uber'],
    answer: 2,
    explanation: 'The verb phrase is "traumen von" + dative.',
    tags: ['verb-prepositions', 'dativ', 'traumen-von'],
  },
  {
    id: 'de-grammar-verb-prepositions-selection-008',
    type: 'selection',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct article.',
    context: 'Sie nimmt an ___ Kurs teil.',
    options: ['der', 'den', 'dem', 'des'],
    answer: 2,
    explanation: '"teilnehmen an" takes the dative, so "an dem Kurs" is correct.',
    tags: ['verb-prepositions', 'dativ', 'teilnehmen-an'],
  },
  {
    id: 'de-grammar-verb-prepositions-selection-009',
    type: 'selection',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Choose the correct pair.',
    context: 'Er erinnert sich ___ ___ Unfall.',
    options: ['an / den', 'mit / dem', 'fur / den', 'von / dem'],
    answer: 0,
    explanation: 'The verb phrase is "sich erinnern an" + accusative.',
    tags: ['verb-prepositions', 'akkusativ', 'sich-erinnern-an'],
  },
  {
    id: 'de-grammar-verb-prepositions-selection-010',
    type: 'selection',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Choose the correct pair.',
    context: 'Alles hangt ___ dem Wetter ___.',
    options: ['von / ab', 'auf / an', 'mit / zusammen', 'fur / ab'],
    answer: 0,
    explanation: 'The fixed structure is "von etwas abhangen".',
    tags: ['verb-prepositions', 'dativ', 'abhangen-von'],
  },
  {
    id: 'de-grammar-verb-prepositions-freetype-001',
    type: 'free-type',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete with one word.',
    context: 'Ich warte ___ meine Freundin.',
    answers: ['auf'],
    explanation: 'Use "warten auf" + accusative.',
    tags: ['verb-prepositions', 'preposition'],
  },
  {
    id: 'de-grammar-verb-prepositions-freetype-002',
    type: 'free-type',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete with one word.',
    context: 'Wir sprechen mit ___ Lehrer.',
    answers: ['dem'],
    explanation: 'Use dative after "mit": "mit dem Lehrer".',
    tags: ['verb-prepositions', 'dativ', 'article'],
  },
  {
    id: 'de-grammar-verb-prepositions-freetype-003',
    type: 'free-type',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Complete with one word.',
    context: 'Er denkt oft an ___ Urlaub.',
    answers: ['den'],
    explanation: 'Use accusative after "an" in this verb phrase: "an den Urlaub denken".',
    tags: ['verb-prepositions', 'akkusativ', 'article'],
  },
  {
    id: 'de-grammar-verb-prepositions-freetype-004',
    type: 'free-type',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Complete with one word.',
    context: 'Sie trauumt ___ einer langen Reise.',
    answers: ['von'],
    explanation: 'The fixed phrase is "traumen von" + dative.',
    tags: ['verb-prepositions', 'preposition'],
  },
  {
    id: 'de-grammar-verb-prepositions-freetype-005',
    type: 'free-type',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Complete with one word.',
    context: 'Er bittet ___ Hilfe.',
    answers: ['um'],
    explanation: 'The fixed phrase is "bitten um" + accusative.',
    tags: ['verb-prepositions', 'akkusativ', 'bitten-um'],
  },
  {
    id: 'de-grammar-verb-prepositions-freetype-006',
    type: 'free-type',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Complete with one word.',
    context: 'Sie freut sich auf ___ Wochenende.',
    answers: ['das'],
    explanation: '"sich freuen auf" takes the accusative: "auf das Wochenende".',
    tags: ['verb-prepositions', 'akkusativ', 'sich-freuen-auf'],
  },
  {
    id: 'de-grammar-verb-prepositions-multiselect-001',
    type: 'multiselect',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Select all verb phrases that take the accusative.',
    options: ['warten auf', 'sprechen mit', 'sich interessieren fur', 'traumen von'],
    answers: [0, 2],
    explanation: '"warten auf" and "sich interessieren fur" take the accusative. "sprechen mit" and "traumen von" take the dative.',
    tags: ['verb-prepositions', 'case-recognition'],
  },
  {
    id: 'de-grammar-verb-prepositions-multiselect-002',
    type: 'multiselect',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Select all sentences that are correct.',
    options: [
      'Ich denke an den Test.',
      'Wir sprechen mit den Lehrer.',
      'Sie trauumt von einem Garten.',
      'Er wartet auf dem Zug.'
    ],
    answers: [0, 2],
    explanation: 'Only sentences with the correct fixed preposition and case are correct.',
    tags: ['verb-prepositions', 'sentence-recognition'],
  },
  {
    id: 'de-grammar-verb-prepositions-multiselect-003',
    type: 'multiselect',
    topic: 'verb patterns',
    subtopic: 'verb-prepositions-cases',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 5,
    prompt: 'Select all verb phrases that take the dative.',
    options: ['teilnehmen an', 'denken an', 'abhangen von', 'bitten um'],
    answers: [0, 2],
    explanation: '"teilnehmen an" and "abhangen von" take the dative. "denken an" and "bitten um" take the accusative.',
    tags: ['verb-prepositions', 'dativ', 'case-recognition'],
  },
]

export default exercises
