import type { Exercise } from '../types/exercise'

// Modalverben (Modal verbs): können, müssen, dürfen, sollen, wollen, mögen/möchten
// Structure: Modal verb (conjugated) + Infinitiv at end of clause

const exercises: Exercise[] = [
  {
    id: 'de-grammar-modal-koennen-ich-001',
    type: 'selection',
    topic: 'Modalverben',
    subtopic: 'können',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form of "können" for "ich".',
    options: ['kann', 'kann ich', 'können', 'könnst'],
    answer: 0,
    explanation: '"können" Präsens: ich kann, du kannst, er kann, wir können, ihr könnt, sie können.',
    grammarNote: 'Modal verbs: ich/er/sie/es forms are identical (no -e/-t endings)',
    tags: ['modalverben', 'können', 'conjugation'],
  },
  {
    id: 'de-grammar-modal-mussen-du-001',
    type: 'selection',
    topic: 'Modalverben',
    subtopic: 'müssen',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct form of "müssen" for "du".',
    options: ['musst', 'müsst', 'muss', 'musste'],
    answer: 0,
    explanation: '"müssen" Präsens: ich muss, du musst, er muss, wir müssen, ihr müsst, sie müssen.',
    tags: ['modalverben', 'müssen', 'conjugation'],
  },
  {
    id: 'de-grammar-modal-durfen-001',
    type: 'selection',
    topic: 'Modalverben',
    subtopic: 'dürfen — meaning',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'What does "dürfen" express?',
    options: [
      'Permission (allowed to)',
      'Obligation (must)',
      'Ability (can)',
      'Desire (want to)',
    ],
    answer: 0,
    explanation: '"dürfen" = to be allowed/permitted. "Du darfst hier rauchen." = You are allowed to smoke here.',
    grammarNote: 'können = can/ability | müssen = must/necessity | dürfen = may/permission | sollen = should/obligation | wollen = want | möchten = would like',
    tags: ['modalverben', 'dürfen', 'meaning'],
  },
  {
    id: 'de-grammar-modal-word-order-001',
    type: 'selection',
    topic: 'Modalverben',
    subtopic: 'word order',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Where does the Infinitiv go in a sentence with a modal verb?',
    options: [
      'At the end of the clause',
      'Right after the modal verb',
      'At the beginning of the sentence',
      'Before the subject',
    ],
    answer: 0,
    explanation: 'Modal verb is in position 2; Infinitiv goes to the end: "Ich kann Deutsch sprechen." (sprechen = end)',
    tags: ['modalverben', 'word-order'],
  },
  {
    id: 'de-grammar-modal-fill-wollen-001',
    type: 'free-type',
    topic: 'Modalverben',
    subtopic: 'wollen',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Fill in: "Ich ___ ein Buch lesen." (wollen)',
    answers: ['will'],
    caseSensitive: false,
    hint: 'wollen → ich will',
    explanation: '"wollen" for "ich" = "will". "Ich will ein Buch lesen."',
    tags: ['modalverben', 'wollen'],
  },
  {
    id: 'de-grammar-modal-sollen-001',
    type: 'selection',
    topic: 'Modalverben',
    subtopic: 'sollen — meaning',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Which sentence expresses "sollen" (external obligation/order)?',
    options: [
      'Du sollst um 8 Uhr kommen. (You are supposed to come at 8.)',
      'Ich kann das nicht machen. (I cannot do that.)',
      'Sie möchte Kaffee trinken. (She would like to drink coffee.)',
      'Wir müssen jetzt gehen. (We must go now.)',
    ],
    answer: 0,
    explanation: '"sollen" = obligation imposed by someone else (instruction, expectation). "Sollst" implies someone told you to come.',
    tags: ['modalverben', 'sollen', 'meaning'],
  },
  {
    id: 'de-grammar-modal-mochten-001',
    type: 'selection',
    topic: 'Modalverben',
    subtopic: 'möchten',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'What is "möchten" for "er/sie/es"?',
    options: ['möchte', 'möchtet', 'möchtest', 'möchten'],
    answer: 0,
    explanation: '"möchten" Präsens: ich möchte, du möchtest, er/sie/es möchte, wir möchten, ihr möchtet, sie/Sie möchten.',
    tags: ['modalverben', 'möchten'],
  },
  {
    id: 'de-grammar-modal-multiselect-meaning-001',
    type: 'multiselect',
    topic: 'Modalverben',
    subtopic: 'meanings',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Match the correct descriptions. Which verbs express ability or possibility? (Select all that apply)',
    options: ['können', 'müssen', 'dürfen', 'mögen'],
    answers: [0, 3],
    explanation: '"können" = ability/can. "mögen" = like/may (possibility). "müssen" = must/necessity. "dürfen" = permission.',
    tags: ['modalverben', 'meaning', 'können', 'mögen'],
  },
  {
    id: 'de-grammar-modal-prateritum-001',
    type: 'selection',
    topic: 'Modalverben',
    subtopic: 'Präteritum of modals',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What is the Präteritum of "können" for "ich"?',
    options: ['konnte', 'kannte', 'könnte', 'gekonnt'],
    answer: 0,
    explanation: 'Modal verbs in Präteritum drop their umlaut: können → konnte, müssen → musste, dürfen → durfte, wollen → wollte, sollen → sollte.',
    grammarNote: 'Modal Präteritum (no umlaut): konnte, musste, durfte, wollte, sollte, mochte',
    tags: ['modalverben', 'prateritum'],
  },
]

export default exercises
