import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-grammar-articles-der-001',
    type: 'selection',
    topic: 'grammar',
    subtopic: 'articles',
    language: 'de',
    difficulty: 1,
    prompt: 'Which article is correct for "Hund" (dog)?',
    context: '___ Hund ist groß.',
    options: ['der', 'die', 'das', 'den'],
    answer: 0,
    explanation: '"Hund" is masculine in German, so it uses "der" in the nominative case.',
    tags: ['articles', 'nominative', 'masculine'],
  },
  {
    id: 'de-grammar-articles-die-001',
    type: 'selection',
    topic: 'grammar',
    subtopic: 'articles',
    language: 'de',
    difficulty: 1,
    prompt: 'Which article is correct for "Katze" (cat)?',
    context: '___ Katze schläft.',
    options: ['der', 'die', 'das', 'eine'],
    answer: 1,
    explanation: '"Katze" is feminine in German, so it uses "die" in the nominative case.',
    tags: ['articles', 'nominative', 'feminine'],
  },
  {
    id: 'de-grammar-articles-das-001',
    type: 'selection',
    topic: 'grammar',
    subtopic: 'articles',
    language: 'de',
    difficulty: 1,
    prompt: 'Which article is correct for "Buch" (book)?',
    context: '___ Buch ist interessant.',
    options: ['der', 'die', 'das', 'ein'],
    answer: 2,
    explanation: '"Buch" is neuter in German, so it uses "das" in the nominative case.',
    tags: ['articles', 'nominative', 'neuter'],
  },
  {
    id: 'de-grammar-articles-freetype-001',
    type: 'free-type',
    topic: 'grammar',
    subtopic: 'articles',
    language: 'de',
    difficulty: 2,
    prompt: 'Type the correct definite article for "Kind" (child).',
    context: '___ Kind spielt.',
    answers: ['das', 'Das'],
    caseSensitive: false,
    hint: '"Kind" is neuter.',
    explanation: '"Kind" is neuter, so it takes "das".',
    tags: ['articles', 'nominative', 'neuter'],
  },
  {
    id: 'de-grammar-articles-freetype-002',
    type: 'free-type',
    topic: 'grammar',
    subtopic: 'articles',
    language: 'de',
    difficulty: 2,
    prompt: 'Type the correct definite article for "Frau" (woman).',
    context: '___ Frau liest.',
    answers: ['die', 'Die'],
    caseSensitive: false,
    hint: '"Frau" is feminine.',
    explanation: '"Frau" is feminine, so it takes "die".',
    tags: ['articles', 'nominative', 'feminine'],
  },
  {
    id: 'de-grammar-articles-multiselect-001',
    type: 'multiselect',
    topic: 'grammar',
    subtopic: 'articles',
    language: 'de',
    difficulty: 2,
    prompt: 'Which of these nouns are feminine (take "die" as their definite article)?',
    options: ['Hund', 'Katze', 'Kind', 'Frau', 'Mann'],
    answers: [1, 3],
    explanation:
      '"Katze" (cat) and "Frau" (woman) are feminine. "Hund" (dog) and "Mann" (man) are masculine. "Kind" (child) is neuter.',
    tags: ['articles', 'gender', 'feminine'],
  },
  {
    id: 'de-grammar-articles-multiselect-002',
    type: 'multiselect',
    topic: 'grammar',
    subtopic: 'articles',
    language: 'de',
    difficulty: 3,
    prompt: 'Which of these nouns are neuter (take "das" as their definite article)?',
    options: ['Buch', 'Tisch', 'Kind', 'Fenster', 'Stuhl'],
    answers: [0, 2, 3],
    explanation:
      '"Buch" (book), "Kind" (child), and "Fenster" (window) are neuter. "Tisch" (table) and "Stuhl" (chair) are masculine.',
    tags: ['articles', 'gender', 'neuter'],
  },
  {
    id: 'de-grammar-articles-der-002',
    type: 'selection',
    topic: 'grammar',
    subtopic: 'articles',
    language: 'de',
    difficulty: 1,
    prompt: 'Which article is correct for "Mann" (man)?',
    context: '___ Mann arbeitet.',
    options: ['der', 'die', 'das', 'ein'],
    answer: 0,
    explanation: '"Mann" is masculine, so it takes "der".',
    tags: ['articles', 'nominative', 'masculine'],
  },
]

export default exercises
