import type { Exercise } from '../types/exercise'

// Plusquamperfekt (Past Perfect) — for the earlier of two past actions
// Formula: haben/sein in PRÄTERITUM + Partizip II
// "Ich hatte gegessen, bevor er kam."

const exercises: Exercise[] = [
  {
    id: 'de-grammar-pluperfect-formula-001',
    type: 'selection',
    topic: 'Plusquamperfekt',
    subtopic: 'formation',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What is the formula for Plusquamperfekt?',
    options: [
      'haben/sein (Präteritum) + Partizip II',
      'haben/sein (Präsens) + Partizip II',
      'werden (Präteritum) + Partizip II',
      'haben/sein (Perfekt) + Infinitiv',
    ],
    answer: 0,
    explanation: 'Plusquamperfekt = "hatte/war" (Präteritum of haben/sein) + Partizip II. E.g. "Ich hatte gegessen."',
    grammarNote: 'Plusquamperfekt: hatte/war + Partizip II\nUsed when one past event happened BEFORE another past event.',
    tags: ['plusquamperfekt', 'formation'],
  },
  {
    id: 'de-grammar-pluperfect-fill-essen-001',
    type: 'free-type',
    topic: 'Plusquamperfekt',
    subtopic: 'haben + Partizip II',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Fill in the blank: "Ich ___ schon ___, bevor er kam." (essen)',
    answers: ['hatte gegessen'],
    caseSensitive: false,
    hint: 'essen → haben. hatte (Prät.) + gegessen (Partizip II)',
    explanation: '"essen" → Plusquamperfekt: "hatte gegessen". "Ich hatte schon gegessen, bevor er kam."',
    tags: ['plusquamperfekt', 'haben'],
  },
  {
    id: 'de-grammar-pluperfect-fill-gehen-001',
    type: 'free-type',
    topic: 'Plusquamperfekt',
    subtopic: 'sein + Partizip II',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Fill in the blank: "Sie ___ schon ___, bevor wir ankamen." (gehen)',
    answers: ['war gegangen'],
    caseSensitive: false,
    hint: 'gehen → sein. war (Prät.) + gegangen (Partizip II)',
    explanation: '"gehen" uses "sein" → "war gegangen". "Sie war schon gegangen, bevor wir ankamen."',
    tags: ['plusquamperfekt', 'sein', 'gehen'],
  },
  {
    id: 'de-grammar-pluperfect-usage-001',
    type: 'selection',
    topic: 'Plusquamperfekt',
    subtopic: 'usage',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 2,
    prompt: 'When do you use Plusquamperfekt?',
    options: [
      'When an action in the past happened BEFORE another past action',
      'For ongoing actions in the present',
      'For future plans',
      'For actions that just happened',
    ],
    answer: 0,
    explanation: 'Plusquamperfekt marks the "earlier" of two past events. "Er hatte gegessen, bevor sie kam." → eating happened before she arrived.',
    tags: ['plusquamperfekt', 'usage'],
  },
  {
    id: 'de-grammar-pluperfect-bevor-001',
    type: 'selection',
    topic: 'Plusquamperfekt',
    subtopic: 'usage with bevor/nachdem',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Choose the correct sentence using Plusquamperfekt.',
    options: [
      'Wir hatten den Film gesehen, bevor er ins Kino kam.',
      'Wir haben den Film gesehen, bevor er ins Kino kam.',
      'Wir sahen den Film, bevor er ins Kino kommt.',
      'Wir wurden den Film sehen, bevor er ins Kino kam.',
    ],
    answer: 0,
    explanation: 'In a "bevor"-clause, the earlier event takes Plusquamperfekt. "hatten gesehen" (earlier) vs "kam" (Präteritum, later).',
    tags: ['plusquamperfekt', 'bevor', 'nachdem'],
  },
  {
    id: 'de-grammar-pluperfect-multiselect-001',
    type: 'multiselect',
    topic: 'Plusquamperfekt',
    subtopic: 'identify Plusquamperfekt sentences',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Which sentences use Plusquamperfekt correctly? (Select all that apply)',
    options: [
      'Er hatte das Buch gelesen, bevor der Film herauskam.',
      'Ich war nach Hause gegangen, als es regnete.',
      'Sie hat die Aufgabe gemacht.',
      'Wir waren angekommen, bevor das Konzert begann.',
    ],
    answers: [0, 1, 3],
    explanation: 'Options 0, 1, and 3 use "hatte/war + Partizip II" (Plusquamperfekt). Option 2 uses Perfekt ("hat gemacht"), not Plusquamperfekt.',
    tags: ['plusquamperfekt', 'identification'],
  },
  {
    id: 'de-grammar-pluperfect-kommen-001',
    type: 'free-type',
    topic: 'Plusquamperfekt',
    subtopic: 'sein + Partizip II',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Write the Plusquamperfekt of "kommen" for "er": "Er ___ schon ___, als ich ankam."',
    answers: ['war gekommen'],
    caseSensitive: false,
    hint: 'kommen → sein. war (Prät.) + gekommen',
    explanation: '"kommen" uses "sein". Plusquamperfekt: "war gekommen". "Er war schon gekommen, als ich ankam."',
    tags: ['plusquamperfekt', 'sein', 'kommen'],
  },
]

export default exercises
