import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-grammar-gender-endings-selection-001',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Zeitung',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Nouns ending in -ung are very reliably feminine: die Zeitung.',
    grammarNote: 'Typical noun endings are strong clues for grammatical gender in German, but not universal rules.',
    tags: ['noun-gender', 'endings', 'feminine', 'ung'],
  },
  {
    id: 'de-grammar-gender-endings-selection-002',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Freiheit',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Nouns ending in -heit are typically feminine: die Freiheit.',
    tags: ['noun-gender', 'endings', 'feminine', 'heit'],
  },
  {
    id: 'de-grammar-gender-endings-selection-003',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Freundlichkeit',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Nouns ending in -keit are typically feminine: die Freundlichkeit.',
    tags: ['noun-gender', 'endings', 'feminine', 'keit'],
  },
  {
    id: 'de-grammar-gender-endings-selection-004',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Mannschaft',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Nouns ending in -schaft are usually feminine: die Mannschaft.',
    tags: ['noun-gender', 'endings', 'feminine', 'schaft'],
  },
  {
    id: 'de-grammar-gender-endings-selection-005',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Nation',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Nouns ending in -ion are typically feminine: die Nation.',
    tags: ['noun-gender', 'endings', 'feminine', 'ion'],
  },
  {
    id: 'de-grammar-gender-endings-selection-006',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Musik',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Many nouns ending in -ik are feminine: die Musik.',
    tags: ['noun-gender', 'endings', 'feminine', 'ik'],
  },
  {
    id: 'de-grammar-gender-endings-selection-007',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Natur',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Nouns ending in -ur are usually feminine: die Natur.',
    tags: ['noun-gender', 'endings', 'feminine', 'ur'],
  },
  {
    id: 'de-grammar-gender-endings-selection-008',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Lehrer',
    options: ['der', 'die', 'das'],
    answer: 0,
    explanation: 'Nouns ending in -er are often masculine, especially agent nouns: der Lehrer.',
    tags: ['noun-gender', 'endings', 'masculine', 'er'],
  },
  {
    id: 'de-grammar-gender-endings-selection-009',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Honig',
    options: ['der', 'die', 'das'],
    answer: 0,
    explanation: 'Nouns ending in -ig are frequently masculine: der Honig.',
    tags: ['noun-gender', 'endings', 'masculine', 'ig'],
  },
  {
    id: 'de-grammar-gender-endings-selection-010',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Teppich',
    options: ['der', 'die', 'das'],
    answer: 0,
    explanation: 'Nouns ending in -ich are often masculine: der Teppich.',
    tags: ['noun-gender', 'endings', 'masculine', 'ich'],
  },
  {
    id: 'de-grammar-gender-endings-selection-011',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Lehrling',
    options: ['der', 'die', 'das'],
    answer: 0,
    explanation: 'Nouns ending in -ling are typically masculine: der Lehrling.',
    tags: ['noun-gender', 'endings', 'masculine', 'ling'],
  },
  {
    id: 'de-grammar-gender-endings-selection-012',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Kapitalismus',
    options: ['der', 'die', 'das'],
    answer: 0,
    explanation: 'Nouns ending in -ismus are almost always masculine: der Kapitalismus.',
    tags: ['noun-gender', 'endings', 'masculine', 'ismus'],
  },
  {
    id: 'de-grammar-gender-endings-selection-013',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Tourist',
    options: ['der', 'die', 'das'],
    answer: 0,
    explanation: 'Many nouns ending in -ist are masculine when referring to a person: der Tourist.',
    tags: ['noun-gender', 'endings', 'masculine', 'ist'],
  },
  {
    id: 'de-grammar-gender-endings-selection-014',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Maedchen',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Diminutives ending in -chen are always neuter: das Maedchen.',
    tags: ['noun-gender', 'endings', 'neuter', 'chen'],
  },
  {
    id: 'de-grammar-gender-endings-selection-015',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Dokument',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Nouns ending in -ment are very often neuter: das Dokument.',
    tags: ['noun-gender', 'endings', 'neuter', 'ment'],
  },
  {
    id: 'de-grammar-gender-endings-selection-016',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Zentrum',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Nouns ending in -um are usually neuter: das Zentrum.',
    tags: ['noun-gender', 'endings', 'neuter', 'um'],
  },
  {
    id: 'de-grammar-gender-endings-selection-017',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Thema',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Many nouns ending in -ma are neuter: das Thema.',
    tags: ['noun-gender', 'endings', 'neuter', 'ma'],
  },
  {
    id: 'de-grammar-gender-endings-selection-018',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Ergebnis',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Nouns ending in -nis are often neuter: das Ergebnis.',
    tags: ['noun-gender', 'endings', 'neuter', 'nis'],
  },
  {
    id: 'de-grammar-gender-endings-selection-019',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Wachstum',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Nouns ending in -tum are typically neuter: das Wachstum.',
    tags: ['noun-gender', 'endings', 'neuter', 'tum'],
  },
  {
    id: 'de-grammar-gender-endings-selection-020',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article based on the noun ending.',
    context: '___ Auto',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Nouns ending in -o are often neuter in learner lists: das Auto.',
    tags: ['noun-gender', 'endings', 'neuter', 'o'],
  },
  {
    id: 'de-grammar-gender-endings-freetype-001',
    type: 'free-type',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Type the correct article.',
    context: '___ Lampe',
    answers: ['die'],
    explanation: 'Many nouns ending in -e are feminine in beginner patterns: die Lampe.',
    tags: ['noun-gender', 'endings', 'freetype', 'e'],
  },
  {
    id: 'de-grammar-gender-endings-freetype-002',
    type: 'free-type',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Type the correct article.',
    context: '___ Lehrer',
    answers: ['der'],
    explanation: 'The ending -er is a strong clue for masculine nouns like der Lehrer.',
    tags: ['noun-gender', 'endings', 'freetype', 'er'],
  },
  {
    id: 'de-grammar-gender-endings-freetype-003',
    type: 'free-type',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Type the correct article.',
    context: '___ Zentrum',
    answers: ['das'],
    explanation: 'The ending -um is a strong clue for neuter nouns like das Zentrum.',
    tags: ['noun-gender', 'endings', 'freetype', 'um'],
  },
  {
    id: 'de-grammar-gender-endings-freetype-004',
    type: 'free-type',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Type the correct article.',
    context: '___ Nation',
    answers: ['die'],
    explanation: 'The ending -ion strongly points to feminine gender: die Nation.',
    tags: ['noun-gender', 'endings', 'freetype', 'ion'],
  },
  {
    id: 'de-grammar-gender-endings-multiselect-001',
    type: 'multiselect',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Select the endings that usually indicate feminine nouns.',
    options: ['-ung', '-heit', '-keit', '-ment', '-chen', '-ion'],
    answers: [0, 1, 2, 5],
    explanation: 'Typical feminine endings include -ung, -heit, -keit, and -ion.',
    tags: ['noun-gender', 'endings', 'multiselect', 'feminine'],
  },
  {
    id: 'de-grammar-gender-endings-multiselect-002',
    type: 'multiselect',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Select the endings that usually indicate neuter nouns.',
    options: ['-chen', '-tum', '-ma', '-er', '-ling', '-um'],
    answers: [0, 1, 2, 5],
    explanation: 'Typical neuter endings include -chen, -tum, -ma, and -um.',
    tags: ['noun-gender', 'endings', 'multiselect', 'neuter'],
  },
  {
    id: 'de-grammar-gender-endings-multiselect-003',
    type: 'multiselect',
    topic: 'noun gender',
    subtopic: 'gender-by-ending',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Select the endings that usually indicate masculine nouns.',
    options: ['-ig', '-ling', '-ismus', '-ist', '-heit', '-schaft'],
    answers: [0, 1, 2, 3],
    explanation: 'Typical masculine endings include -ig, -ling, -ismus, and -ist.',
    tags: ['noun-gender', 'endings', 'multiselect', 'masculine'],
  },
]

export default exercises
