import type { Exercise } from '../types/exercise'

// Reflexive Verben — verbs with reflexive pronouns (sich)
// Akkusativ reflexive: sich waschen, sich freuen, sich erinnern, sich beeilen
// Dativ reflexive: sich etw. kaufen, sich etw. wünschen, sich etw. vorstellen

const exercises: Exercise[] = [
  {
    id: 'de-grammar-reflexiv-akkusativ-ich-001',
    type: 'selection',
    topic: 'Reflexive Verben',
    subtopic: 'Akkusativ reflexivpronomen',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Which reflexive pronoun goes with "ich" (Akkusativ)?',
    options: ['mich', 'mir', 'sich', 'dich'],
    answer: 0,
    explanation: 'Akkusativ reflexive pronouns: mich (ich), dich (du), sich (er/sie/es/sie/Sie), uns (wir), euch (ihr).',
    grammarNote: 'Akk: mich / dich / sich / uns / euch / sich\nDat: mir / dir / sich / uns / euch / sich',
    tags: ['reflexive-verben', 'reflexivpronomen', 'akkusativ'],
  },
  {
    id: 'de-grammar-reflexiv-akkusativ-du-001',
    type: 'selection',
    topic: 'Reflexive Verben',
    subtopic: 'Akkusativ reflexivpronomen',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Fill in the correct reflexive pronoun: "Du musst ___ beeilen." (sich beeilen)',
    options: ['dich', 'dir', 'sich', 'euch'],
    answer: 0,
    explanation: '"du" + Akkusativ reflexive → "dich". "Du musst dich beeilen." (You need to hurry.)',
    tags: ['reflexive-verben', 'reflexivpronomen', 'dich'],
  },
  {
    id: 'de-grammar-reflexiv-akkusativ-er-001',
    type: 'free-type',
    topic: 'Reflexive Verben',
    subtopic: 'Akkusativ reflexivpronomen',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Fill in: "Er freut ___ über das Geschenk." (sich freuen)',
    answers: ['sich'],
    caseSensitive: false,
    explanation: 'For er/sie/es and plural sie/Sie, the reflexive pronoun is always "sich". "Er freut sich über das Geschenk."',
    tags: ['reflexive-verben', 'sich-freuen'],
  },
  {
    id: 'de-grammar-reflexiv-dativ-ich-001',
    type: 'selection',
    topic: 'Reflexive Verben',
    subtopic: 'Dativ reflexivpronomen',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Which reflexive pronoun is needed? "Ich kaufe ___ ein neues Buch." (sich etw. kaufen)',
    options: ['mir', 'mich', 'sich', 'uns'],
    answer: 0,
    explanation: 'When there is an accusative object ("ein neues Buch"), the reflexive takes Dativ. "ich" Dativ = "mir". "Ich kaufe mir ein neues Buch."',
    tags: ['reflexive-verben', 'reflexivpronomen', 'dativ'],
  },
  {
    id: 'de-grammar-reflexiv-vorstellen-001',
    type: 'selection',
    topic: 'Reflexive Verben',
    subtopic: 'sich vorstellen',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete: "Wir möchten ___ vorstellen." (sich vorstellen = to introduce oneself)',
    options: ['uns', 'sich', 'euch', 'mich'],
    answer: 0,
    explanation: '"wir" → Akkusativ reflexive = "uns". "Wir möchten uns vorstellen." (We would like to introduce ourselves.)',
    tags: ['reflexive-verben', 'sich-vorstellen'],
  },
  {
    id: 'de-grammar-reflexiv-erinnern-001',
    type: 'free-type',
    topic: 'Reflexive Verben',
    subtopic: 'sich erinnern',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Fill in: "Kannst du ___ an ihn erinnern?" (sich erinnern)',
    answers: ['dich'],
    caseSensitive: false,
    hint: '"du" + Akkusativ → dich',
    explanation: '"sich erinnern" requires Akkusativ reflexive. "du" → "dich". "Kannst du dich an ihn erinnern?"',
    tags: ['reflexive-verben', 'sich-erinnern'],
  },
  {
    id: 'de-grammar-reflexiv-identify-verbs-001',
    type: 'multiselect',
    topic: 'Reflexive Verben',
    subtopic: 'identify reflexive verbs',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Which are reflexive verbs (always used with "sich")? (Select all that apply)',
    options: ['sich beeilen', 'kaufen', 'sich freuen', 'schlafen', 'sich erinnern'],
    answers: [0, 2, 4],
    explanation: '"sich beeilen" (to hurry), "sich freuen" (to be happy), and "sich erinnern" (to remember) are always reflexive. "kaufen" and "schlafen" can be used without "sich".',
    tags: ['reflexive-verben', 'identification'],
  },
  {
    id: 'de-grammar-reflexiv-wir-waschen-001',
    type: 'selection',
    topic: 'Reflexive Verben',
    subtopic: 'Akkusativ reflexivpronomen',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete: "Wir ___ jeden Morgen." (sich waschen)',
    options: ['waschen uns', 'waschen sich', 'waschen euch', 'waschen mir'],
    answer: 0,
    explanation: '"wir" → reflexive "uns". "Wir waschen uns jeden Morgen." (We wash ourselves every morning.)',
    tags: ['reflexive-verben', 'sich-waschen'],
  },
]

export default exercises
