import type { Exercise } from '../types/exercise'

// Partikeln (Modal/Discourse Particles)
// doch, mal, halt/eben, ja, denn, eigentlich, wohl, nur/bloß, erst
// These add nuance, softness, or emotional tone — difficult to translate directly

const exercises: Exercise[] = [
  {
    id: 'de-grammar-partikel-doch-001',
    type: 'selection',
    topic: 'Partikeln',
    subtopic: 'doch',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What nuance does "doch" add in "Komm doch rein!"?',
    options: [
      'An encouraging invitation/mild insistence',
      'A strong command',
      'A question',
      'A negation',
    ],
    answer: 0,
    explanation: '"doch" in imperatives softens or encourages: "Komm doch rein!" ≈ "Come on in!" / "Do come in!" It implies the listener should already know or it feels natural.',
    grammarNote: '"doch" multiple uses:\n1. Contradiction: "Doch!" (Yes it is! after negation)\n2. Particle: encouraging/confirming tone\n3. Adverb: "Das ist doch klar." = "That\'s obvious after all."',
    tags: ['partikeln', 'doch'],
  },
  {
    id: 'de-grammar-partikel-mal-001',
    type: 'selection',
    topic: 'Partikeln',
    subtopic: 'mal',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What does "mal" add in "Schau mal!"?',
    options: [
      'Softens the request / makes it more casual (just/once)',
      'Makes it more urgent',
      'Adds a question tone',
      'Indicates time in the past',
    ],
    answer: 0,
    explanation: '"mal" makes imperatives/requests softer and more casual: "Schau mal!" ≈ "Just look!" / "Have a look!" Without "mal" it sounds more abrupt.',
    tags: ['partikeln', 'mal'],
  },
  {
    id: 'de-grammar-partikel-halt-eben-001',
    type: 'selection',
    topic: 'Partikeln',
    subtopic: 'halt / eben',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What do "halt" and "eben" express? "Das ist halt so." / "Das ist eben so."',
    options: [
      'Resignation or inevitability (that\'s just the way it is)',
      'Surprise',
      'Negation',
      'Politeness',
    ],
    answer: 0,
    explanation: '"halt" (Southern German) and "eben" (Northern German) express resignation or that something is inevitable/self-evident. "Das ist halt/eben so." ≈ "That\'s just how it is."',
    tags: ['partikeln', 'halt', 'eben'],
  },
  {
    id: 'de-grammar-partikel-ja-001',
    type: 'selection',
    topic: 'Partikeln',
    subtopic: 'ja',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What does "ja" express in "Das weißt du ja!"?',
    options: [
      'Reminder that the listener already knows this (shared knowledge)',
      'Agreement with what was just said',
      'Surprise',
      'Doubt',
    ],
    answer: 0,
    explanation: 'As a particle, "ja" signals shared knowledge or emphasizes something the listener should know. "Das weißt du ja!" ≈ "You know that already!" Can also express surprise: "Das ist ja toll!" ≈ "Wow, that\'s great!"',
    tags: ['partikeln', 'ja'],
  },
  {
    id: 'de-grammar-partikel-denn-001',
    type: 'selection',
    topic: 'Partikeln',
    subtopic: 'denn',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What does "denn" express in "Was machst du denn?"?',
    options: [
      'Curiosity / interested tone to a question',
      'Cause/reason (then)',
      'Negation',
      'Agreement',
    ],
    answer: 0,
    explanation: '"denn" in questions adds a tone of genuine curiosity or slight surprise. "Was machst du denn?" ≈ "So what are you doing?" / "What are you doing then?" (more engaged than without it)',
    tags: ['partikeln', 'denn'],
  },
  {
    id: 'de-grammar-partikel-wohl-001',
    type: 'selection',
    topic: 'Partikeln',
    subtopic: 'wohl',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What does "wohl" add in "Er ist wohl krank."?',
    options: [
      'Probability / assumption (probably)',
      'Certainty',
      'Negation',
      'Politeness',
    ],
    answer: 0,
    explanation: '"wohl" as a particle expresses probability or assumption: "Er ist wohl krank." ≈ "He is probably sick." Similar to Futur I with assumption.',
    tags: ['partikeln', 'wohl', 'probability'],
  },
  {
    id: 'de-grammar-partikel-multiselect-001',
    type: 'multiselect',
    topic: 'Partikeln',
    subtopic: 'identify particles',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Which words function as modal particles (Abtönungspartikeln) in spoken German? (Select all that apply)',
    options: ['doch', 'mal', 'halt', 'kaufen', 'wohl'],
    answers: [0, 1, 2, 4],
    explanation: '"doch", "mal", "halt", and "wohl" are modal particles that add nuance. "kaufen" is a verb.',
    tags: ['partikeln', 'identification'],
  },
  {
    id: 'de-grammar-partikel-erst-001',
    type: 'selection',
    topic: 'Partikeln',
    subtopic: 'erst',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What does "erst" express in "Er ist erst 10 Jahre alt."?',
    options: [
      'Only / just (unexpectedly young/small amount)',
      'Already (old/much)',
      'Still',
      'Never',
    ],
    answer: 0,
    explanation: '"erst" = only/just (implies less than expected). "Er ist erst 10 Jahre alt." = "He is only 10 years old." Contrast: "schon" = already (implies more than expected).',
    grammarNote: '"erst" = only (less than expected)\n"schon" = already (more than expected)',
    tags: ['partikeln', 'erst', 'schon'],
  },
]

export default exercises
