import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-grammar-gender-exceptions-selection-001',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct article. The ending can be misleading.',
    context: '___ Junge',
    options: ['der', 'die', 'das'],
    answer: 0,
    explanation: 'Although many nouns ending in -e are feminine, Junge is masculine: der Junge.',
    tags: ['noun-gender', 'exceptions', 'masculine', 'e'],
  },
  {
    id: 'de-grammar-gender-exceptions-selection-002',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct article. The ending can be misleading.',
    context: '___ Name',
    options: ['der', 'die', 'das'],
    answer: 0,
    explanation: 'Name is masculine despite the ending -e: der Name.',
    tags: ['noun-gender', 'exceptions', 'masculine', 'e'],
  },
  {
    id: 'de-grammar-gender-exceptions-selection-003',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct article. The ending can be misleading.',
    context: '___ Ende',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Ende ends in -e but is neuter: das Ende.',
    tags: ['noun-gender', 'exceptions', 'neuter', 'e'],
  },
  {
    id: 'de-grammar-gender-exceptions-selection-004',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct article. The ending can be misleading.',
    context: '___ Auge',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Auge ends in -e but is neuter: das Auge.',
    tags: ['noun-gender', 'exceptions', 'neuter', 'e'],
  },
  {
    id: 'de-grammar-gender-exceptions-selection-005',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 4,
    prompt: 'Choose the correct article. The ending can be misleading.',
    context: '___ Butter',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Butter ends in -er but is feminine in standard German: die Butter.',
    tags: ['noun-gender', 'exceptions', 'feminine', 'er'],
  },
  {
    id: 'de-grammar-gender-exceptions-selection-006',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 4,
    prompt: 'Choose the correct article. The ending can be misleading.',
    context: '___ Mutter',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Mutter ends in -er but is feminine: die Mutter.',
    tags: ['noun-gender', 'exceptions', 'feminine', 'er'],
  },
  {
    id: 'de-grammar-gender-exceptions-selection-007',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 4,
    prompt: 'Choose the correct article. The ending can be misleading.',
    context: '___ Firma',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Not every noun ending in -a is neuter. Firma is feminine: die Firma.',
    tags: ['noun-gender', 'exceptions', 'feminine', 'a'],
  },
  {
    id: 'de-grammar-gender-exceptions-selection-008',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 4,
    prompt: 'Choose the correct article. The ending can be misleading.',
    context: '___ Pizza',
    options: ['der', 'die', 'das'],
    answer: 1,
    explanation: 'Pizza ends in -a but is feminine: die Pizza.',
    tags: ['noun-gender', 'exceptions', 'feminine', 'a'],
  },
  {
    id: 'de-grammar-gender-exceptions-selection-009',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Choose the correct article. The ending can be misleading.',
    context: '___ Herz',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Herz does not follow a common beginner ending pattern and is neuter: das Herz.',
    tags: ['noun-gender', 'exceptions', 'neuter'],
  },
  {
    id: 'de-grammar-gender-exceptions-selection-010',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Choose the correct article. The ending can be misleading.',
    context: '___ Museum',
    options: ['der', 'die', 'das'],
    answer: 2,
    explanation: 'Although -um is often neuter, Museum is a high-frequency example worth memorizing separately: das Museum.',
    tags: ['noun-gender', 'exceptions', 'neuter', 'um'],
  },
  {
    id: 'de-grammar-gender-exceptions-freetype-001',
    type: 'free-type',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Type the correct article.',
    context: '___ Name',
    answers: ['der'],
    explanation: 'Name is masculine: der Name.',
    tags: ['noun-gender', 'exceptions', 'freetype'],
  },
  {
    id: 'de-grammar-gender-exceptions-freetype-002',
    type: 'free-type',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Type the correct article.',
    context: '___ Butter',
    answers: ['die'],
    explanation: 'Butter is feminine in standard German: die Butter.',
    tags: ['noun-gender', 'exceptions', 'freetype'],
  },
  {
    id: 'de-grammar-gender-exceptions-freetype-003',
    type: 'free-type',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Type the correct article.',
    context: '___ Ende',
    answers: ['das'],
    explanation: 'Ende is neuter: das Ende.',
    tags: ['noun-gender', 'exceptions', 'freetype'],
  },
  {
    id: 'de-grammar-gender-exceptions-multiselect-001',
    type: 'multiselect',
    topic: 'noun gender',
    subtopic: 'gender-exceptions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 4,
    prompt: 'Select the nouns that are exceptions to the common beginner rule “-e is often feminine”.',
    options: ['Junge', 'Name', 'Ende', 'Lampe', 'Auge', 'Blume'],
    answers: [0, 1, 2, 4],
    explanation: 'Junge and Name are masculine; Ende and Auge are neuter. Lampe and Blume are regular feminine examples.',
    tags: ['noun-gender', 'exceptions', 'multiselect'],
  },
]

export default exercises
