import type { Exercise } from '../types/exercise'

// Pluralbildung (Plural Formation)
// Main patterns:
// -e: der Tag → die Tage (often masc/neut monosyllabic)
// -er: das Kind → die Kinder (often neut, often with umlaut)
// -en/-n: die Frau → die Frauen, die Lampe → die Lampen (often fem)
// -(e)s: das Auto → die Autos, das Büro → die Büros (foreign words)
// Umlaut only (no suffix): der Vater → die Väter, der Bruder → die Brüder
// No change: das Zimmer → die Zimmer, der Lehrer → die Lehrer

const exercises: Exercise[] = [
  {
    id: 'de-grammar-plural-tag-001',
    type: 'selection',
    topic: 'Pluralbildung',
    subtopic: '-e plural',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'What is the plural of "der Tag"?',
    options: ['die Tage', 'die Tagen', 'die Täge', 'die Tags'],
    answer: 0,
    explanation: '"der Tag" → plural: "die Tage" (-e suffix, no umlaut). Many masculine monosyllabic nouns take -e.',
    tags: ['pluralbildung', '-e', 'tag'],
  },
  {
    id: 'de-grammar-plural-kind-001',
    type: 'selection',
    topic: 'Pluralbildung',
    subtopic: '-er plural',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'What is the plural of "das Kind"?',
    options: ['die Kinder', 'die Kinde', 'die Kinder', 'die Kindern'],
    answer: 0,
    explanation: '"das Kind" → "die Kinder" (-er suffix). Many neuter nouns take -er.',
    tags: ['pluralbildung', '-er', 'kind'],
  },
  {
    id: 'de-grammar-plural-frau-001',
    type: 'selection',
    topic: 'Pluralbildung',
    subtopic: '-en plural',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'What is the plural of "die Frau"?',
    options: ['die Frauen', 'die Fraue', 'die Frauern', 'die Fraues'],
    answer: 0,
    explanation: '"die Frau" → "die Frauen" (-en suffix). Most feminine nouns take -en or -n.',
    tags: ['pluralbildung', '-en', 'frau'],
  },
  {
    id: 'de-grammar-plural-auto-001',
    type: 'selection',
    topic: 'Pluralbildung',
    subtopic: '-s plural',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'What is the plural of "das Auto"?',
    options: ['die Autos', 'die Autoen', 'die Autoes', 'die Auto'],
    answer: 0,
    explanation: '"das Auto" → "die Autos" (-s suffix). Loan words and words ending in vowels often take -s.',
    tags: ['pluralbildung', '-s', 'auto'],
  },
  {
    id: 'de-grammar-plural-vater-umlaut-001',
    type: 'free-type',
    topic: 'Pluralbildung',
    subtopic: 'umlaut plural',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'What is the plural of "der Vater"?',
    answers: ['die Väter', 'Väter'],
    caseSensitive: false,
    hint: 'Umlaut change (a → ä), no suffix added',
    explanation: '"der Vater" → "die Väter" (umlaut only, no extra suffix). Similar: der Bruder → die Brüder.',
    tags: ['pluralbildung', 'umlaut', 'vater'],
  },
  {
    id: 'de-grammar-plural-no-change-001',
    type: 'selection',
    topic: 'Pluralbildung',
    subtopic: 'no change plural',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'What is the plural of "das Zimmer" (room)?',
    options: ['die Zimmer', 'die Zimmers', 'die Zimmern', 'die Zimmerе'],
    answer: 0,
    explanation: '"das Zimmer" → "die Zimmer" (no change). Nouns ending in -er, -el, -en often have the same form in singular and plural.',
    tags: ['pluralbildung', 'no-change', 'zimmer'],
  },
  {
    id: 'de-grammar-plural-multiselect-en-001',
    type: 'multiselect',
    topic: 'Pluralbildung',
    subtopic: '-en plural',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Which nouns form their plural with "-en"? (Select all that apply)',
    options: ['die Frau → Frauen', 'das Kind → Kinder', 'die Schule → Schulen', 'der Tisch → Tische'],
    answers: [0, 2],
    explanation: '"Frau → Frauen" and "Schule → Schulen" take -en. "Kind → Kinder" (-er), "Tisch → Tische" (-e).',
    tags: ['pluralbildung', '-en', 'identification'],
  },
  {
    id: 'de-grammar-plural-haus-001',
    type: 'free-type',
    topic: 'Pluralbildung',
    subtopic: '-er + umlaut plural',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'What is the plural of "das Haus"?',
    answers: ['die Häuser', 'Häuser'],
    caseSensitive: false,
    hint: '-er suffix + umlaut (au → äu)',
    explanation: '"das Haus" → "die Häuser" (-er + umlaut). "Wir sehen viele Häuser."',
    tags: ['pluralbildung', '-er', 'umlaut', 'haus'],
  },
  {
    id: 'de-grammar-plural-dative-n-001',
    type: 'selection',
    topic: 'Pluralbildung',
    subtopic: 'dative plural -n',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'In Dative plural, what is added to the noun if its plural doesn\'t already end in -n or -s?',
    options: ['-n', '-en', '-s', '-e'],
    answer: 0,
    explanation: 'Dative plural always ends in -n. If plural doesn\'t end in -n or -s, add -n: "die Kinder" → Dat.Pl. "den Kindern". "die Autos" → "den Autos" (already -s).',
    grammarNote: 'Dativ Plural: always add -n to plural form (unless already ends in -n or -s)',
    tags: ['pluralbildung', 'dativ', 'plural'],
  },
]

export default exercises
