import type { Exercise } from '../types/exercise'

// Passiv (Passive Voice)
// Vorgangspassiv (process): werden + Partizip II
// Zustandspassiv (state): sein + Partizip II
// Agent expressed with "von" + Dativ

const exercises: Exercise[] = [
  {
    id: 'de-grammar-passiv-prasens-formula-001',
    type: 'selection',
    topic: 'Passiv',
    subtopic: 'Vorgangspassiv Präsens',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What is the formula for Vorgangspassiv (Präsens)?',
    options: [
      'werden (Präsens) + Partizip II',
      'sein (Präsens) + Partizip II',
      'haben (Präsens) + Partizip II',
      'werden (Präsens) + Infinitiv',
    ],
    answer: 0,
    explanation: 'Vorgangspassiv Präsens = conjugated "werden" + Partizip II at end. "Das Buch wird gelesen."',
    grammarNote: 'Passiv Präsens: wird/werden + Partizip II\nPassiv Präteritum: wurde/wurden + Partizip II\nAgent: von + Dativ',
    tags: ['passiv', 'vorgangspassiv', 'formation'],
  },
  {
    id: 'de-grammar-passiv-prasens-fill-001',
    type: 'free-type',
    topic: 'Passiv',
    subtopic: 'Vorgangspassiv Präsens',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Rewrite actively: "Die Lehrerin erklärt die Aufgabe." → Passiv: "Die Aufgabe ___ ___ der Lehrerin ___."',
    answers: ['wird von erklärt'],
    caseSensitive: false,
    hint: 'werden (wird) + von + Dativ agent + Partizip II at end',
    explanation: '"Die Aufgabe wird von der Lehrerin erklärt." — "wird" + "von der Lehrerin" (agent in Dativ) + "erklärt" (Partizip II)',
    tags: ['passiv', 'vorgangspassiv', 'von'],
  },
  {
    id: 'de-grammar-passiv-prateritum-001',
    type: 'selection',
    topic: 'Passiv',
    subtopic: 'Vorgangspassiv Präteritum',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Choose the correct Passiv Präteritum sentence.',
    options: [
      'Das Haus wurde gebaut.',
      'Das Haus wird gebaut.',
      'Das Haus ist gebaut.',
      'Das Haus hat gebaut.',
    ],
    answer: 0,
    explanation: 'Passiv Präteritum = "wurde/wurden" + Partizip II. "Das Haus wurde gebaut." (The house was built.)',
    tags: ['passiv', 'prateritum', 'wurde'],
  },
  {
    id: 'de-grammar-passiv-zustand-001',
    type: 'selection',
    topic: 'Passiv',
    subtopic: 'Zustandspassiv',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What is the difference between "Die Tür wird geöffnet" and "Die Tür ist geöffnet"?',
    options: [
      '"wird geöffnet" = process (being opened now); "ist geöffnet" = state (already open)',
      '"wird geöffnet" = state; "ist geöffnet" = process',
      'They mean exactly the same thing',
      '"ist geöffnet" uses Futur I',
    ],
    answer: 0,
    explanation: 'Vorgangspassiv (werden): action in progress. Zustandspassiv (sein): resulting state. "Die Tür ist geöffnet" = the door is (in the state of being) open.',
    grammarNote: 'Vorgangspassiv: werden + Partizip II (process/action)\nZustandspassiv: sein + Partizip II (resulting state)',
    tags: ['passiv', 'zustandspassiv', 'vorgangspassiv'],
  },
  {
    id: 'de-grammar-passiv-agent-von-001',
    type: 'selection',
    topic: 'Passiv',
    subtopic: 'von + Dativ (agent)',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'How is the agent (doer) expressed in a passive sentence?',
    options: [
      'von + Dativ',
      'mit + Dativ',
      'durch + Akkusativ (for persons)',
      'für + Akkusativ',
    ],
    answer: 0,
    explanation: 'The agent (person performing the action) takes "von + Dativ": "Das Buch wird von der Lehrerin gelesen." Note: "durch + Akkusativ" is used for means/instruments.',
    tags: ['passiv', 'von', 'dativ', 'agent'],
  },
  {
    id: 'de-grammar-passiv-perfekt-001',
    type: 'selection',
    topic: 'Passiv',
    subtopic: 'Passiv Perfekt',
    language: 'de',
    group: 'grammar',
    level: 'B2',
    difficulty: 4,
    prompt: 'How do you form Passiv Perfekt?',
    options: [
      'sein (Präsens) + Partizip II + worden',
      'haben (Präsens) + Partizip II + geworden',
      'werden (Präsens) + Partizip II',
      'sein (Präteritum) + Partizip II',
    ],
    answer: 0,
    explanation: 'Passiv Perfekt: sein + Partizip II + "worden" (special form of werden). "Das Buch ist gelesen worden." Note: not "geworden" but "worden".',
    grammarNote: 'Passiv Perfekt: ist/sind + Partizip II + worden',
    tags: ['passiv', 'perfekt', 'worden'],
  },
  {
    id: 'de-grammar-passiv-multiselect-001',
    type: 'multiselect',
    topic: 'Passiv',
    subtopic: 'Vorgangspassiv identification',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Which sentences are Vorgangspassiv? (Select all that apply)',
    options: [
      'Das Auto wird repariert.',
      'Das Fenster ist geschlossen.',
      'Die Zeitung wurde gelesen.',
      'Der Brief ist geschrieben.',
    ],
    answers: [0, 2],
    explanation: '"wird repariert" and "wurde gelesen" use "werden" → Vorgangspassiv. "ist geschlossen" and "ist geschrieben" use "sein" → Zustandspassiv.',
    tags: ['passiv', 'identification'],
  },
]

export default exercises
