import type { Exercise } from '../types/exercise'

// Komparation der Adjektive (Comparison of Adjectives)
// Positiv: schnell
// Komparativ: schneller (+ als for comparison)
// Superlativ: am schnellsten / schnellste (with article)
// Irregular: gut → besser → am besten; viel → mehr → am meisten; gern → lieber → am liebsten

const exercises: Exercise[] = [
  {
    id: 'de-grammar-komp-komparativ-form-001',
    type: 'selection',
    topic: 'Komparation',
    subtopic: 'Komparativ formation',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'What is the Komparativ of "schnell" (fast)?',
    options: ['schneller', 'schnellest', 'am schnellsten', 'mehr schnell'],
    answer: 0,
    explanation: 'Komparativ = adjective + -er. "schnell" → "schneller". Used in comparisons: "Er ist schneller als ich."',
    grammarNote: 'Positiv: schnell | Komparativ: schnell-er | Superlativ: am schnell-sten / der/die/das schnellste',
    tags: ['komparation', 'komparativ'],
  },
  {
    id: 'de-grammar-komp-als-001',
    type: 'selection',
    topic: 'Komparation',
    subtopic: 'Komparativ + als',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete: "Er ist ___ ich." (He is taller than me.)',
    options: ['größer als', 'am größten', 'größe wie', 'größer wie'],
    answer: 0,
    explanation: 'Comparison uses "als": "Er ist größer als ich." Note: "wie" is used for equal comparison (so … wie).',
    tags: ['komparation', 'komparativ', 'als'],
  },
  {
    id: 'de-grammar-komp-superlativ-001',
    type: 'selection',
    topic: 'Komparation',
    subtopic: 'Superlativ',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'What is the predicative Superlativ of "alt" (old)? (E.g. "Er ist ___")',
    options: ['am ältesten', 'am altest', 'am alten', 'der älteste'],
    answer: 0,
    explanation: 'Predicative Superlativ: "am" + adjective + "-sten". Short adj ending in -t/-d/-s/-ß/-z add -esten: "alt" → "am ältesten" (+ umlaut).',
    tags: ['komparation', 'superlativ', 'predikativ'],
  },
  {
    id: 'de-grammar-komp-superlativ-attributiv-001',
    type: 'selection',
    topic: 'Komparation',
    subtopic: 'Superlativ — attributive',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Complete: "Das ist das ___ Buch in der Bibliothek." (interesting)',
    options: ['interessanteste', 'interessantest', 'interessanter', 'am interessantesten'],
    answer: 0,
    explanation: 'Attributive Superlativ (before noun): -ste- + adjective ending. "das interessanteste Buch" (neut., Nom. → -e).',
    tags: ['komparation', 'superlativ', 'attributiv'],
  },
  {
    id: 'de-grammar-komp-irregular-gut-001',
    type: 'selection',
    topic: 'Komparation',
    subtopic: 'irregular forms',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'What is the Komparativ of "gut" (good)?',
    options: ['besser', 'guter', 'mehr gut', 'am gutem'],
    answer: 0,
    explanation: '"gut" is irregular: gut → besser → am besten.',
    grammarNote: 'Irregular: gut → besser → am besten\nviel → mehr → am meisten\ngern → lieber → am liebsten\nhoch → höher → am höchsten\nnah → näher → am nächsten',
    tags: ['komparation', 'irregular', 'gut', 'besser'],
  },
  {
    id: 'de-grammar-komp-irregular-viel-001',
    type: 'selection',
    topic: 'Komparation',
    subtopic: 'irregular forms',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'What is the Superlativ of "viel" (much/many)?',
    options: ['am meisten', 'am vielen', 'am vielsten', 'am mehrsten'],
    answer: 0,
    explanation: '"viel" is irregular: viel → mehr → am meisten.',
    tags: ['komparation', 'irregular', 'viel', 'meisten'],
  },
  {
    id: 'de-grammar-komp-gleichheit-001',
    type: 'selection',
    topic: 'Komparation',
    subtopic: 'equality — so … wie',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete the sentence of equality: "Er ist ___ groß ___ ich."',
    options: ['so … wie', 'so … als', 'genau … als', 'als … wie'],
    answer: 0,
    explanation: 'Equality comparison: "so + Positiv + wie". "Er ist so groß wie ich." (He is as tall as me.)',
    tags: ['komparation', 'gleichheit', 'so-wie'],
  },
  {
    id: 'de-grammar-komp-umlaut-001',
    type: 'multiselect',
    topic: 'Komparation',
    subtopic: 'umlaut in comparative',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Which adjectives take an umlaut in the Komparativ? (Select all that apply)',
    options: ['alt → älter', 'schnell → schneller', 'jung → jünger', 'lang → länger'],
    answers: [0, 2, 3],
    explanation: 'Many one-syllable adjectives with a/o/u take umlaut in comparison: alt→älter, jung→jünger, lang→länger. "schnell" has no umlaut.',
    tags: ['komparation', 'umlaut'],
  },
]

export default exercises
