import type { Exercise } from '../types/exercise'

// Indefinitpronomen (Indefinite Pronouns)
// man, jemand, niemand, etwas, nichts, alle, jeder, viele, einige, andere, beide, manche

const exercises: Exercise[] = [
  {
    id: 'de-grammar-indef-man-001',
    type: 'selection',
    topic: 'Indefinitpronomen',
    subtopic: 'man',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: '"Man" is used to express…',
    options: [
      'a general/unspecified subject (one/people/you in general)',
      'a specific unknown person',
      'every single person',
      'nobody',
    ],
    answer: 0,
    explanation: '"man" = general/impersonal "one". "Man spricht hier Deutsch." = "German is spoken here / People speak German here." Always used with 3rd person singular verb.',
    grammarNote: '"man" is always subject, uses 3rd person sg. verb. Cannot be replaced by "er".',
    tags: ['indefinitpronomen', 'man'],
  },
  {
    id: 'de-grammar-indef-jemand-001',
    type: 'selection',
    topic: 'Indefinitpronomen',
    subtopic: 'jemand / niemand',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Fill in: "___ hat an die Tür geklopft." (someone)',
    options: ['Jemand', 'Niemand', 'Etwas', 'Man'],
    answer: 0,
    explanation: '"jemand" = someone/somebody. "Jemand hat an die Tür geklopft." (Someone knocked on the door.)',
    tags: ['indefinitpronomen', 'jemand'],
  },
  {
    id: 'de-grammar-indef-niemand-001',
    type: 'selection',
    topic: 'Indefinitpronomen',
    subtopic: 'niemand',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Translate: "Nobody came to the party."',
    options: [
      'Niemand kam zur Party.',
      'Jemand kam nicht zur Party.',
      'Kein kam zur Party.',
      'Alle kamen nicht zur Party.',
    ],
    answer: 0,
    explanation: '"niemand" = nobody/no one. "Niemand kam zur Party."',
    tags: ['indefinitpronomen', 'niemand'],
  },
  {
    id: 'de-grammar-indef-etwas-nichts-001',
    type: 'selection',
    topic: 'Indefinitpronomen',
    subtopic: 'etwas / nichts',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'What is the opposite of "etwas" (something)?',
    options: ['nichts', 'niemand', 'jemand', 'alles'],
    answer: 0,
    explanation: '"etwas" = something; "nichts" = nothing. "Ich habe etwas gegessen." / "Ich habe nichts gegessen."',
    tags: ['indefinitpronomen', 'etwas', 'nichts'],
  },
  {
    id: 'de-grammar-indef-jeder-001',
    type: 'selection',
    topic: 'Indefinitpronomen',
    subtopic: 'jeder',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct form: "___ Mensch macht Fehler." (Every person)',
    options: ['Jeder', 'Alle', 'Viele', 'Manche'],
    answer: 0,
    explanation: '"jeder" = every (emphasizes each individual). "Jeder Mensch macht Fehler." (Every person makes mistakes.)',
    tags: ['indefinitpronomen', 'jeder'],
  },
  {
    id: 'de-grammar-indef-alle-001',
    type: 'selection',
    topic: 'Indefinitpronomen',
    subtopic: 'alle',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'What does "alle" mean?',
    options: ['all / everyone (as a group)', 'some', 'many', 'each individual'],
    answer: 0,
    explanation: '"alle" = all/everyone as a whole. "Alle kamen zur Party." (Everyone came to the party.)',
    tags: ['indefinitpronomen', 'alle'],
  },
  {
    id: 'de-grammar-indef-manche-einige-001',
    type: 'selection',
    topic: 'Indefinitpronomen',
    subtopic: 'manche / einige',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Which word best completes: "___ Studenten lernen sehr fleißig." (some students — implying not all)',
    options: ['Manche', 'Alle', 'Niemand', 'Jeder'],
    answer: 0,
    explanation: '"manche" = some (but not all), with a slight implication of unexpectedness. "einige" also works but is more neutral. "Manche Studenten lernen sehr fleißig."',
    tags: ['indefinitpronomen', 'manche', 'einige'],
  },
  {
    id: 'de-grammar-indef-multiselect-001',
    type: 'multiselect',
    topic: 'Indefinitpronomen',
    subtopic: 'identification',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Which are indefinite pronouns? (Select all that apply)',
    options: ['man', 'ich', 'niemand', 'etwas', 'der'],
    answers: [0, 2, 3],
    explanation: '"man", "niemand", "etwas" are indefinite pronouns. "ich" is a personal pronoun, "der" is a definite article or relative pronoun.',
    tags: ['indefinitpronomen', 'identification'],
  },
]

export default exercises
