import type { Exercise } from '../types/exercise'

// Trennbare Verben (Separable Verbs) — prefix detaches and moves to end of clause
// Untrennbare Verben (Inseparable Verbs) — prefix stays attached, no "ge-" in Partizip II
// Separable prefixes: ab-, an-, auf-, aus-, ein-, mit-, nach-, vor-, zu-, zurück-...
// Inseparable prefixes: be-, emp-, ent-, er-, ge-, miss-, ver-, zer-

const exercises: Exercise[] = [
  {
    id: 'de-grammar-trennbar-aufmachen-001',
    type: 'selection',
    topic: 'Trennbare Verben',
    subtopic: 'separable prefix — word order',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Where does the separable prefix go in a main clause (Präsens)?',
    context: '"aufmachen" → Ich ___ die Tür ___.',
    options: ['mache … auf', 'aufmache … —', '— … aufmache', 'mache auf … —'],
    answer: 0,
    explanation: 'In a main clause, the verb root takes position 2 and the prefix goes to the end: "Ich mache die Tür auf."',
    grammarNote: 'Separable prefix → end of clause in Präsens/Präteritum | Stays attached in Infinitiv and Partizip II',
    tags: ['trennbare-verben', 'word-order', 'aufmachen'],
  },
  {
    id: 'de-grammar-trennbar-partizip2-001',
    type: 'selection',
    topic: 'Trennbare Verben',
    subtopic: 'Partizip II',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'What is the Partizip II of "aufmachen" (separable)?',
    options: ['aufgemacht', 'gemacht auf', 'aufmachte', 'geaufmacht'],
    answer: 0,
    explanation: 'Separable verb Partizip II: prefix + ge- + stem + -t. "auf" + "ge" + "mach" + "t" = "aufgemacht".',
    tags: ['trennbare-verben', 'partizip2'],
  },
  {
    id: 'de-grammar-trennbar-anrufen-001',
    type: 'free-type',
    topic: 'Trennbare Verben',
    subtopic: 'separable prefix — word order',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Fill in: "Ich ___ meinen Freund ___." (anrufen)',
    answers: ['rufe an'],
    caseSensitive: false,
    hint: 'anrufen → rufe … an',
    explanation: '"anrufen" splits: "rufe" (position 2) + "an" (end). "Ich rufe meinen Freund an."',
    tags: ['trennbare-verben', 'anrufen'],
  },
  {
    id: 'de-grammar-untrennbar-verstehen-001',
    type: 'selection',
    topic: 'Trennbare Verben',
    subtopic: 'inseparable prefix — Partizip II',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What is the Partizip II of "verstehen" (inseparable prefix "ver-")?',
    options: ['verstanden', 'geverstanden', 'verstandenen', 'gestandenver'],
    answer: 0,
    explanation: 'Inseparable prefixes (ver-, be-, ent-, er-…) do NOT add "ge-" in Partizip II. "verstehen" → "verstanden".',
    grammarNote: 'Inseparable prefixes: be-, emp-, ent-, er-, ge-, miss-, ver-, zer- → no ge- in Partizip II',
    tags: ['untrennbare-verben', 'partizip2', 'verstehen'],
  },
  {
    id: 'de-grammar-trennbar-identify-001',
    type: 'multiselect',
    topic: 'Trennbare Verben',
    subtopic: 'separable vs inseparable',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Which of these are SEPARABLE verbs? (Select all that apply)',
    options: ['aufstehen', 'verstehen', 'einschlafen', 'besuchen', 'mitnehmen'],
    answers: [0, 2, 4],
    explanation: '"aufstehen" (auf-), "einschlafen" (ein-), "mitnehmen" (mit-) are separable. "verstehen" (ver-) and "besuchen" (be-) have inseparable prefixes.',
    tags: ['trennbare-verben', 'untrennbare-verben', 'identification'],
  },
  {
    id: 'de-grammar-trennbar-nebensatz-001',
    type: 'selection',
    topic: 'Trennbare Verben',
    subtopic: 'word order in subordinate clause',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Which sentence correctly uses "aufstehen" in a subordinate clause?',
    options: [
      'Ich weiß, dass er früh aufsteht.',
      'Ich weiß, dass er steht früh auf.',
      'Ich weiß, dass er aufsteht früh.',
      'Ich weiß, dass früh steht er auf.',
    ],
    answer: 0,
    explanation: 'In a subordinate clause (Nebensatz), the verb is at the END and the prefix rejoins: "aufsteht" (not split). "dass er früh aufsteht."',
    tags: ['trennbare-verben', 'nebensatz', 'word-order'],
  },
  {
    id: 'de-grammar-trennbar-einladen-perfekt-001',
    type: 'free-type',
    topic: 'Trennbare Verben',
    subtopic: 'Perfekt',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Write the Perfekt of "einladen" (er): "Er ___ uns ___."',
    answers: ['hat eingeladen'],
    caseSensitive: false,
    hint: 'einladen → ein + ge + lad + en = eingeladen. Uses haben.',
    explanation: '"einladen" separable: Partizip II = "eingeladen". "Er hat uns eingeladen."',
    tags: ['trennbare-verben', 'perfekt', 'einladen'],
  },
  {
    id: 'de-grammar-trennbar-untrennbar-prefixes-001',
    type: 'multiselect',
    topic: 'Trennbare Verben',
    subtopic: 'inseparable prefixes',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Which are INSEPARABLE prefixes? (Select all that apply)',
    options: ['ver-', 'auf-', 'be-', 'mit-', 'ent-'],
    answers: [0, 2, 4],
    explanation: '"ver-", "be-", "ent-" are inseparable. "auf-" and "mit-" are separable prefixes.',
    tags: ['untrennbare-verben', 'prefixes'],
  },
]

export default exercises
