import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-grammar-case-table-selection-001',
    type: 'selection',
    topic: 'cases',
    subtopic: 'definite-articles-case-table',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct definite article.',
    context: 'Masculine, nominative',
    options: ['der', 'den', 'dem', 'des'],
    answer: 0,
    explanation: 'Masculine nominative takes der.',
    tags: ['cases', 'articles', 'nominative', 'masculine'],
  },
  {
    id: 'de-grammar-case-table-selection-002',
    type: 'selection',
    topic: 'cases',
    subtopic: 'definite-articles-case-table',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct definite article.',
    context: 'Masculine, accusative',
    options: ['der', 'den', 'dem', 'des'],
    answer: 1,
    explanation: 'Masculine accusative changes to den.',
    tags: ['cases', 'articles', 'accusative', 'masculine'],
  },
  {
    id: 'de-grammar-case-table-selection-003',
    type: 'selection',
    topic: 'cases',
    subtopic: 'definite-articles-case-table',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct definite article.',
    context: 'Masculine, dative',
    options: ['der', 'den', 'dem', 'des'],
    answer: 2,
    explanation: 'Masculine dative takes dem.',
    tags: ['cases', 'articles', 'dative', 'masculine'],
  },
  {
    id: 'de-grammar-case-table-selection-004',
    type: 'selection',
    topic: 'cases',
    subtopic: 'definite-articles-case-table',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct definite article.',
    context: 'Masculine, genitive',
    options: ['der', 'den', 'dem', 'des'],
    answer: 3,
    explanation: 'Masculine genitive takes des.',
    tags: ['cases', 'articles', 'genitive', 'masculine'],
  },
  {
    id: 'de-grammar-case-table-selection-005',
    type: 'selection',
    topic: 'cases',
    subtopic: 'definite-articles-case-table',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct definite article.',
    context: 'Feminine, dative',
    options: ['die', 'der', 'das', 'dem'],
    answer: 1,
    explanation: 'Feminine dative takes der.',
    tags: ['cases', 'articles', 'dative', 'feminine'],
  },
  {
    id: 'de-grammar-case-table-selection-006',
    type: 'selection',
    topic: 'cases',
    subtopic: 'definite-articles-case-table',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct definite article.',
    context: 'Neuter, genitive',
    options: ['das', 'dem', 'des', 'der'],
    answer: 2,
    explanation: 'Neuter genitive takes des.',
    tags: ['cases', 'articles', 'genitive', 'neuter'],
  },
  {
    id: 'de-grammar-case-table-selection-007',
    type: 'selection',
    topic: 'cases',
    subtopic: 'definite-articles-case-table',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct definite article.',
    context: 'Plural, dative',
    options: ['die', 'der', 'den', 'dem'],
    answer: 2,
    explanation: 'Plural dative takes den.',
    tags: ['cases', 'articles', 'dative', 'plural'],
  },
  {
    id: 'de-grammar-case-table-selection-008',
    type: 'selection',
    topic: 'cases',
    subtopic: 'definite-articles-case-table',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article in context.',
    context: 'Ich sehe ___ Mann.',
    options: ['der', 'den', 'dem', 'des'],
    answer: 1,
    explanation: 'Mann is the direct object here, so use masculine accusative: den Mann.',
    tags: ['cases', 'articles', 'accusative', 'context'],
  },
  {
    id: 'de-grammar-case-table-selection-009',
    type: 'selection',
    topic: 'cases',
    subtopic: 'definite-articles-case-table',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct article in context.',
    context: 'Ich helfe ___ Frau.',
    options: ['die', 'der', 'das', 'dem'],
    answer: 1,
    explanation: 'Helfen takes the dative, so use der Frau.',
    tags: ['cases', 'articles', 'dative', 'context'],
  },
  {
    id: 'de-grammar-case-table-selection-010',
    type: 'selection',
    topic: 'cases',
    subtopic: 'definite-articles-case-table',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct article in context.',
    context: 'Die Farbe ___ Hauses ist schoen.',
    options: ['das', 'dem', 'des', 'der'],
    answer: 2,
    explanation: 'This is a genitive relationship: die Farbe des Hauses.',
    tags: ['cases', 'articles', 'genitive', 'context'],
  },
  {
    id: 'de-grammar-case-table-freetype-001',
    type: 'free-type',
    topic: 'cases',
    subtopic: 'definite-articles-case-table',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the correct article.',
    context: 'Neuter, dative ->',
    answers: ['dem'],
    explanation: 'Neuter dative takes dem.',
    tags: ['cases', 'articles', 'dative', 'freetype'],
  },
  {
    id: 'de-grammar-case-table-freetype-002',
    type: 'free-type',
    topic: 'cases',
    subtopic: 'definite-articles-case-table',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the correct article.',
    context: 'Plural, genitive ->',
    answers: ['der'],
    explanation: 'Plural genitive takes der.',
    tags: ['cases', 'articles', 'genitive', 'freetype'],
  },
  {
    id: 'de-grammar-case-table-multiselect-001',
    type: 'multiselect',
    topic: 'cases',
    subtopic: 'definite-articles-case-table',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Select all forms that are dative articles.',
    options: ['dem', 'den', 'der', 'des', 'die'],
    answers: [0, 1, 2],
    explanation: 'Dative forms are dem for masculine and neuter, der for feminine, and den for plural.',
    tags: ['cases', 'articles', 'dative', 'multiselect'],
  },
]

export default exercises
