import type { Exercise } from '../types/exercise'

// Relativpronomen (Relative Pronouns)
// Used to introduce relative clauses (Relativsätze)
// Forms are almost identical to definite articles, with some exceptions in Dativ/Genitiv
// Key differences: Dat. Pl. = denen; Gen. = dessen/deren

const exercises: Exercise[] = [
  {
    id: 'de-grammar-relativ-nom-masc-001',
    type: 'selection',
    topic: 'Relativpronomen',
    subtopic: 'nominative',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct relative pronoun: "Der Mann, ___ dort steht, ist mein Vater." (der Mann = masc.)',
    options: ['der', 'den', 'dem', 'dessen'],
    answer: 0,
    explanation: '"der Mann" = masculine. The relative pronoun is subject of the relative clause → Nominativ masc. = "der".',
    grammarNote: 'Rel. pronouns (like definite articles, mostly):\nNom: der / die / das / die\nAkk: den / die / das / die\nDat: dem / der / dem / denen\nGen: dessen / deren / dessen / deren',
    tags: ['relativpronomen', 'nominativ', 'maskulin'],
  },
  {
    id: 'de-grammar-relativ-akk-masc-001',
    type: 'selection',
    topic: 'Relativpronomen',
    subtopic: 'accusative',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct relative pronoun: "Das Buch, ___ ich lese, ist interessant." (das Buch = neut.)',
    options: ['das', 'dem', 'dessen', 'der'],
    answer: 0,
    explanation: '"das Buch" = neuter, and it is the object of "lese" → Akkusativ neut. = "das".',
    tags: ['relativpronomen', 'akkusativ', 'neutrum'],
  },
  {
    id: 'de-grammar-relativ-dat-fem-001',
    type: 'selection',
    topic: 'Relativpronomen',
    subtopic: 'dative',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Choose the correct relative pronoun: "Die Frau, ___ ich geholfen habe, ist nett." (die Frau = fem.)',
    options: ['der', 'die', 'deren', 'denen'],
    answer: 0,
    explanation: '"helfen" takes Dative. "die Frau" is feminine. Dativ fem. = "der". "Die Frau, der ich geholfen habe, ist nett."',
    tags: ['relativpronomen', 'dativ', 'feminin'],
  },
  {
    id: 'de-grammar-relativ-gen-001',
    type: 'selection',
    topic: 'Relativpronomen',
    subtopic: 'genitive',
    language: 'de',
    group: 'grammar',
    level: 'B2',
    difficulty: 4,
    prompt: 'Choose the correct relative pronoun: "Der Freund, ___ Auto kaputt ist, kommt zu mir." (der Freund = masc.)',
    options: ['dessen', 'deren', 'denen', 'dem'],
    answer: 0,
    explanation: 'Genitive masculine = "dessen". "Der Freund, dessen Auto kaputt ist..." = whose car is broken.',
    tags: ['relativpronomen', 'genitiv', 'maskulin', 'dessen'],
  },
  {
    id: 'de-grammar-relativ-pl-dat-001',
    type: 'selection',
    topic: 'Relativpronomen',
    subtopic: 'dative plural',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Choose the correct relative pronoun: "Die Kinder, mit ___ ich gespielt habe, sind nett."',
    options: ['denen', 'den', 'die', 'deren'],
    answer: 0,
    explanation: 'Dative plural relative pronoun = "denen" (not "den" like the definite article). "Die Kinder, mit denen ich gespielt habe."',
    tags: ['relativpronomen', 'dativ', 'plural', 'denen'],
  },
  {
    id: 'de-grammar-relativ-word-order-001',
    type: 'selection',
    topic: 'Relativpronomen',
    subtopic: 'word order in Relativsatz',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Where does the verb go in a relative clause?',
    options: [
      'At the end of the relative clause',
      'Immediately after the relative pronoun',
      'At the beginning',
      'Before the relative pronoun',
    ],
    answer: 0,
    explanation: 'A relative clause is a Nebensatz → verb goes to the end. "Das Buch, das ich lese, ist interessant." (lese = end)',
    tags: ['relativpronomen', 'word-order', 'nebensatz'],
  },
  {
    id: 'de-grammar-relativ-deren-001',
    type: 'selection',
    topic: 'Relativpronomen',
    subtopic: 'genitive — deren',
    language: 'de',
    group: 'grammar',
    level: 'B2',
    difficulty: 4,
    prompt: 'Choose the correct relative pronoun: "Die Frau, ___ Kinder ich kenne, wohnt nebenan."',
    options: ['deren', 'dessen', 'denen', 'der'],
    answer: 0,
    explanation: 'Genitive feminine = "deren". "Die Frau, deren Kinder ich kenne..." = whose children I know.',
    tags: ['relativpronomen', 'genitiv', 'feminin', 'deren'],
  },
  {
    id: 'de-grammar-relativ-multiselect-001',
    type: 'multiselect',
    topic: 'Relativpronomen',
    subtopic: 'relative pronoun identification',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Which sentences use relative pronouns correctly? (Select all that apply)',
    options: [
      'Das ist der Mann, der hier arbeitet.',
      'Das ist die Frau, dem ich helfe.',
      'Das ist das Kind, das lacht.',
      'Das sind die Leute, denen wir danken.',
    ],
    answers: [0, 2, 3],
    explanation: '"dem" in option 1 is wrong — "Frau" is feminine, Dativ needs "der". All others are correct.',
    tags: ['relativpronomen', 'identification'],
  },
]

export default exercises
