import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-grammar-personal-pronouns-selection-001',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'personal-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form.',
    context: 'ich -> accusative',
    options: ['ich', 'mich', 'mir', 'mein'],
    answer: 1,
    explanation: 'The accusative form of ich is mich.',
    tags: ['pronouns', 'personal', 'accusative'],
  },
  {
    id: 'de-grammar-personal-pronouns-selection-002',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'personal-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form.',
    context: 'du -> dative',
    options: ['du', 'dich', 'dir', 'dein'],
    answer: 2,
    explanation: 'The dative form of du is dir.',
    tags: ['pronouns', 'personal', 'dative'],
  },
  {
    id: 'de-grammar-personal-pronouns-selection-003',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'personal-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form.',
    context: 'er -> accusative',
    options: ['er', 'ihn', 'ihm', 'sein'],
    answer: 1,
    explanation: 'The accusative form of er is ihn.',
    tags: ['pronouns', 'personal', 'accusative'],
  },
  {
    id: 'de-grammar-personal-pronouns-selection-004',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'personal-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form.',
    context: 'sie (she) -> dative',
    options: ['sie', 'ihr', 'ihnen', 'mich'],
    answer: 1,
    explanation: 'The dative form of sie for she is ihr.',
    tags: ['pronouns', 'personal', 'dative'],
  },
  {
    id: 'de-grammar-personal-pronouns-selection-005',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'personal-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form.',
    context: 'wir -> accusative',
    options: ['wir', 'uns', 'euch', 'ihnen'],
    answer: 1,
    explanation: 'The accusative form of wir is uns.',
    tags: ['pronouns', 'personal', 'accusative'],
  },
  {
    id: 'de-grammar-personal-pronouns-selection-006',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'personal-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form.',
    context: 'ihr -> dative',
    options: ['ihr', 'euch', 'uns', 'ihnen'],
    answer: 1,
    explanation: 'The dative form of ihr is euch.',
    tags: ['pronouns', 'personal', 'dative'],
  },
  {
    id: 'de-grammar-personal-pronouns-selection-007',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'personal-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct form in context.',
    context: 'Er sieht ___. (I)',
    options: ['ich', 'mir', 'mich', 'mein'],
    answer: 2,
    explanation: 'Sehen takes the accusative, so use mich.',
    tags: ['pronouns', 'personal', 'accusative', 'context'],
  },
  {
    id: 'de-grammar-personal-pronouns-selection-008',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'personal-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct form in context.',
    context: 'Ich helfe ___. (he)',
    options: ['er', 'ihn', 'ihm', 'sein'],
    answer: 2,
    explanation: 'Helfen takes the dative, so use ihm.',
    tags: ['pronouns', 'personal', 'dative', 'context'],
  },
  {
    id: 'de-grammar-personal-pronouns-selection-009',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'personal-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct form in context.',
    context: 'Ich schreibe ___ morgen. (you, formal)',
    options: ['Sie', 'Ihnen', 'dir', 'euch'],
    answer: 1,
    explanation: 'Schreiben to a person here takes the dative-like indirect object form in this exercise pattern: Ihnen.',
    tags: ['pronouns', 'personal', 'formal', 'dative'],
  },
  {
    id: 'de-grammar-personal-pronouns-selection-010',
    type: 'selection',
    topic: 'pronouns',
    subtopic: 'personal-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct form in context.',
    context: 'Wir sehen ___. (they)',
    options: ['sie', 'ihnen', 'ihr', 'euch'],
    answer: 0,
    explanation: 'The accusative form of sie for they is also sie.',
    tags: ['pronouns', 'personal', 'accusative', 'plural'],
  },
  {
    id: 'de-grammar-personal-pronouns-freetype-001',
    type: 'free-type',
    topic: 'pronouns',
    subtopic: 'personal-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the correct form.',
    context: 'es -> dative',
    answers: ['ihm'],
    explanation: 'The dative form of es is ihm.',
    tags: ['pronouns', 'personal', 'dative', 'freetype'],
  },
  {
    id: 'de-grammar-personal-pronouns-freetype-002',
    type: 'free-type',
    topic: 'pronouns',
    subtopic: 'personal-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the correct form.',
    context: 'du -> accusative',
    answers: ['dich'],
    explanation: 'The accusative form of du is dich.',
    tags: ['pronouns', 'personal', 'accusative', 'freetype'],
  },
  {
    id: 'de-grammar-personal-pronouns-multiselect-001',
    type: 'multiselect',
    topic: 'pronouns',
    subtopic: 'personal-pronouns-cases',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Select all dative pronoun forms.',
    options: ['mir', 'dich', 'ihr', 'ihm', 'uns', 'er'],
    answers: [0, 2, 3, 4],
    explanation: 'mir, ihr, ihm, and uns are dative forms in this list.',
    tags: ['pronouns', 'personal', 'dative', 'multiselect'],
  },
]

export default exercises
