import type { Exercise } from '../types/exercise'

// Konjunktionen (Conjunctions)
// Koordinierende (Coordinating): und, oder, aber, denn, sondern — no change in word order
// Subordinierende (Subordinating): weil, dass, wenn, ob, als, obwohl — verb to end

const exercises: Exercise[] = [
  {
    id: 'de-grammar-konj-koordinierend-001',
    type: 'multiselect',
    topic: 'Konjunktionen',
    subtopic: 'koordinierende Konjunktionen',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Which are coordinating conjunctions (no change to word order)? (Select all that apply)',
    options: ['und', 'weil', 'aber', 'denn', 'dass'],
    answers: [0, 2, 3],
    explanation: '"und" (and), "aber" (but), "denn" (because/for) are coordinating. "weil" and "dass" are subordinating (verb goes to end).',
    grammarNote: 'Coordinating (no verb movement): und, oder, aber, denn, sondern\nSubordinating (verb to end): weil, dass, wenn, ob, als, obwohl, damit…',
    tags: ['konjunktionen', 'koordinierend'],
  },
  {
    id: 'de-grammar-konj-weil-order-001',
    type: 'selection',
    topic: 'Konjunktionen',
    subtopic: 'weil — word order',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct "weil"-clause:',
    options: [
      'Ich bleibe zu Hause, weil ich krank bin.',
      'Ich bleibe zu Hause, weil ich bin krank.',
      'Ich bleibe zu Hause, weil bin ich krank.',
      'Weil ich bin krank, bleibe ich zu Hause.',
    ],
    answer: 0,
    explanation: '"weil" sends the verb to the end of the clause: "weil ich krank BIN". "Ich bleibe zu Hause, weil ich krank bin."',
    tags: ['konjunktionen', 'weil', 'word-order'],
  },
  {
    id: 'de-grammar-konj-denn-vs-weil-001',
    type: 'selection',
    topic: 'Konjunktionen',
    subtopic: 'denn vs weil',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What is the difference between "denn" and "weil"?',
    options: [
      '"denn" keeps normal word order; "weil" sends verb to end',
      '"denn" sends verb to end; "weil" keeps normal order',
      'They are completely interchangeable',
      '"denn" is only used in written German',
    ],
    answer: 0,
    explanation: '"denn" is coordinating → normal word order: "Ich bleibe zu Hause, denn ich bin krank." "weil" is subordinating → verb to end: "…weil ich krank bin."',
    tags: ['konjunktionen', 'denn', 'weil'],
  },
  {
    id: 'de-grammar-konj-dass-001',
    type: 'selection',
    topic: 'Konjunktionen',
    subtopic: 'dass',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct "dass"-clause:',
    options: [
      'Ich weiß, dass du Recht hast.',
      'Ich weiß, dass du hast Recht.',
      'Ich weiß dass, du Recht hast.',
      'Ich weiß, dass hast du Recht.',
    ],
    answer: 0,
    explanation: '"dass" is subordinating → verb to end. "Ich weiß, dass du Recht HAST."',
    tags: ['konjunktionen', 'dass', 'word-order'],
  },
  {
    id: 'de-grammar-konj-aber-sondern-001',
    type: 'selection',
    topic: 'Konjunktionen',
    subtopic: 'aber vs sondern',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Choose the correct sentence: "Er ist nicht krank, ___ müde."',
    options: ['sondern', 'aber', 'denn', 'weil'],
    answer: 0,
    explanation: '"sondern" is used after a negation to give the correct information (not X, but rather Y). "Er ist nicht krank, sondern müde." "aber" is used for simple contrast without negation.',
    grammarNote: '"aber" = but (general contrast)\n"sondern" = but rather (after a negation, correcting)',
    tags: ['konjunktionen', 'aber', 'sondern'],
  },
  {
    id: 'de-grammar-konj-obwohl-001',
    type: 'selection',
    topic: 'Konjunktionen',
    subtopic: 'obwohl (although)',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Choose the correct sentence using "obwohl":',
    options: [
      'Er geht spazieren, obwohl es regnet.',
      'Er geht spazieren, obwohl es regnet ist.',
      'Obwohl regnet es, er geht spazieren.',
      'Er geht spazieren obwohl, es regnet.',
    ],
    answer: 0,
    explanation: '"obwohl" (although) is subordinating → verb to end of clause. "obwohl es REGNET" (verb at end). If obwohl-clause is first, main clause inverts: "Obwohl es regnet, geht er spazieren."',
    tags: ['konjunktionen', 'obwohl', 'word-order'],
  },
  {
    id: 'de-grammar-konj-als-wenn-001',
    type: 'selection',
    topic: 'Konjunktionen',
    subtopic: 'als vs wenn',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Which word correctly fills: "___ ich jung war, spielte ich gern Fußball." (one-time past event)',
    options: ['Als', 'Wenn', 'Ob', 'Weil'],
    answer: 0,
    explanation: '"als" = when (one single time in the past). "wenn" = when/whenever (repeated action or future). "Als ich jung war…" (specific time in the past).',
    grammarNote: '"als" = one-time past event\n"wenn" = repeated past action OR present/future conditions',
    tags: ['konjunktionen', 'als', 'wenn'],
  },
  {
    id: 'de-grammar-konj-ob-001',
    type: 'selection',
    topic: 'Konjunktionen',
    subtopic: 'ob (whether/if)',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Translate: "I don\'t know whether he is coming."',
    options: [
      'Ich weiß nicht, ob er kommt.',
      'Ich weiß nicht, wenn er kommt.',
      'Ich weiß nicht, falls er kommt.',
      'Ich weiß nicht, ob kommt er.',
    ],
    answer: 0,
    explanation: '"ob" = whether/if (in indirect yes/no questions). Verb goes to end. "Ich weiß nicht, ob er kommt."',
    tags: ['konjunktionen', 'ob', 'indirect-question'],
  },
]

export default exercises
