import type { Exercise } from '../types/exercise'

// Konjunktiv II — subjunctive II
// Used for: hypothetical situations, polite requests, wishes, unreal conditions
// Common forms: wäre (sein), hätte (haben), würde + Infinitiv (most other verbs)
// Modal verbs have their own Konjunktiv II forms: könnte, müsste, dürfte, sollte, wollte

const exercises: Exercise[] = [
  {
    id: 'de-grammar-konj2-ware-001',
    type: 'selection',
    topic: 'Konjunktiv II',
    subtopic: 'sein → wäre',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What is the Konjunktiv II form of "sein" for "ich"?',
    options: ['wäre', 'sei', 'würde sein', 'war'],
    answer: 0,
    explanation: '"sein" Konjunktiv II: ich wäre, du wärst, er/sie/es wäre, wir wären, ihr wärt, sie wären.',
    grammarNote: 'Most used Konjunktiv II forms:\nsein → wäre\nhaben → hätte\nwerden → würde\nModals: könnte, müsste, sollte, dürfte',
    tags: ['konjunktiv2', 'sein', 'ware'],
  },
  {
    id: 'de-grammar-konj2-hatte-001',
    type: 'selection',
    topic: 'Konjunktiv II',
    subtopic: 'haben → hätte',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What is the Konjunktiv II form of "haben" for "er"?',
    options: ['hätte', 'hatte', 'hat', 'würde haben'],
    answer: 0,
    explanation: '"haben" Konjunktiv II: ich hätte, du hättest, er/sie/es hätte, wir hätten, ihr hättet, sie hätten.',
    tags: ['konjunktiv2', 'haben', 'hatte'],
  },
  {
    id: 'de-grammar-konj2-wurde-001',
    type: 'selection',
    topic: 'Konjunktiv II',
    subtopic: 'würde + Infinitiv',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 2,
    prompt: 'How do you form Konjunktiv II for most regular verbs?',
    options: [
      'würde + Infinitiv',
      'hätte + Partizip II',
      'wäre + Infinitiv',
      'Stem + -te ending',
    ],
    answer: 0,
    explanation: 'For most verbs, Konjunktiv II = "würde" + Infinitiv. "Ich würde gehen." (I would go.)',
    tags: ['konjunktiv2', 'wurde', 'formation'],
  },
  {
    id: 'de-grammar-konj2-hypothetical-001',
    type: 'selection',
    topic: 'Konjunktiv II',
    subtopic: 'wenn-clauses (unreal conditions)',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Complete the unreal conditional: "Wenn ich Geld ___, ___ ich ein Auto kaufen."',
    options: [
      'hätte … würde',
      'habe … werde',
      'hatte … würde',
      'hätte … werde',
    ],
    answer: 0,
    explanation: 'Unreal "wenn"-clause uses Konjunktiv II throughout: "Wenn ich Geld hätte, würde ich ein Auto kaufen."',
    tags: ['konjunktiv2', 'wenn', 'unreal-condition'],
  },
  {
    id: 'de-grammar-konj2-polite-001',
    type: 'selection',
    topic: 'Konjunktiv II',
    subtopic: 'polite requests',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Which sentence is a polite request using Konjunktiv II?',
    options: [
      'Könnten Sie mir bitte helfen?',
      'Können Sie mir bitte helfen?',
      'Sie helfen mir bitte!',
      'Sie sollen mir helfen.',
    ],
    answer: 0,
    explanation: '"Könnten" is Konjunktiv II of "können" → used for polite requests. "Könnten Sie mir helfen?" = "Could you help me?" (more polite than "Können")',
    tags: ['konjunktiv2', 'polite-request', 'konnte'],
  },
  {
    id: 'de-grammar-konj2-wish-001',
    type: 'selection',
    topic: 'Konjunktiv II',
    subtopic: 'wishes with "wenn nur"',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Translate: "If only I were rich!"',
    options: [
      'Wenn ich nur reich wäre!',
      'Wenn ich nur reich bin!',
      'Wenn ich nur reich war!',
      'Wenn ich nur reich würde sein!',
    ],
    answer: 0,
    explanation: 'Wishes contrary to fact: "Wenn ich nur … wäre!" (Konjunktiv II of sein = wäre)',
    tags: ['konjunktiv2', 'wishes', 'ware'],
  },
  {
    id: 'de-grammar-konj2-modal-konnte-001',
    type: 'free-type',
    topic: 'Konjunktiv II',
    subtopic: 'modal verbs',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Fill in the Konjunktiv II of "können" for "ich": "Ich ___ das verstehen."',
    answers: ['könnte'],
    caseSensitive: false,
    hint: 'können → Konjunktiv II: könnte (Präteritum + umlaut)',
    explanation: '"können" Konjunktiv II = "könnte". "Ich könnte das verstehen." (I could understand that.)',
    tags: ['konjunktiv2', 'können', 'konnte'],
  },
  {
    id: 'de-grammar-konj2-musste-001',
    type: 'selection',
    topic: 'Konjunktiv II',
    subtopic: 'modal verbs',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What is the Konjunktiv II of "müssen" for "du"?',
    options: ['müsstest', 'müsste', 'musst', 'müsstet'],
    answer: 0,
    explanation: '"müssen" Konjunktiv II: ich müsste, du müsstest, er/sie/es müsste, wir müssten, ihr müsstet, sie müssten.',
    tags: ['konjunktiv2', 'müssen', 'musste'],
  },
]

export default exercises
