import type { Exercise } from '../types/exercise'

// Indirekte Rede (Indirect Speech) — reporting what someone said
// Konjunktiv I is the "proper" form for indirect speech (especially in formal/written German)
// Konjunktiv I: er sage, er habe, er sei, er komme…
// If Konjunktiv I = Präsens form → use Konjunktiv II instead (to distinguish)

const exercises: Exercise[] = [
  {
    id: 'de-grammar-ind-rede-konjunktiv1-sein-001',
    type: 'selection',
    topic: 'Indirekte Rede',
    subtopic: 'Konjunktiv I — sein',
    language: 'de',
    group: 'grammar',
    level: 'B2',
    difficulty: 4,
    prompt: 'Direct: "Ich bin krank." → Indirect: "Er sagt, er ___ krank."',
    options: ['sei', 'ist', 'wäre', 'war'],
    answer: 0,
    explanation: 'Indirect speech uses Konjunktiv I. "sein" Konjunktiv I for er/sie/es = "sei". "Er sagt, er sei krank."',
    grammarNote: 'Konjunktiv I (er/sie/es):\nsein → sei | haben → habe | kommen → komme | gehen → gehe\nUsed in news, reports, formal writing',
    tags: ['indirekte-rede', 'konjunktiv1', 'sein'],
  },
  {
    id: 'de-grammar-ind-rede-konjunktiv1-haben-001',
    type: 'selection',
    topic: 'Indirekte Rede',
    subtopic: 'Konjunktiv I — haben',
    language: 'de',
    group: 'grammar',
    level: 'B2',
    difficulty: 4,
    prompt: 'Direct: "Ich habe keine Zeit." → Indirect: "Sie sagt, sie ___ keine Zeit."',
    options: ['habe', 'hat', 'hätte', 'hatte'],
    answer: 0,
    explanation: 'Konjunktiv I of "haben" for er/sie/es = "habe". "Sie sagt, sie habe keine Zeit."',
    tags: ['indirekte-rede', 'konjunktiv1', 'haben'],
  },
  {
    id: 'de-grammar-ind-rede-reporting-verb-001',
    type: 'multiselect',
    topic: 'Indirekte Rede',
    subtopic: 'reporting verbs',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Which verbs are typically used to introduce indirect speech? (Select all that apply)',
    options: ['sagen', 'berichten', 'meinen', 'gehen', 'behaupten'],
    answers: [0, 1, 2, 4],
    explanation: '"sagen" (to say), "berichten" (to report), "meinen" (to think/mean), "behaupten" (to claim) introduce indirect speech. "gehen" is unrelated.',
    tags: ['indirekte-rede', 'reporting-verbs'],
  },
  {
    id: 'de-grammar-ind-rede-dass-001',
    type: 'selection',
    topic: 'Indirekte Rede',
    subtopic: 'with dass-clause',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Which correctly reports the statement "Ich komme morgen"?',
    options: [
      'Er sagt, dass er morgen komme.',
      'Er sagt, dass er morgen kommt.',
      'Er sagt, er morgen kommt.',
      'Er sagt, dass er morgen kommen.',
    ],
    answer: 0,
    explanation: 'With "dass", verb goes to end of clause (Nebensatz) in Konjunktiv I: "komme". "Er sagt, dass er morgen komme."',
    tags: ['indirekte-rede', 'dass', 'word-order'],
  },
  {
    id: 'de-grammar-ind-rede-question-001',
    type: 'selection',
    topic: 'Indirekte Rede',
    subtopic: 'indirect questions',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'How do you report the question "Wo wohnst du?"?',
    options: [
      'Er fragte, wo sie wohne.',
      'Er fragte, wo sie wohnt.',
      'Er fragte, wo wohne sie.',
      'Er fragte, dass sie wo wohne.',
    ],
    answer: 0,
    explanation: 'Indirect questions use Konjunktiv I with the question word as subordinating conjunction, verb at end: "Er fragte, wo sie wohne."',
    tags: ['indirekte-rede', 'indirect-questions'],
  },
  {
    id: 'de-grammar-ind-rede-konjunktiv2-fallback-001',
    type: 'selection',
    topic: 'Indirekte Rede',
    subtopic: 'Konjunktiv II as fallback',
    language: 'de',
    group: 'grammar',
    level: 'B2',
    difficulty: 4,
    prompt: 'When is Konjunktiv II used instead of Konjunktiv I in indirect speech?',
    options: [
      'When Konjunktiv I looks identical to the Präsens indicative form',
      'In everyday spoken German only',
      'With modal verbs always',
      'When the subject is plural',
    ],
    answer: 0,
    explanation: 'If Konjunktiv I = Präsens (ambiguous), switch to Konjunktiv II. E.g. "sie kommen" (Präsens) = "sie kommen" (Konj. I) → use "sie kämen" (Konj. II).',
    tags: ['indirekte-rede', 'konjunktiv2', 'fallback'],
  },
]

export default exercises
