import type { Exercise } from '../types/exercise'

// Präpositionen mit Dativ
// aus, bei, mit, nach, seit, von, zu, außer, gegenüber, ab

const exercises: Exercise[] = [
  {
    id: 'de-grammar-prap-dat-list-001',
    type: 'multiselect',
    topic: 'Präpositionen Dativ',
    subtopic: 'identify Dativ prepositions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Which prepositions always take Dativ? (Select all that apply)',
    options: ['mit', 'für', 'bei', 'nach', 'gegen', 'von'],
    answers: [0, 2, 3, 5],
    explanation: '"mit", "bei", "nach", "von" are Dativ prepositions. "für" and "gegen" take Akkusativ.',
    grammarNote: 'Dativ prepositions: aus, bei, mit, nach, seit, von, zu, außer, gegenüber, ab',
    tags: ['präpositionen', 'dativ', 'identification'],
  },
  {
    id: 'de-grammar-prap-dat-mit-001',
    type: 'selection',
    topic: 'Präpositionen Dativ',
    subtopic: 'mit',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete: "Ich fahre mit ___ Zug." (der Zug = masc.)',
    options: ['dem', 'den', 'der', 'des'],
    answer: 0,
    explanation: '"mit" + Dativ. "der Zug" (masc.) → Dativ = "dem Zug". "Ich fahre mit dem Zug."',
    tags: ['präpositionen', 'dativ', 'mit'],
  },
  {
    id: 'de-grammar-prap-dat-aus-001',
    type: 'selection',
    topic: 'Präpositionen Dativ',
    subtopic: 'aus',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete: "Er kommt aus ___ Schweiz." (die Schweiz = fem.)',
    options: ['der', 'die', 'dem', 'den'],
    answer: 0,
    explanation: '"aus" + Dativ. "die Schweiz" (fem.) → Dativ = "der Schweiz". "Er kommt aus der Schweiz."',
    tags: ['präpositionen', 'dativ', 'aus'],
  },
  {
    id: 'de-grammar-prap-dat-seit-001',
    type: 'selection',
    topic: 'Präpositionen Dativ',
    subtopic: 'seit — meaning',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: '"Seit" is used for…',
    options: [
      'Duration from past to now (since/for)',
      'Future duration',
      'Past completed action',
      'Direction/destination',
    ],
    answer: 0,
    explanation: '"seit" + Dativ = from a past point up to now, with Präsens (or Präteritum). "Ich lerne seit drei Jahren Deutsch." (I have been learning German for 3 years.)',
    tags: ['präpositionen', 'dativ', 'seit'],
  },
  {
    id: 'de-grammar-prap-dat-zu-001',
    type: 'selection',
    topic: 'Präpositionen Dativ',
    subtopic: 'zu',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete: "Ich gehe zu ___ Arzt." (der Arzt = masc.)',
    options: ['dem', 'den', 'der', 'des'],
    answer: 0,
    explanation: '"zu" + Dativ. "der Arzt" (masc.) → Dativ = "dem Arzt". Common contraction: "zum" (zu + dem).',
    grammarNote: 'Contractions: zu + dem = zum | zu + der = zur | von + dem = vom | bei + dem = beim',
    tags: ['präpositionen', 'dativ', 'zu', 'contraction'],
  },
  {
    id: 'de-grammar-prap-dat-von-001',
    type: 'selection',
    topic: 'Präpositionen Dativ',
    subtopic: 'von',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete: "Das Buch ist von ___ Lehrerin." (die Lehrerin = fem.)',
    options: ['der', 'die', 'dem', 'den'],
    answer: 0,
    explanation: '"von" + Dativ. "die Lehrerin" (fem.) → Dativ = "der Lehrerin". "Das Buch ist von der Lehrerin."',
    tags: ['präpositionen', 'dativ', 'von'],
  },
  {
    id: 'de-grammar-prap-dat-nach-001',
    type: 'selection',
    topic: 'Präpositionen Dativ',
    subtopic: 'nach — meaning',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Which sentence uses "nach" correctly for direction to a country/city?',
    options: [
      'Ich fahre nach Berlin.',
      'Ich fahre zu Berlin.',
      'Ich fahre in Berlin.',
      'Ich fahre an Berlin.',
    ],
    answer: 0,
    explanation: '"nach" + place name (without article) = direction. "Ich fahre nach Berlin/Deutschland." But "in die Türkei" (countries with articles need "in + Akkusativ").',
    tags: ['präpositionen', 'dativ', 'nach', 'direction'],
  },
  {
    id: 'de-grammar-prap-dat-contraction-001',
    type: 'multiselect',
    topic: 'Präpositionen Dativ',
    subtopic: 'contractions',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Which contractions are correct? (Select all that apply)',
    options: ['zu + dem = zum', 'von + dem = vom', 'bei + dem = beim', 'mit + dem = mitdem'],
    answers: [0, 1, 2],
    explanation: '"zum", "vom", "beim" are standard contractions. "mit + dem" does NOT contract.',
    tags: ['präpositionen', 'dativ', 'contractions'],
  },
]

export default exercises
