import type { Exercise } from '../types/exercise'

// Adjective declension in German:
// Weak (after der/die/das): -e in Nom.sg, -en everywhere else
// Mixed (after ein/eine/ein): -er/-e/-es in Nom.sg, -en everywhere else
// Strong (no article): adjective carries gender/case marker

const exercises: Exercise[] = [
  // --- Weak declension: Nominative ---
  {
    id: 'de-grammar-adj-weak-nom-masc-001',
    type: 'selection',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 2,
    prompt: 'Choose the correct adjective ending. (Weak declension — nominative masculine)',
    context: 'Der alt___ Mann schläft.',
    options: ['-e', '-en', '-er', '-es'],
    answer: 0,
    explanation:
      'After "der" (definite article), nominative masculine → ending is -e. "Der alte Mann."',
    tags: ['adjectives', 'weak-declension', 'nominative', 'masculine'],
  },
  {
    id: 'de-grammar-adj-weak-nom-fem-001',
    type: 'selection',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 2,
    prompt: 'Choose the correct adjective ending. (Weak declension — nominative feminine)',
    context: 'Die jung___ Frau liest.',
    options: ['-e', '-en', '-er', '-es'],
    answer: 0,
    explanation:
      'After "die" (definite article), nominative feminine → ending is -e. "Die junge Frau."',
    tags: ['adjectives', 'weak-declension', 'nominative', 'feminine'],
  },
  {
    id: 'de-grammar-adj-weak-nom-neut-001',
    type: 'selection',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 2,
    prompt: 'Choose the correct adjective ending. (Weak declension — nominative neuter)',
    context: 'Das klein___ Kind spielt.',
    options: ['-e', '-en', '-er', '-es'],
    answer: 0,
    explanation:
      'After "das" (definite article), nominative neuter → ending is -e. "Das kleine Kind."',
    tags: ['adjectives', 'weak-declension', 'nominative', 'neuter'],
  },

  // --- Weak declension: Accusative ---
  {
    id: 'de-grammar-adj-weak-acc-masc-001',
    type: 'free-type',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 3,
    prompt: 'Fill in the correct adjective form: "groß" (after definite article, accusative masculine).',
    context: 'Ich sehe den ___ Hund.',
    answers: ['großen', 'grossen'],
    caseSensitive: false,
    hint: 'After "den" (accusative masculine) — weak declension ending is -en.',
    explanation:
      'Accusative masculine with definite article → -en. "Ich sehe den großen Hund."',
    tags: ['adjectives', 'weak-declension', 'accusative', 'masculine'],
  },
  {
    id: 'de-grammar-adj-weak-acc-fem-001',
    type: 'selection',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 3,
    prompt: 'Choose the correct adjective ending. (Weak declension — accusative feminine)',
    context: 'Er kauft die rot___ Tasche.',
    options: ['-e', '-en', '-er', '-em'],
    answer: 0,
    explanation:
      'Accusative feminine with definite article → -e. "Er kauft die rote Tasche." (Feminine accusative = same as nominative after definite article.)',
    tags: ['adjectives', 'weak-declension', 'accusative', 'feminine'],
  },

  // --- Weak declension: Dative ---
  {
    id: 'de-grammar-adj-weak-dat-masc-001',
    type: 'free-type',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 3,
    prompt: 'Fill in the correct adjective form: "alt" (after definite article, dative masculine).',
    context: 'Er hilft dem ___ Mann.',
    answers: ['alten'],
    caseSensitive: false,
    hint: 'After "dem" (dative masculine) — weak declension ending is always -en.',
    explanation:
      'Dative with definite article → always -en. "Er hilft dem alten Mann."',
    tags: ['adjectives', 'weak-declension', 'dative', 'masculine'],
  },
  {
    id: 'de-grammar-adj-weak-dat-fem-001',
    type: 'free-type',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 3,
    prompt: 'Fill in the correct adjective form: "schön" (after definite article, dative feminine).',
    context: 'Er schenkt der ___ Frau Blumen.',
    answers: ['schönen', 'schoenen'],
    caseSensitive: false,
    hint: 'After "der" (dative feminine) — weak declension ending is always -en.',
    explanation:
      'Dative feminine with definite article → -en. "Er schenkt der schönen Frau Blumen."',
    tags: ['adjectives', 'weak-declension', 'dative', 'feminine'],
  },

  // --- Mixed declension: Nominative ---
  {
    id: 'de-grammar-adj-mixed-nom-masc-001',
    type: 'selection',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 3,
    prompt: 'Choose the correct adjective ending. (Mixed declension — nominative masculine)',
    context: 'Ein alt___ Mann steht dort.',
    options: ['-er', '-e', '-es', '-en'],
    answer: 0,
    explanation:
      'After "ein" (indefinite article), nominative masculine → -er. "Ein alter Mann." The adjective must show the masculine marker since "ein" doesn\'t.',
    tags: ['adjectives', 'mixed-declension', 'nominative', 'masculine'],
  },
  {
    id: 'de-grammar-adj-mixed-nom-neut-001',
    type: 'selection',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 3,
    prompt: 'Choose the correct adjective ending. (Mixed declension — nominative neuter)',
    context: 'Ein klein___ Kind lacht.',
    options: ['-es', '-e', '-er', '-en'],
    answer: 0,
    explanation:
      'After "ein" (indefinite article), nominative neuter → -es. "Ein kleines Kind." The adjective must show the neuter marker since "ein" doesn\'t.',
    tags: ['adjectives', 'mixed-declension', 'nominative', 'neuter'],
  },
  {
    id: 'de-grammar-adj-mixed-nom-fem-001',
    type: 'selection',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 3,
    prompt: 'Choose the correct adjective ending. (Mixed declension — nominative feminine)',
    context: 'Eine jung___ Frau singt.',
    options: ['-e', '-er', '-es', '-en'],
    answer: 0,
    explanation:
      'After "eine" (indefinite article), nominative feminine → -e. "Eine junge Frau." Here "eine" already shows the feminine marker, so the adjective takes a weak -e.',
    tags: ['adjectives', 'mixed-declension', 'nominative', 'feminine'],
  },

  // --- Mixed declension: Accusative ---
  {
    id: 'de-grammar-adj-mixed-acc-masc-001',
    type: 'selection',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 3,
    prompt: 'Choose the correct adjective ending. (Mixed declension — accusative masculine)',
    context: 'Ich sehe einen neu___ Film.',
    options: ['-en', '-e', '-er', '-es'],
    answer: 0,
    explanation:
      'After "einen" (accusative masculine), mixed declension uses -en: "einen neuen Film."',
    tags: ['adjectives', 'mixed-declension', 'accusative', 'masculine'],
  },
  {
    id: 'de-grammar-adj-mixed-acc-neut-001',
    type: 'selection',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 3,
    prompt: 'Choose the correct adjective ending. (Mixed declension — accusative neuter)',
    context: 'Ich kaufe ein alt___ Auto.',
    options: ['-es', '-en', '-e', '-er'],
    answer: 0,
    explanation:
      'After "ein" (accusative neuter), mixed declension takes -es: "ein altes Auto."',
    tags: ['adjectives', 'mixed-declension', 'accusative', 'neuter'],
  },

  // --- Strong declension (no article) ---
  {
    id: 'de-grammar-adj-strong-nom-masc-001',
    type: 'selection',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 4,
    prompt: 'Choose the correct adjective ending. (Strong declension — nominative masculine)',
    context: 'Frisch___ Kaffee schmeckt gut.',
    options: ['-er', '-e', '-en', '-es'],
    answer: 0,
    explanation:
      'Without an article, the adjective carries the marker. Nominative masculine takes -er: "frischer Kaffee."',
    tags: ['adjectives', 'strong-declension', 'nominative', 'masculine'],
  },
  {
    id: 'de-grammar-adj-strong-nom-fem-001',
    type: 'selection',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 4,
    prompt: 'Choose the correct adjective ending. (Strong declension — nominative feminine)',
    context: 'Kalt___ Milch steht im Kühlschrank.',
    options: ['-e', '-er', '-en', '-es'],
    answer: 0,
    explanation:
      'Without an article, nominative feminine takes -e: "kalte Milch."',
    tags: ['adjectives', 'strong-declension', 'nominative', 'feminine'],
  },
  {
    id: 'de-grammar-adj-strong-acc-masc-001',
    type: 'free-type',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 4,
    prompt: 'Fill in the correct adjective form: "kalt" (strong declension, accusative masculine).',
    context: 'Ich trinke ___ Kaffee.',
    answers: ['kalten'],
    caseSensitive: false,
    hint: 'No article + accusative masculine uses -en.',
    explanation:
      'In strong declension, accusative masculine takes -en: "Ich trinke kalten Kaffee."',
    tags: ['adjectives', 'strong-declension', 'accusative', 'masculine'],
  },
  {
    id: 'de-grammar-adj-strong-dat-neut-001',
    type: 'free-type',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 4,
    prompt: 'Fill in the correct adjective form: "frisch" (strong declension, dative neuter).',
    context: 'Mit ___ Brot schmeckt die Suppe besser.',
    answers: ['frischem'],
    caseSensitive: false,
    hint: 'No article + dative neuter uses -em.',
    explanation:
      'Strong declension dative neuter takes -em: "Mit frischem Brot ..."',
    tags: ['adjectives', 'strong-declension', 'dative', 'neuter'],
  },
  {
    id: 'de-grammar-adj-strong-gen-fem-001',
    type: 'free-type',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 4,
    prompt: 'Fill in the correct adjective form: "stark" (strong declension, genitive feminine).',
    context: 'Wegen ___ Hitze bleiben wir zu Hause.',
    answers: ['starker'],
    caseSensitive: false,
    hint: 'No article + genitive feminine uses -er.',
    explanation:
      'Strong declension genitive feminine takes -er: "wegen starker Hitze."',
    tags: ['adjectives', 'strong-declension', 'genitive', 'feminine'],
  },
  {
    id: 'de-grammar-adj-weak-gen-pl-001',
    type: 'free-type',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 4,
    prompt: 'Fill in the correct adjective form: "alt" (weak declension, genitive plural).',
    context: 'Die Farbe der ___ Häuser ist schön.',
    answers: ['alten'],
    caseSensitive: false,
    hint: 'With definite article in genitive plural, weak declension uses -en.',
    explanation:
      'Weak declension in genitive plural takes -en: "der alten Häuser."',
    tags: ['adjectives', 'weak-declension', 'genitive', 'plural'],
  },

  // --- Multiselect: identify correct sentences ---
  {
    id: 'de-grammar-adj-multiselect-weak-001',
    type: 'multiselect',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 4,
    prompt: 'Which sentences have the CORRECT adjective ending?',
    options: [
      'Der alte Mann schläft. (nom. masc.)',
      'Ich sehe den alten Hund. (acc. masc.)',
      'Er hilft dem alten Frau. (dat. fem.)',
      'Die junge Mädchen tanzt. (nom. neut.)',
      'Sie kauft die rote Tasche. (acc. fem.)',
    ],
    answers: [0, 1, 4],
    explanation:
      '"dem alten Frau" is wrong — "Frau" is feminine, so it should be "der alten Frau". "Mädchen" is neuter, so "das junge Mädchen" is correct, not "die junge".',
    tags: ['adjectives', 'weak-declension', 'mixed-practice'],
  },
  {
    id: 'de-grammar-adj-multiselect-mixed-001',
    type: 'multiselect',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 4,
    prompt: 'Which sentences have the CORRECT adjective ending? (Mixed declension)',
    options: [
      'Ein alter Mann wohnt hier. (nom. masc.)',
      'Ein kleines Kind weint. (nom. neut.)',
      'Eine schöner Frau lächelt. (nom. fem.)',
      'Ein guten Hund habe ich. (acc. masc.)',
      'Ich habe einen großen Hund. (acc. masc.)',
    ],
    answers: [0, 1, 4],
    explanation:
      '"Eine schöner Frau" is wrong — feminine after eine → -e: "Eine schöne Frau". "Ein guten Hund" is wrong in accusative — "einen guten Hund" is correct (accusative needs "einen").',
    tags: ['adjectives', 'mixed-declension', 'mixed-practice'],
  },
  {
    id: 'de-grammar-adj-multiselect-strong-001',
    type: 'multiselect',
    topic: 'склонение прилагательных',
    subtopic: 'склонение прилагательных',
    language: 'de',
    difficulty: 5,
    prompt: 'Which sentences have the CORRECT adjective ending? (Strong declension)',
    options: [
      'Frischer Kaffee ist lecker. (nom. masc.)',
      'Ich trinke kalt Kaffee. (acc. masc.)',
      'Mit frischem Brot esse ich Suppe. (dat. neut.)',
      'Wegen starker Hitze bleiben wir zu Hause. (gen. fem.)',
      'Kalte Wasser ist gut. (nom. neut.)',
    ],
    answers: [0, 2, 3],
    explanation:
      '"Ich trinke kalt Kaffee" is wrong; accusative masculine needs -en: "kalten Kaffee". "Kalte Wasser" is wrong because Wasser is neuter: "Kaltes Wasser."',
    tags: ['adjectives', 'strong-declension', 'mixed-practice'],
  },
]

export default exercises
