import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-grammar-question-words-selection-001',
    type: 'selection',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct question word.',
    context: 'Nominative: ___ kommt heute?',
    options: ['wer', 'wen', 'wem', 'wessen'],
    answer: 0,
    explanation: 'Use wer for the nominative subject question.',
    tags: ['question-words', 'nominative', 'wer'],
  },
  {
    id: 'de-grammar-question-words-selection-002',
    type: 'selection',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct question word.',
    context: 'Accusative: ___ siehst du?',
    options: ['wer', 'wen', 'wem', 'wessen'],
    answer: 1,
    explanation: 'Use wen for accusative object questions.',
    tags: ['question-words', 'accusative', 'wen'],
  },
  {
    id: 'de-grammar-question-words-selection-003',
    type: 'selection',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct question word.',
    context: 'Dative: ___ hilfst du?',
    options: ['wer', 'wen', 'wem', 'wessen'],
    answer: 2,
    explanation: 'Use wem for dative questions.',
    tags: ['question-words', 'dative', 'wem'],
  },
  {
    id: 'de-grammar-question-words-selection-004',
    type: 'selection',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct question word in context.',
    context: '___ ist dein Lehrer?',
    options: ['Wer', 'Wen', 'Wem', 'Wessen'],
    answer: 0,
    explanation: 'The asked person is the subject, so use Wer?',
    tags: ['question-words', 'nominative', 'context'],
  },
  {
    id: 'de-grammar-question-words-selection-005',
    type: 'selection',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct question word in context.',
    context: '___ besuchst du am Wochenende?',
    options: ['Wer', 'Wen', 'Wem', 'Wessen'],
    answer: 1,
    explanation: 'Besuchen takes an accusative object, so use Wen?',
    tags: ['question-words', 'accusative', 'context'],
  },
  {
    id: 'de-grammar-question-words-selection-006',
    type: 'selection',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct question word in context.',
    context: '___ dankst du fuer die Hilfe?',
    options: ['Wer', 'Wen', 'Wem', 'Wessen'],
    answer: 2,
    explanation: 'Danken takes the dative, so use Wem?',
    tags: ['question-words', 'dative', 'context'],
  },
  {
    id: 'de-grammar-question-words-selection-007',
    type: 'selection',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct question-answer pair.',
    context: '___ siehst du? - Ich sehe meinen Bruder.',
    options: ['Wer', 'Wen', 'Wem', 'Wessen'],
    answer: 1,
    explanation: 'The answer contains a direct object, so the correct question is Wen siehst du?',
    tags: ['question-words', 'accusative', 'pairing'],
  },
  {
    id: 'de-grammar-question-words-selection-008',
    type: 'selection',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct question-answer pair.',
    context: '___ gibst du das Buch? - Ich gebe es meiner Freundin.',
    options: ['Wer', 'Wen', 'Wem', 'Wessen'],
    answer: 2,
    explanation: 'The answer contains a dative recipient, so the correct question is Wem gibst du das Buch?',
    tags: ['question-words', 'dative', 'pairing'],
  },
  {
    id: 'de-grammar-question-words-selection-009',
    type: 'selection',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct question-answer pair.',
    context: '___ arbeitet hier? - Frau Klein arbeitet hier.',
    options: ['Wer', 'Wen', 'Wem', 'Wessen'],
    answer: 0,
    explanation: 'The answer names the subject, so the correct question is Wer arbeitet hier?',
    tags: ['question-words', 'nominative', 'pairing'],
  },
  {
    id: 'de-grammar-question-words-freetype-001',
    type: 'free-type',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the correct question word.',
    context: '___ kommt mit uns?',
    answers: ['Wer', 'wer'],
    explanation: 'This asks about the subject, so use wer.',
    tags: ['question-words', 'nominative', 'freetype'],
  },
  {
    id: 'de-grammar-question-words-freetype-002',
    type: 'free-type',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the correct question word.',
    context: '___ rufst du an?',
    answers: ['Wen', 'wen'],
    explanation: 'Anrufen asks for a direct object here, so use wen.',
    tags: ['question-words', 'accusative', 'freetype'],
  },
  {
    id: 'de-grammar-question-words-freetype-003',
    type: 'free-type',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the correct question word.',
    context: '___ gehoert das Fahrrad?',
    answers: ['Wem', 'wem'],
    explanation: 'Gehoren takes the dative, so use wem.',
    tags: ['question-words', 'dative', 'freetype'],
  },
  {
    id: 'de-grammar-question-words-multiselect-001',
    type: 'multiselect',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Select all sentences that need wem.',
    options: ['___ hilfst du?', '___ siehst du?', '___ gibst du die Blumen?', '___ kommt spaeter?'],
    answers: [0, 2],
    explanation: 'Helfen and geben to a recipient use dative questions with wem.',
    tags: ['question-words', 'dative', 'multiselect'],
  },
  {
    id: 'de-grammar-question-words-multiselect-002',
    type: 'multiselect',
    topic: 'question words',
    subtopic: 'wer-wen-wem',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Select all sentences that need wen.',
    options: ['___ besuchst du?', '___ kennst du?', '___ schreibst du eine E-Mail?', '___ ist das?'],
    answers: [0, 1],
    explanation: 'Besuchen and kennen take the accusative direct object, so these use wen.',
    tags: ['question-words', 'accusative', 'multiselect'],
  },
]

export default exercises
