import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-grammar-gender-plural-selection-001',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-and-plural',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct pair: article + plural.',
    context: 'Lampe',
    options: ['der Lampe / Lampen', 'die Lampe / Lampen', 'das Lampe / Lampen', 'die Lampe / Lampees'],
    answer: 1,
    explanation: 'Lampe is feminine and its plural is Lampen: die Lampe, die Lampen.',
    tags: ['noun-gender', 'plural', 'article'],
  },
  {
    id: 'de-grammar-gender-plural-selection-002',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-and-plural',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct pair: article + plural.',
    context: 'Lehrer',
    options: ['der Lehrer / Lehrer', 'die Lehrer / Lehreren', 'das Lehrer / Lehrer', 'der Lehrer / Lehrers'],
    answer: 0,
    explanation: 'Lehrer is masculine, and the plural is identical in form: der Lehrer, die Lehrer.',
    tags: ['noun-gender', 'plural', 'article'],
  },
  {
    id: 'de-grammar-gender-plural-selection-003',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-and-plural',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct pair: article + plural.',
    context: 'Mädchen',
    options: ['das Mädchen / Mädchen', 'die Mädchen / Mädchen', 'der Mädchen / Mädcher', 'das Mädchen / Mädchens'],
    answer: 0,
    explanation: 'Mädchen is neuter, and diminutives in -chen often keep the same plural form: das Mädchen, die Mädchen.',
    tags: ['noun-gender', 'plural', 'article'],
  },
  {
    id: 'de-grammar-gender-plural-selection-004',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-and-plural',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct pair: article + plural.',
    context: 'Buch',
    options: ['der Buch / Buchen', 'das Buch / Bücher', 'die Buch / Bücher', 'das Buch / Buchs'],
    answer: 1,
    explanation: 'Buch is neuter and its plural is Bücher: das Buch, die Bücher.',
    tags: ['noun-gender', 'plural', 'article'],
  },
  {
    id: 'de-grammar-gender-plural-selection-005',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-and-plural',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct pair: article + plural.',
    context: 'Nation',
    options: ['der Nation / Nationen', 'die Nation / Nationen', 'das Nation / Natione', 'die Nation / Nations'],
    answer: 1,
    explanation: 'Nation is feminine and the plural is Nationen: die Nation, die Nationen.',
    tags: ['noun-gender', 'plural', 'article'],
  },
  {
    id: 'de-grammar-gender-plural-selection-006',
    type: 'selection',
    topic: 'noun gender',
    subtopic: 'gender-and-plural',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct pair: article + plural.',
    context: 'Museum',
    options: ['das Museum / Museen', 'der Museum / Museume', 'die Museum / Museen', 'das Museum / Museums'],
    answer: 0,
    explanation: 'Museum is neuter and the plural is Museen: das Museum, die Museen.',
    tags: ['noun-gender', 'plural', 'article'],
  },
  {
    id: 'de-grammar-gender-plural-freetype-001',
    type: 'free-type',
    topic: 'noun gender',
    subtopic: 'gender-and-plural',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Type the correct article only.',
    context: '___ Zeitung; plural: Zeitungen',
    answers: ['die'],
    explanation: 'Zeitung is feminine: die Zeitung.',
    tags: ['noun-gender', 'plural', 'freetype'],
  },
  {
    id: 'de-grammar-gender-plural-freetype-002',
    type: 'free-type',
    topic: 'noun gender',
    subtopic: 'gender-and-plural',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Type the plural form only.',
    context: 'das Buch ->',
    answers: ['Bücher'],
    explanation: 'The plural of Buch is Bücher.',
    tags: ['noun-gender', 'plural', 'freetype'],
  },
  {
    id: 'de-grammar-gender-plural-freetype-003',
    type: 'free-type',
    topic: 'noun gender',
    subtopic: 'gender-and-plural',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Type the correct article only.',
    context: '___ Mädchen; plural: Mädchen',
    answers: ['das'],
    explanation: 'Mädchen is neuter: das Mädchen.',
    tags: ['noun-gender', 'plural', 'freetype'],
  },
  {
    id: 'de-grammar-gender-plural-multiselect-001',
    type: 'multiselect',
    topic: 'noun gender',
    subtopic: 'gender-and-plural',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Select the nouns whose plural form stays the same in these examples.',
    options: ['Lehrer', 'Mädchen', 'Buch', 'Museum', 'Fenster', 'Nation'],
    answers: [0, 1, 4],
    explanation: 'In these examples, Lehrer, Mädchen, and Fenster keep the same base plural form.',
    tags: ['noun-gender', 'plural', 'multiselect'],
  },
]

export default exercises
