import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-grammar-um-zu-damit-selection-001',
    type: 'selection',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Choose the correct connector.',
    context: 'Ich lerne jeden Abend, ___ die B1-Prufung zu bestehen.',
    options: ['um', 'damit', 'ohne', 'statt'],
    answer: 0,
    explanation: 'Use "um ... zu" when the subject is the same in both parts of the sentence.',
    grammarNote: '"um ... zu" expresses purpose with the same subject. "damit" is used with a finite clause, often when the subject changes.',
    tags: ['um-zu', 'purpose', 'same-subject'],
  },
  {
    id: 'de-grammar-um-zu-damit-selection-002',
    type: 'selection',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Choose the correct connector.',
    context: 'Ich spreche langsam, ___ du alles verstehst.',
    options: ['um', 'zu', 'damit', 'ohne'],
    answer: 2,
    explanation: 'Use "damit" because the subjects are different: ich spreche, du verstehst.',
    tags: ['damit', 'purpose', 'different-subject'],
  },
  {
    id: 'de-grammar-um-zu-damit-selection-003',
    type: 'selection',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 2,
    prompt: 'Choose the best phrase.',
    context: 'Er spart Geld, ___ ein neues Fahrrad zu kaufen.',
    options: ['damit', 'um', 'zu', 'weil'],
    answer: 1,
    explanation: 'The same person saves money and buys the bike, so use "um ... zu kaufen".',
    tags: ['um-zu', 'same-subject'],
  },
  {
    id: 'de-grammar-um-zu-damit-selection-004',
    type: 'selection',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Choose the correct connector.',
    context: 'Die Lehrerin wiederholt die Regel, ___ die Schuler sie besser verstehen.',
    options: ['um', 'damit', 'zu', 'statt'],
    answer: 1,
    explanation: 'Use "damit" because the teacher and the students are not the same subject.',
    tags: ['damit', 'different-subject'],
  },
  {
    id: 'de-grammar-um-zu-damit-selection-005',
    type: 'selection',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Pick the grammatically correct sentence.',
    options: [
      'Ich rufe an, damit dich zu informieren.',
      'Ich rufe an, um dich zu informieren.',
      'Ich rufe an, um du zu informieren.',
      'Ich rufe an, damit ich dich zu informieren.'
    ],
    answer: 1,
    explanation: 'Only "um dich zu informieren" is grammatically correct here.',
    tags: ['um-zu', 'sentence-choice'],
  },
  {
    id: 'de-grammar-um-zu-damit-selection-006',
    type: 'selection',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Pick the grammatically correct sentence.',
    options: [
      'Wir machen das Fenster zu, damit das Baby nicht friert.',
      'Wir machen das Fenster zu, um das Baby friert nicht.',
      'Wir machen das Fenster zu, damit nicht frieren das Baby.',
      'Wir machen das Fenster zu, um das Baby nicht friert.'
    ],
    answer: 0,
    explanation: 'Use "damit" with a finite clause because the baby is the one who might feel cold.',
    tags: ['damit', 'sentence-choice'],
  },
  {
    id: 'de-grammar-um-zu-damit-selection-007',
    type: 'selection',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Choose the correct connector.',
    context: 'Sie geht fruh ins Bett, ___ morgen fit zu sein.',
    options: ['damit', 'um', 'weil', 'ob'],
    answer: 1,
    explanation: 'The same subject goes to bed and wants to be fit, so use "um ... zu sein".',
    tags: ['um-zu', 'purpose'],
  },
  {
    id: 'de-grammar-um-zu-damit-selection-008',
    type: 'selection',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Choose the correct connector.',
    context: 'Ich schreibe alles auf, ___ ihr nichts vergesst.',
    options: ['um', 'zu', 'damit', 'statt'],
    answer: 2,
    explanation: 'Use "damit" because the subject changes from ich to ihr.',
    tags: ['damit', 'purpose'],
  },
  {
    id: 'de-grammar-um-zu-damit-freetype-001',
    type: 'free-type',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Complete with one word.',
    context: 'Ich gehe in die Bibliothek, ___ in Ruhe zu lernen.',
    answers: ['um'],
    explanation: 'Use "um" with "zu lernen" because the subject is the same.',
    tags: ['um-zu', 'purpose'],
  },
  {
    id: 'de-grammar-um-zu-damit-freetype-002',
    type: 'free-type',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Complete with one word.',
    context: 'Ich erklare den Plan noch einmal, ___ alle ihn verstehen.',
    answers: ['damit'],
    explanation: 'Use "damit" because the subject changes from ich to alle.',
    tags: ['damit', 'different-subject'],
  },
  {
    id: 'de-grammar-um-zu-damit-freetype-003',
    type: 'free-type',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Complete with one word.',
    context: 'Er nimmt den Bus, ___ nicht zu spat zu kommen.',
    answers: ['um'],
    explanation: 'The same person takes the bus and wants not to be late, so use "um".',
    tags: ['um-zu', 'purpose'],
  },
  {
    id: 'de-grammar-um-zu-damit-freetype-004',
    type: 'free-type',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Complete with one word.',
    context: 'Wir kaufen Obst, ___ die Kinder mehr Vitamine bekommen.',
    answers: ['damit'],
    explanation: 'Use "damit" because the children receive the vitamins, not the speakers.',
    tags: ['damit', 'different-subject'],
  },
  {
    id: 'de-grammar-um-zu-damit-multiselect-001',
    type: 'multiselect',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Select all sentences that correctly use "um ... zu".',
    options: [
      'Ich bleibe zu Hause, um zu arbeiten.',
      'Sie liest laut, um die Kinder schlafen.',
      'Er spart lange, um ein Auto zu kaufen.',
      'Wir rufen an, um ihr Bescheid zu sagen.'
    ],
    answers: [0, 2, 3],
    explanation: 'Correct "um ... zu" sentences keep the same subject and use a proper infinitive clause.',
    tags: ['um-zu', 'recognition'],
  },
  {
    id: 'de-grammar-um-zu-damit-multiselect-002',
    type: 'multiselect',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Select all sentences where "damit" is appropriate.',
    options: [
      'Ich gebe dir meinen Text, damit du ihn korrigierst.',
      'Sie geht einkaufen, damit Brot zu kaufen.',
      'Wir machen das Licht an, damit ihr besser seht.',
      'Er trainiert viel, damit fitter zu werden.'
    ],
    answers: [0, 2],
    explanation: '"damit" is used with a full clause, especially when the subject changes.',
    tags: ['damit', 'recognition'],
  },
  {
    id: 'de-grammar-um-zu-damit-multiselect-003',
    type: 'multiselect',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 5,
    prompt: 'Select all correct completions for this grammar rule.',
    context: '"um ... zu" is normally used when...',
    options: [
      'the subject in both clauses is the same.',
      'the clause has a finite verb after "damit".',
      'you want to express purpose.',
      'the subject changes from one clause to another.'
    ],
    answers: [0, 2],
    explanation: '"um ... zu" expresses purpose and usually requires the same subject in both clauses.',
    tags: ['rule', 'um-zu'],
  },
  {
    id: 'de-grammar-um-zu-damit-selection-009',
    type: 'selection',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Choose the better transformation.',
    context: 'Ich schicke dir die Adresse. Du findest den Ort leichter.',
    options: [
      'Ich schicke dir die Adresse, um den Ort leichter zu finden.',
      'Ich schicke dir die Adresse, damit du den Ort leichter findest.',
      'Ich schicke dir die Adresse, um du den Ort leichter findest.',
      'Ich schicke dir die Adresse, damit den Ort leichter zu finden.'
    ],
    answer: 1,
    explanation: 'Because the second clause has the subject "du", use "damit du ... findest".',
    tags: ['transformation', 'damit'],
  },
  {
    id: 'de-grammar-um-zu-damit-selection-010',
    type: 'selection',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 4,
    prompt: 'Choose the better transformation.',
    context: 'Sie kauft einen Wecker. Sie will fruher aufstehen.',
    options: [
      'Sie kauft einen Wecker, damit sie fruher aufsteht.',
      'Sie kauft einen Wecker, um fruher aufzustehen.',
      'Sie kauft einen Wecker, damit fruher aufzustehen.',
      'Sie kauft einen Wecker, um sie fruher aufsteht.'
    ],
    answer: 1,
    explanation: 'Both clauses have the same subject, so "um ... aufzustehen" is the better structure here.',
    tags: ['transformation', 'um-zu'],
  },
  {
    id: 'de-grammar-um-zu-damit-selection-011',
    type: 'selection',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 5,
    prompt: 'Choose the sentence with the correct punctuation and structure.',
    options: [
      'Ich nehme meinen Laptop mit um im Zug zu arbeiten.',
      'Ich nehme meinen Laptop mit, um im Zug zu arbeiten.',
      'Ich nehme, meinen Laptop mit um im Zug zu arbeiten.',
      'Ich nehme meinen Laptop, mit um im Zug zu arbeiten.'
    ],
    answer: 1,
    explanation: 'Infinitive clauses with "um ... zu" are separated by a comma.',
    tags: ['punctuation', 'um-zu'],
  },
  {
    id: 'de-grammar-um-zu-damit-selection-012',
    type: 'selection',
    topic: 'infinitive clauses',
    subtopic: 'um-zu-damit',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 5,
    prompt: 'Choose the correct completion.',
    context: 'Wir schicken die Datei sofort, ___ ihr heute noch anfangen konnt.',
    options: ['um', 'zu', 'damit', 'obwohl'],
    answer: 2,
    explanation: 'Use "damit" because "ihr" is a different subject and the clause has a finite verb.',
    tags: ['damit', 'purpose'],
  },
]

export default exercises
