import type { Exercise } from '../types/exercise'

// Futur I — future tense or assumption about the present
// Formula: werden (Präsens) + Infinitiv (at the end of the clause)
// Also used for assumptions: "Er wird müde sein." (He is probably tired.)

const exercises: Exercise[] = [
  {
    id: 'de-grammar-futur1-formula-001',
    type: 'selection',
    topic: 'Futur I',
    subtopic: 'formation',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 1,
    prompt: 'What is the formula for Futur I?',
    options: [
      'werden (Präsens) + Infinitiv',
      'werden (Präteritum) + Partizip II',
      'sein (Präsens) + Infinitiv',
      'haben (Präsens) + Infinitiv',
    ],
    answer: 0,
    explanation: 'Futur I = conjugated "werden" + Infinitiv at the end. "Ich werde arbeiten."',
    grammarNote: 'ich werde / du wirst / er wird / wir werden / ihr werdet / sie werden + Infinitiv',
    tags: ['futur1', 'formation', 'werden'],
  },
  {
    id: 'de-grammar-futur1-conjugation-du-001',
    type: 'selection',
    topic: 'Futur I',
    subtopic: 'werden conjugation',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct Futur I form: "___ morgen einkaufen gehen." (du)',
    options: ['Du wirst morgen einkaufen gehen.', 'Du werde morgen einkaufen gehen.', 'Du wird morgen einkaufen gehen.', 'Du werdest morgen einkaufen gehen.'],
    answer: 0,
    explanation: '"werden" for "du" = "wirst". "Du wirst morgen einkaufen gehen."',
    tags: ['futur1', 'werden', 'conjugation'],
  },
  {
    id: 'de-grammar-futur1-fill-arbeiten-001',
    type: 'free-type',
    topic: 'Futur I',
    subtopic: 'formation',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete the Futur I sentence for "ich": "Ich ___ morgen ___." (arbeiten)',
    answers: ['werde arbeiten'],
    caseSensitive: false,
    hint: 'ich + werden → werde. Infinitiv at the end.',
    explanation: '"Ich werde morgen arbeiten." — "werde" (1st pers. sg. of werden) + Infinitiv "arbeiten".',
    tags: ['futur1', 'formation'],
  },
  {
    id: 'de-grammar-futur1-assumption-001',
    type: 'selection',
    topic: 'Futur I',
    subtopic: 'expressing assumption',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'The sentence "Er wird müde sein." expresses…',
    options: [
      'An assumption about the present (He is probably tired.)',
      'A command (He must be tired.)',
      'A past event (He was tired.)',
      'A wish (I hope he is tired.)',
    ],
    answer: 0,
    explanation: 'Futur I with "sein/haben/werden" often expresses a present assumption. "Er wird müde sein" = "He is probably tired."',
    tags: ['futur1', 'assumption', 'usage'],
  },
  {
    id: 'de-grammar-futur1-word-order-001',
    type: 'selection',
    topic: 'Futur I',
    subtopic: 'word order',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Where does the Infinitiv go in a Futur I main clause?',
    options: [
      'At the end of the clause',
      'Right after "werden"',
      'At the beginning',
      'Before "werden"',
    ],
    answer: 0,
    explanation: 'The Infinitiv always goes to the end in a main clause: "Ich werde ein Buch kaufen." (kaufen = end)',
    tags: ['futur1', 'word-order'],
  },
  {
    id: 'de-grammar-futur1-fill-kommen-001',
    type: 'free-type',
    topic: 'Futur I',
    subtopic: 'formation',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Write the Futur I of "kommen" for "er": "Er ___ bald ___."',
    answers: ['wird kommen'],
    caseSensitive: false,
    explanation: '"er" → "wird". "Er wird bald kommen."',
    tags: ['futur1', 'kommen'],
  },
  {
    id: 'de-grammar-futur1-sentence-order-001',
    type: 'multiselect',
    topic: 'Futur I',
    subtopic: 'correct sentences',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Which sentences are grammatically correct Futur I? (Select all that apply)',
    options: [
      'Wir werden das Projekt abschließen.',
      'Sie wird ein neues Auto kaufen.',
      'Ich werde gestern laufen.',
      'Du wirst bald ankommen.',
    ],
    answers: [0, 1, 3],
    explanation: 'All are correct except option 2: "gestern" (yesterday) is past, not compatible with Futur I.',
    tags: ['futur1', 'correct-sentences'],
  },
  {
    id: 'de-grammar-futur1-werden-paradigm-001',
    type: 'selection',
    topic: 'Futur I',
    subtopic: 'werden conjugation',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'What is "werden" for "ihr"?',
    options: ['werdet', 'werden', 'wirst', 'wird'],
    answer: 0,
    explanation: 'Full paradigm: ich werde, du wirst, er/sie/es wird, wir werden, ihr werdet, sie/Sie werden.',
    tags: ['futur1', 'werden', 'conjugation'],
  },
]

export default exercises
