import type { Exercise } from '../types/exercise'

// Perfekt (Present Perfect) — the most common past tense in spoken German
// Formula: haben/sein (Präsens) + Partizip II
// haben: most transitive verbs
// sein: verbs of movement/change of state (gehen, kommen, fahren, werden, bleiben, sein…)

const exercises: Exercise[] = [
  {
    id: 'de-grammar-perfekt-haben-machen-001',
    type: 'selection',
    topic: 'Perfekt',
    subtopic: 'haben + Partizip II',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Which auxiliary verb goes with "machen" in Perfekt?',
    options: ['haben', 'sein', 'werden', 'können'],
    answer: 0,
    explanation: '"machen" is transitive → uses "haben". "Ich habe die Arbeit gemacht."',
    grammarNote: 'haben: most verbs | sein: movement/change of state (gehen, kommen, fahren, werden, bleiben…)',
    tags: ['perfekt', 'haben', 'auxiliary'],
  },
  {
    id: 'de-grammar-perfekt-sein-gehen-001',
    type: 'selection',
    topic: 'Perfekt',
    subtopic: 'sein + Partizip II',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Which auxiliary verb goes with "gehen" in Perfekt?',
    options: ['sein', 'haben', 'werden', 'lassen'],
    answer: 0,
    explanation: '"gehen" is a verb of movement → uses "sein". "Ich bin in die Schule gegangen."',
    tags: ['perfekt', 'sein', 'auxiliary', 'bewegungsverben'],
  },
  {
    id: 'de-grammar-perfekt-partizip2-weak-001',
    type: 'selection',
    topic: 'Perfekt',
    subtopic: 'Partizip II formation',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'What is the Partizip II of "kaufen"?',
    options: ['gekauft', 'kaufte', 'kaufen', 'gekaufen'],
    answer: 0,
    explanation: 'Weak verbs: ge- + stem + -t. "kaufen" → ge + kauf + t = "gekauft".',
    grammarNote: 'Weak Partizip II: ge- + stem + -t | Strong: ge- + changed stem + -en',
    tags: ['perfekt', 'partizip2', 'weak-verbs'],
  },
  {
    id: 'de-grammar-perfekt-partizip2-strong-001',
    type: 'selection',
    topic: 'Perfekt',
    subtopic: 'Partizip II formation',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'What is the Partizip II of "schreiben"?',
    options: ['geschrieben', 'geschreibt', 'schrieben', 'gegeschrieben'],
    answer: 0,
    explanation: '"schreiben" is a strong verb: ge- + changed stem "schrieb" + -en = "geschrieben".',
    tags: ['perfekt', 'partizip2', 'strong-verbs'],
  },
  {
    id: 'de-grammar-perfekt-sein-bleiben-001',
    type: 'free-type',
    topic: 'Perfekt',
    subtopic: 'sein + Partizip II',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Complete the Perfekt sentence: "Er ___ zu Hause ___ ." (bleiben)',
    answers: ['ist geblieben'],
    caseSensitive: false,
    hint: 'bleiben = change of state/location → sein. Partizip II: geblieben.',
    explanation: '"bleiben" uses "sein". Partizip II: "geblieben". → "Er ist zu Hause geblieben."',
    tags: ['perfekt', 'sein', 'bleiben'],
  },
  {
    id: 'de-grammar-perfekt-haben-essen-001',
    type: 'free-type',
    topic: 'Perfekt',
    subtopic: 'haben + Partizip II',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Write the Perfekt of "essen" for "wir": "Wir ___ Pizza ___."',
    answers: ['haben gegessen'],
    caseSensitive: false,
    hint: 'essen → haben (transitive). Partizip II: gegessen.',
    explanation: '"essen" uses "haben". Partizip II: "gegessen". → "Wir haben Pizza gegessen."',
    tags: ['perfekt', 'haben', 'essen'],
  },
  {
    id: 'de-grammar-perfekt-inseparable-001',
    type: 'selection',
    topic: 'Perfekt',
    subtopic: 'Partizip II — inseparable prefix verbs',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'What is the Partizip II of "verstehen" (inseparable prefix verb)?',
    options: ['verstanden', 'geverstanden', 'versteht', 'gestanden'],
    answer: 0,
    explanation: 'Inseparable prefix verbs (be-, ge-, er-, ver-, zer-, ent-, emp-, miss-) do NOT add "ge-". "verstehen" → "verstanden".',
    grammarNote: 'Inseparable prefixes (ver-, be-, er-, ent-…): no "ge-" in Partizip II',
    tags: ['perfekt', 'partizip2', 'inseparable-verbs'],
  },
  {
    id: 'de-grammar-perfekt-sein-fahren-001',
    type: 'selection',
    topic: 'Perfekt',
    subtopic: 'sein + Partizip II',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Complete: "Wir ___ nach Berlin gefahren."',
    options: ['sind', 'haben', 'werden', 'waren'],
    answer: 0,
    explanation: '"fahren" (movement) uses "sein". "Wir sind nach Berlin gefahren."',
    tags: ['perfekt', 'sein', 'fahren'],
  },
  {
    id: 'de-grammar-perfekt-multiselect-sein-001',
    type: 'multiselect',
    topic: 'Perfekt',
    subtopic: 'haben vs sein',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Which verbs use "sein" in Perfekt? (Select all that apply)',
    options: ['gehen', 'essen', 'kommen', 'trinken', 'werden', 'schlafen'],
    answers: [0, 2, 4],
    explanation: '"gehen", "kommen", and "werden" are movement/change-of-state verbs → use "sein". "essen", "trinken", and "schlafen" use "haben".',
    tags: ['perfekt', 'haben-vs-sein'],
  },
]

export default exercises
