import type { Exercise } from '../types/exercise'

// Präteritum (Simple Past) — mostly used in written German: books, news, formal text
// Weak verbs: stem + -te + personal ending
// Strong verbs: vowel change, no -te suffix

const exercises: Exercise[] = [
  {
    id: 'de-grammar-prateritum-weak-ich-001',
    type: 'selection',
    topic: 'Präteritum',
    subtopic: 'weak verbs',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct Präteritum form of "lernen" for "ich".',
    options: ['lernte', 'lernete', 'lernte ich', 'gelernt'],
    answer: 0,
    explanation: 'Weak verbs: stem + -te. "lernen" → stem "lern" + "-te" = "lernte". In 1st and 3rd person singular there is no additional ending.',
    tags: ['prateritum', 'weak-verbs', 'conjugation'],
  },
  {
    id: 'de-grammar-prateritum-weak-er-001',
    type: 'selection',
    topic: 'Präteritum',
    subtopic: 'weak verbs',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct Präteritum form of "wohnen" for "er".',
    options: ['wohnte', 'wohnete', 'wohnt', 'hat gewohnt'],
    answer: 0,
    explanation: '"wohnen" → stem "wohn" + "-te" = "wohnte". 3rd person singular = same as 1st person (no extra ending).',
    tags: ['prateritum', 'weak-verbs', 'conjugation'],
  },
  {
    id: 'de-grammar-prateritum-weak-wir-001',
    type: 'free-type',
    topic: 'Präteritum',
    subtopic: 'weak verbs',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Write the Präteritum form of "spielen" for "wir".',
    answers: ['spielten'],
    caseSensitive: false,
    hint: 'Weak verb: stem + -te + -n for wir/sie/Sie',
    explanation: '"spielen" → stem "spiel" + "-te" + "-n" (wir-ending) = "spielten". "Wir spielten Fußball."',
    tags: ['prateritum', 'weak-verbs', 'conjugation'],
  },
  {
    id: 'de-grammar-prateritum-strong-sein-001',
    type: 'selection',
    topic: 'Präteritum',
    subtopic: 'strong verbs',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'What is the Präteritum of "sein" (to be) for "ich"?',
    options: ['war', 'wurde', 'bin', 'sei'],
    answer: 0,
    explanation: '"sein" is irregular. Präteritum: ich war, du warst, er/sie/es war, wir waren, ihr wart, sie/Sie waren.',
    grammarNote: 'sein → war (Präteritum) | haben → hatte | werden → wurde',
    tags: ['prateritum', 'strong-verbs', 'irregular', 'sein'],
  },
  {
    id: 'de-grammar-prateritum-strong-haben-001',
    type: 'selection',
    topic: 'Präteritum',
    subtopic: 'strong verbs',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'What is the Präteritum of "haben" for "er/sie/es"?',
    options: ['hatte', 'hat', 'hatte gehabt', 'war'],
    answer: 0,
    explanation: '"haben" → Präteritum: ich hatte, du hattest, er/sie/es hatte, wir hatten, ihr hattet, sie hatten.',
    tags: ['prateritum', 'strong-verbs', 'haben'],
  },
  {
    id: 'de-grammar-prateritum-strong-gehen-001',
    type: 'free-type',
    topic: 'Präteritum',
    subtopic: 'strong verbs',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Write the Präteritum form of "gehen" for "sie (they)".',
    answers: ['gingen'],
    caseSensitive: false,
    hint: 'gehen → ging (vowel change). Plural "sie": add -en.',
    explanation: '"gehen" is a strong verb: ging. Plural: sie gingen. "Sie gingen in die Schule."',
    tags: ['prateritum', 'strong-verbs', 'gehen'],
  },
  {
    id: 'de-grammar-prateritum-strong-kommen-001',
    type: 'selection',
    topic: 'Präteritum',
    subtopic: 'strong verbs',
    language: 'de',
    group: 'grammar',
    level: 'B1',
    difficulty: 3,
    prompt: 'Which is the correct Präteritum of "kommen" for "du"?',
    options: ['kamst', 'kommtest', 'kamest', 'kam'],
    answer: 0,
    explanation: '"kommen" → Präteritum stem "kam". Du: kamst. (kam + -st)',
    tags: ['prateritum', 'strong-verbs', 'kommen'],
  },
  {
    id: 'de-grammar-prateritum-usage-001',
    type: 'multiselect',
    topic: 'Präteritum',
    subtopic: 'usage',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'In which situations is Präteritum typically used? (Select all that apply)',
    options: [
      'In written texts: books, articles, newspapers',
      'In everyday spoken conversation',
      'For "sein", "haben", "werden" and modal verbs in speech',
      'To describe past events in formal written German',
    ],
    answers: [0, 2, 3],
    explanation: 'Präteritum is mainly written past tense. In speech, Germans use Perfekt for most verbs, but "war" (sein), "hatte" (haben), and modal verbs like "konnte" are commonly used in speech too.',
    tags: ['prateritum', 'usage'],
  },
  {
    id: 'de-grammar-prateritum-weak-paradigm-001',
    type: 'selection',
    topic: 'Präteritum',
    subtopic: 'weak verbs',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Which suffix is added to a weak verb stem to form Präteritum?',
    options: ['-te', '-et', '-t', '-ge'],
    answer: 0,
    explanation: 'Weak verbs add "-te" to the stem: machen → machte, kaufen → kaufte, lernen → lernte.',
    grammarNote: 'Weak (schwach): stem + -te + ending | Strong (stark): vowel change, no -te',
    tags: ['prateritum', 'weak-verbs', 'rule'],
  },
  {
    id: 'de-grammar-prateritum-fill-001',
    type: 'free-type',
    topic: 'Präteritum',
    subtopic: 'weak verbs',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Fill in the blank with the Präteritum of "kaufen" (ich).',
    context: 'Ich ___ gestern ein Buch.',
    answers: ['kaufte'],
    caseSensitive: false,
    explanation: '"kaufen" → stem "kauf" + "-te" = "kaufte". "Ich kaufte gestern ein Buch."',
    tags: ['prateritum', 'weak-verbs'],
  },
]

export default exercises
