import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-phonetics-alphabet-selection-001',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'A a',
    options: ['[a:]', '[e:]', '[be:]', '[ha:]'],
    answer: 0,
    explanation: 'The German letter name for A is pronounced [a:].',
    tags: ['alphabet', 'transcription', 'a'],
  },
  {
    id: 'de-phonetics-alphabet-selection-002',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'B b',
    options: ['[pe:]', '[be:]', '[ve:]', '[de:]'],
    answer: 1,
    explanation: 'The German letter name for B is [be:].',
    tags: ['alphabet', 'transcription', 'b'],
  },
  {
    id: 'de-phonetics-alphabet-selection-003',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'C c',
    options: ['[tse:]', '[ze:]', '[se:]', '[ka:]'],
    answer: 0,
    explanation: 'The German letter name for C is [tse:].',
    tags: ['alphabet', 'transcription', 'c'],
  },
  {
    id: 'de-phonetics-alphabet-selection-004',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'D d',
    options: ['[de:]', '[te:]', '[ge:]', '[be:]'],
    answer: 0,
    explanation: 'The German letter name for D is [de:].',
    tags: ['alphabet', 'transcription', 'd'],
  },
  {
    id: 'de-phonetics-alphabet-selection-005',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'E e',
    options: ['[a:]', '[e:]', '[i:]', '[o:]'],
    answer: 1,
    explanation: 'The German letter name for E is [e:].',
    tags: ['alphabet', 'transcription', 'e'],
  },
  {
    id: 'de-phonetics-alphabet-selection-006',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'F f',
    options: ['[ef]', '[elf]', '[fe:]', '[ve:]'],
    answer: 0,
    explanation: 'The German letter name for F is [ef].',
    tags: ['alphabet', 'transcription', 'f'],
  },
  {
    id: 'de-phonetics-alphabet-selection-007',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'G g',
    options: ['[ka:]', '[ge:]', '[je:]', '[ze:]'],
    answer: 1,
    explanation: 'The German letter name for G is [ge:].',
    tags: ['alphabet', 'transcription', 'g'],
  },
  {
    id: 'de-phonetics-alphabet-selection-008',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'H h',
    options: ['[ha:]', '[a:tʃ]', '[e:tʃ]', '[ka:]'],
    answer: 0,
    explanation: 'The German letter name for H is [ha:].',
    tags: ['alphabet', 'transcription', 'h'],
  },
  {
    id: 'de-phonetics-alphabet-selection-009',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'I i',
    options: ['[i:]', '[e:]', '[u:]', '[y:]'],
    answer: 0,
    explanation: 'The German letter name for I is [i:].',
    tags: ['alphabet', 'transcription', 'i'],
  },
  {
    id: 'de-phonetics-alphabet-selection-010',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'J j',
    options: ['[jot]', '[ʒot]', '[i:]', '[je:]'],
    answer: 0,
    explanation: 'The German letter name for J is [jot].',
    tags: ['alphabet', 'transcription', 'j'],
  },
  {
    id: 'de-phonetics-alphabet-selection-011',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'K k',
    options: ['[ka:]', '[ke:]', '[ge:]', '[tse:]'],
    answer: 0,
    explanation: 'The German letter name for K is [ka:].',
    tags: ['alphabet', 'transcription', 'k'],
  },
  {
    id: 'de-phonetics-alphabet-selection-012',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'L l',
    options: ['[el]', '[em]', '[en]', '[ef]'],
    answer: 0,
    explanation: 'The German letter name for L is [el].',
    tags: ['alphabet', 'transcription', 'l'],
  },
  {
    id: 'de-phonetics-alphabet-selection-013',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'M m',
    options: ['[el]', '[em]', '[en]', '[er]'],
    answer: 1,
    explanation: 'The German letter name for M is [em].',
    tags: ['alphabet', 'transcription', 'm'],
  },
  {
    id: 'de-phonetics-alphabet-selection-014',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'N n',
    options: ['[em]', '[en]', '[el]', '[e:n]'],
    answer: 1,
    explanation: 'The German letter name for N is [en].',
    tags: ['alphabet', 'transcription', 'n'],
  },
  {
    id: 'de-phonetics-alphabet-selection-015',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'O o',
    options: ['[u:]', '[o:]', '[ø:]', '[ɔ]'],
    answer: 1,
    explanation: 'The German letter name for O is [o:].',
    tags: ['alphabet', 'transcription', 'o'],
  },
  {
    id: 'de-phonetics-alphabet-selection-016',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'P p',
    options: ['[be:]', '[pe:]', '[te:]', '[ef]'],
    answer: 1,
    explanation: 'The German letter name for P is [pe:].',
    tags: ['alphabet', 'transcription', 'p'],
  },
  {
    id: 'de-phonetics-alphabet-selection-017',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'Q q',
    options: ['[ku:]', '[ka:]', '[kve:]', '[tse:]'],
    answer: 0,
    explanation: 'The German letter name for Q is [ku:].',
    tags: ['alphabet', 'transcription', 'q'],
  },
  {
    id: 'de-phonetics-alphabet-selection-018',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'R r',
    options: ['[ar]', '[er]', '[ɛr]', '[or]'],
    answer: 1,
    explanation: 'The German letter name for R is usually represented here as [er].',
    tags: ['alphabet', 'transcription', 'r'],
  },
  {
    id: 'de-phonetics-alphabet-selection-019',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'S s',
    options: ['[es]', '[ze:]', '[ef]', '[tse:]'],
    answer: 0,
    explanation: 'The German letter name for S is [es].',
    tags: ['alphabet', 'transcription', 's'],
  },
  {
    id: 'de-phonetics-alphabet-selection-020',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'T t',
    options: ['[de:]', '[te:]', '[tse:]', '[ti:]'],
    answer: 1,
    explanation: 'The German letter name for T is [te:].',
    tags: ['alphabet', 'transcription', 't'],
  },
  {
    id: 'de-phonetics-alphabet-selection-021',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'U u',
    options: ['[u:]', '[y:]', '[o:]', '[ju:]'],
    answer: 0,
    explanation: 'The German letter name for U is [u:].',
    tags: ['alphabet', 'transcription', 'u'],
  },
  {
    id: 'de-phonetics-alphabet-selection-022',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'V v',
    options: ['[ve:]', '[faʊ]', '[fe:]', '[vau]'],
    answer: 1,
    explanation: 'The German letter name for V is [faʊ].',
    tags: ['alphabet', 'transcription', 'v'],
  },
  {
    id: 'de-phonetics-alphabet-selection-023',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'W w',
    options: ['[faʊ]', '[ve:]', '[we:]', '[vɛ]'],
    answer: 1,
    explanation: 'The German letter name for W is [ve:].',
    tags: ['alphabet', 'transcription', 'w'],
  },
  {
    id: 'de-phonetics-alphabet-selection-024',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'X x',
    options: ['[iks]', '[ɛks]', '[ix]', '[ka-es]'],
    answer: 0,
    explanation: 'The German letter name for X is [iks].',
    tags: ['alphabet', 'transcription', 'x'],
  },
  {
    id: 'de-phonetics-alphabet-selection-025',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'Y y',
    options: ['[y:]', '[ʏpsilɔn]', '[i:]', '[igrek]'],
    answer: 1,
    explanation: 'The German letter name for Y is [ʏpsilɔn].',
    tags: ['alphabet', 'transcription', 'y'],
  },
  {
    id: 'de-phonetics-alphabet-selection-026',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'Z z',
    options: ['[ze:]', '[tset]', '[tse:t]', '[set]'],
    answer: 1,
    explanation: 'The German letter name for Z is [tset].',
    tags: ['alphabet', 'transcription', 'z'],
  },
  {
    id: 'de-phonetics-alphabet-selection-027',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'Ä ä',
    options: ['[ɛ:]', '[e:]', '[a:]', '[æ]'],
    answer: 0,
    explanation: 'The German letter name for Ä is [ɛ:].',
    tags: ['alphabet', 'transcription', 'a-umlaut'],
  },
  {
    id: 'de-phonetics-alphabet-selection-028',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'Ö ö',
    options: ['[o:]', '[ø:]', '[œ]', '[u:]'],
    answer: 1,
    explanation: 'The German letter name for Ö is [ø:].',
    tags: ['alphabet', 'transcription', 'o-umlaut'],
  },
  {
    id: 'de-phonetics-alphabet-selection-029',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'Ü ü',
    options: ['[u:]', '[y:]', '[ju:]', '[ø:]'],
    answer: 1,
    explanation: 'The German letter name for Ü is [y:].',
    tags: ['alphabet', 'transcription', 'u-umlaut'],
  },
  {
    id: 'de-phonetics-alphabet-selection-030',
    type: 'selection',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct transcription for the German letter name.',
    context: 'ß',
    options: ['[ɛsˈtset]', '[es]', '[ʃarfes-s]', '[set]'],
    answer: 0,
    explanation: 'The letter ß is called [ɛsˈtset] in German.',
    tags: ['alphabet', 'transcription', 'eszett'],
  },
  {
    id: 'de-phonetics-alphabet-multiselect-001',
    type: 'multiselect',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select all letters whose names end with a long vowel [e:].',
    options: ['B', 'C', 'D', 'W'],
    answers: [0, 2, 3],
    explanation: 'B = [be:], D = [de:], W = [ve:]. C is [tse:].',
    tags: ['alphabet', 'pattern-recognition'],
  },
  {
    id: 'de-phonetics-alphabet-multiselect-002',
    type: 'multiselect',
    topic: 'alphabet',
    subtopic: 'letter-transcription',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select all umlaut letters.',
    options: ['Ä', 'Ö', 'Ü', 'Y'],
    answers: [0, 1, 2],
    explanation: 'Ä, Ö, and Ü are the German umlaut letters. Y is not an umlaut.',
    tags: ['alphabet', 'umlaut'],
  },
]

export default exercises
