import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-vocab-food-apple-001',
    type: 'selection',
    topic: 'vocabulary',
    subtopic: 'food',
    language: 'de',
    difficulty: 1,
    prompt: 'What does "der Apfel" mean in English?',
    options: ['orange', 'apple', 'pear', 'banana'],
    answer: 1,
    explanation: '"Apfel" means apple. It is masculine (der Apfel).',
    tags: ['food', 'fruit', 'translation'],
  },
  {
    id: 'de-vocab-food-bread-001',
    type: 'free-type',
    topic: 'vocabulary',
    subtopic: 'food',
    language: 'de',
    difficulty: 2,
    prompt: 'How do you say "bread" in German?',
    answers: ['Brot', 'brot'],
    caseSensitive: false,
    explanation: '"Bread" in German is "Brot" (das Brot — neuter).',
    tags: ['food', 'nouns', 'translation'],
  },
  {
    id: 'de-vocab-food-water-001',
    type: 'selection',
    topic: 'vocabulary',
    subtopic: 'food',
    language: 'de',
    difficulty: 1,
    prompt: 'What does "das Wasser" mean?',
    options: ['wine', 'juice', 'water', 'milk'],
    answer: 2,
    explanation: '"Wasser" means water. It is neuter (das Wasser).',
    tags: ['food', 'drinks', 'translation'],
  },
  {
    id: 'de-vocab-food-milk-001',
    type: 'free-type',
    topic: 'vocabulary',
    subtopic: 'food',
    language: 'de',
    difficulty: 1,
    prompt: 'How do you say "milk" in German?',
    answers: ['Milch', 'milch'],
    caseSensitive: false,
    explanation: '"Milk" in German is "Milch" (die Milch — feminine).',
    tags: ['food', 'drinks', 'translation'],
  },
  {
    id: 'de-vocab-food-fruit-multiselect-001',
    type: 'multiselect',
    topic: 'vocabulary',
    subtopic: 'food',
    language: 'de',
    difficulty: 2,
    prompt: 'Which of these are fruits (Früchte) in German?',
    options: ['der Apfel', 'das Brot', 'die Banane', 'die Milch', 'die Orange'],
    answers: [0, 2, 4],
    explanation:
      '"der Apfel" (apple), "die Banane" (banana), and "die Orange" (orange) are fruits. "das Brot" is bread and "die Milch" is milk.',
    tags: ['food', 'fruit', 'vocabulary'],
  },
  {
    id: 'de-vocab-food-cheese-001',
    type: 'selection',
    topic: 'vocabulary',
    subtopic: 'food',
    language: 'de',
    difficulty: 2,
    prompt: 'Which German word means "cheese"?',
    options: ['das Fleisch', 'der Käse', 'das Ei', 'die Butter'],
    answer: 1,
    explanation: '"Käse" means cheese. It is masculine (der Käse).',
    tags: ['food', 'dairy', 'translation'],
  },
  {
    id: 'de-vocab-food-egg-001',
    type: 'free-type',
    topic: 'vocabulary',
    subtopic: 'food',
    language: 'de',
    difficulty: 2,
    prompt: 'How do you say "egg" in German?',
    answers: ['Ei', 'ei'],
    caseSensitive: false,
    hint: 'It is a neuter noun (das ___)',
    explanation: '"Egg" in German is "Ei" (das Ei — neuter). Plural: "Eier".',
    tags: ['food', 'nouns', 'translation'],
  },
]

export default exercises
