import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'de-writing-email-selection-001',
    type: 'selection',
    topic: 'email writing',
    subtopic: 'greetings-and-closings',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the better informal greeting.',
    context: 'You are writing to your friend Claudia.',
    options: ['Sehr geehrte Frau Claudia,', 'Liebe Claudia,', 'Mit freundlichen Gruessen,', 'Sehr geehrter Claudia,'],
    answer: 1,
    explanation: 'For an informal email to a friend, Liebe Claudia, is appropriate.',
    tags: ['email', 'greeting', 'informal', 'du'],
  },
  {
    id: 'de-writing-email-selection-002',
    type: 'selection',
    topic: 'email writing',
    subtopic: 'greetings-and-closings',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the better formal greeting.',
    context: 'You are writing to Mrs. Mueller in a formal context.',
    options: ['Hallo Frau Mueller,', 'Liebe Frau Mueller,', 'Sehr geehrte Frau Mueller,', 'Bis bald, Frau Mueller,'],
    answer: 2,
    explanation: 'Sehr geehrte Frau Mueller, is the standard formal greeting.',
    tags: ['email', 'greeting', 'formal', 'sie'],
  },
  {
    id: 'de-writing-email-selection-003',
    type: 'selection',
    topic: 'email writing',
    subtopic: 'greetings-and-closings',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the better informal closing.',
    context: 'End of an email to a friend.',
    options: ['Viele Gruesse', 'Mit freundlichen Gruessen', 'Sehr geehrte Damen und Herren', 'Ich moechte Sie einladen'],
    answer: 0,
    explanation: 'Viele Gruesse is a common informal closing.',
    tags: ['email', 'closing', 'informal', 'du'],
  },
  {
    id: 'de-writing-email-selection-004',
    type: 'selection',
    topic: 'email writing',
    subtopic: 'greetings-and-closings',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the better formal closing.',
    context: 'End of an email to a company or teacher.',
    options: ['Bis bald', 'Liebe Gruesse', 'Mit freundlichen Gruessen', 'Hallo zusammen'],
    answer: 2,
    explanation: 'Mit freundlichen Gruessen is the standard formal closing.',
    tags: ['email', 'closing', 'formal', 'sie'],
  },
  {
    id: 'de-writing-email-selection-005',
    type: 'selection',
    topic: 'email writing',
    subtopic: 'thanks-formulas',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct informal phrase.',
    context: 'You want to say: "I thank you" to a friend.',
    options: ['Ich bedanke mich bei Ihnen.', 'Ich bedanke mich bei dir.', 'Mit freundlichen Gruessen', 'Ich schreibe Ihnen, weil...'],
    answer: 1,
    explanation: 'Use dir in informal communication with du: Ich bedanke mich bei dir.',
    tags: ['email', 'thanks', 'informal', 'du'],
  },
  {
    id: 'de-writing-email-selection-006',
    type: 'selection',
    topic: 'email writing',
    subtopic: 'thanks-formulas',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct formal phrase.',
    context: 'You want to thank a customer or teacher politely.',
    options: ['Ich bedanke mich bei dir.', 'Ich bedanke mich bei Ihnen.', 'Liebe Claudia,', 'Bis bald'],
    answer: 1,
    explanation: 'Use Ihnen in formal communication with Sie: Ich bedanke mich bei Ihnen.',
    tags: ['email', 'thanks', 'formal', 'sie'],
  },
  {
    id: 'de-writing-email-selection-007',
    type: 'selection',
    topic: 'email writing',
    subtopic: 'thanks-formulas',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the most complete polite phrase.',
    context: 'You want to thank someone formally for their help.',
    options: [
      'Ich bedanke mich bei Ihnen.',
      'Ich bedanke mich bei dir.',
      'Ich bedanke mich bei Ihnen fuer Ihre Hilfe.',
      'Viele Gruesse',
    ],
    answer: 2,
    explanation: 'Ich bedanke mich bei Ihnen fuer Ihre Hilfe. is the most complete polite option here.',
    tags: ['email', 'thanks', 'formal', 'sie'],
  },
  {
    id: 'de-writing-email-selection-008',
    type: 'selection',
    topic: 'email writing',
    subtopic: 'opening-lines',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the more typical first sentence after a formal greeting.',
    context: 'After: Sehr geehrte Frau Mueller,',
    options: ['Wie geht es dir?', 'Ich schreibe Ihnen, weil ich einen Termin brauche.', 'Bis bald', 'Liebe Gruesse'],
    answer: 1,
    explanation: 'A formal email often continues with Ich schreibe Ihnen, weil... or a similar formal purpose sentence.',
    tags: ['email', 'opening-line', 'formal', 'sie'],
  },
  {
    id: 'de-writing-email-selection-009',
    type: 'selection',
    topic: 'email writing',
    subtopic: 'opening-lines',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the more typical first sentence after an informal greeting.',
    context: 'After: Hallo Claudia,',
    options: ['Sehr geehrte Damen und Herren,', 'Wie geht es dir?', 'Mit freundlichen Gruessen', 'Ich moechte Sie einladen.'],
    answer: 1,
    explanation: 'Wie geht es dir? fits an informal email with du.',
    tags: ['email', 'opening-line', 'informal', 'du'],
  },
  {
    id: 'de-writing-email-selection-010',
    type: 'selection',
    topic: 'email writing',
    subtopic: 'register-choice',
    language: 'de',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the line that matches formal register consistently.',
    context: 'You are writing to Mr. Schmidt.',
    options: [
      'Lieber Herr Schmidt, Wie geht es dir?',
      'Sehr geehrter Herr Schmidt, ich schreibe Ihnen wegen des Termins.',
      'Hallo Herr Schmidt, bis bald',
      'Liebe Gruesse, Oleg',
    ],
    answer: 1,
    explanation: 'Formal register needs Sehr geehrter... and Ihnen, not du-based phrasing.',
    tags: ['email', 'register', 'formal', 'sie'],
  },
  {
    id: 'de-writing-email-freetype-001',
    type: 'free-type',
    topic: 'email writing',
    subtopic: 'greetings-and-closings',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the missing informal closing.',
    context: '___,\nOleg',
    answers: ['Viele Gruesse', 'Liebe Gruesse', 'Bis bald'],
    explanation: 'Many informal closings are possible here; Viele Gruesse is the neutral standard option.',
    tags: ['email', 'closing', 'informal', 'freetype'],
  },
  {
    id: 'de-writing-email-freetype-002',
    type: 'free-type',
    topic: 'email writing',
    subtopic: 'greetings-and-closings',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Type the missing formal closing.',
    context: '___,\nOleg Ivanov',
    answers: ['Mit freundlichen Gruessen', 'Freundliche Gruesse'],
    explanation: 'Mit freundlichen Gruessen is the most standard formal closing.',
    tags: ['email', 'closing', 'formal', 'freetype'],
  },
  {
    id: 'de-writing-email-freetype-003',
    type: 'free-type',
    topic: 'email writing',
    subtopic: 'thanks-formulas',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Complete with one word.',
    context: 'Ich bedanke mich bei ___.',
    answers: ['dir', 'Ihnen'],
    explanation: 'Use dir for informal du and Ihnen for formal Sie, depending on context.',
    tags: ['email', 'thanks', 'pronouns', 'freetype'],
  },
  {
    id: 'de-writing-email-freetype-004',
    type: 'free-type',
    topic: 'email writing',
    subtopic: 'opening-lines',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Complete with one word.',
    context: 'Ich schreibe ___, weil ich einen Termin brauche.',
    answers: ['Ihnen'],
    explanation: 'In a formal email, the correct pronoun is Ihnen.',
    tags: ['email', 'opening-line', 'formal', 'freetype'],
  },
  {
    id: 'de-writing-email-multiselect-001',
    type: 'multiselect',
    topic: 'email writing',
    subtopic: 'greetings-and-closings',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Select the informal email elements.',
    options: ['Hallo Claudia,', 'Liebe Claudia,', 'Mit freundlichen Gruessen', 'Wie geht es dir?', 'Sehr geehrte Frau Mueller,'],
    answers: [0, 1, 3],
    explanation: 'Hallo Claudia, Liebe Claudia, and Wie geht es dir? belong to informal du-based email style.',
    tags: ['email', 'informal', 'multiselect'],
  },
  {
    id: 'de-writing-email-multiselect-002',
    type: 'multiselect',
    topic: 'email writing',
    subtopic: 'greetings-and-closings',
    language: 'de',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Select the formal email elements.',
    options: [
      'Sehr geehrter Herr Schmidt,',
      'Ich schreibe Ihnen, weil...',
      'Viele Gruesse',
      'Mit freundlichen Gruessen',
      'Wie geht es dir?',
    ],
    answers: [0, 1, 3],
    explanation: 'These three phrases are standard formal Sie-based email elements.',
    tags: ['email', 'formal', 'multiselect'],
  },
]

export default exercises
