import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  // -AR verbs: hablar
  {
    id: 'es-verb-conj-hablar-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: '-ar-verbs',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form of "hablar" (yo).',
    context: 'Yo ___ espanol.',
    options: ['hablas', 'habla', 'hablo', 'hablamos'],
    answer: 2,
    explanation: '"Hablar" in the first person singular (yo) is "hablo" — drop -ar, add -o.',
    tags: ['conjugation', '-ar-verbs', 'present', 'a1'],
  },
  {
    id: 'es-verb-conj-hablar-002',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: '-ar-verbs',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form of "hablar" (vosotros).',
    context: 'Vosotros ___ muy rapido.',
    options: ['hablan', 'hablais', 'hablamos', 'hablan'],
    answer: 1,
    explanation: '"Hablar" in the second person plural (vosotros) is "hablais".',
    tags: ['conjugation', '-ar-verbs', 'present', 'a1'],
  },
  {
    id: 'es-verb-conj-hablar-003',
    type: 'multiselect',
    topic: 'verb conjugation',
    subtopic: '-ar-verbs',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select ALL correct conjugations of "hablar" in the present tense.',
    options: ['tu hablas', 'nosotros hablamos', 'ellos hablan', 'usted hablas'],
    answers: [0, 1, 2],
    explanation: '"Tu hablas", "nosotros hablamos", and "ellos hablan" are correct. "Usted hablas" is wrong — usted takes the third person: "usted habla".',
    tags: ['conjugation', '-ar-verbs', 'present'],
  },
  // -ER verbs: comer
  {
    id: 'es-verb-conj-comer-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: '-er-verbs',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form of "comer" (ella).',
    context: 'Ella ___ una ensalada.',
    options: ['como', 'comes', 'come', 'comemos'],
    answer: 2,
    explanation: '"Comer" in the third person singular (ella) is "come".',
    tags: ['conjugation', '-er-verbs', 'present', 'a1'],
  },
  {
    id: 'es-verb-conj-comer-002',
    type: 'multiselect',
    topic: 'verb conjugation',
    subtopic: '-er-verbs',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select ALL correct conjugations of "comer".',
    options: ['yo como', 'tu comeis', 'ellos comen', 'nosotros comemos'],
    answers: [0, 2, 3],
    explanation: '"Yo como", "ellos comen", and "nosotros comemos" are correct. "Tu comeis" is wrong — "vosotros" takes "comeis", but "tu" takes "comes".',
    tags: ['conjugation', '-er-verbs', 'present'],
  },
  // -IR verbs: vivir
  {
    id: 'es-verb-conj-vivir-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: '-ir-verbs',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form of "vivir" (nosotros).',
    context: 'Nosotros ___ en Madrid.',
    options: ['viven', 'vivimos', 'vivimos', 'vivo'],
    answer: 1,
    explanation: '"Vivir" in the first person plural (nosotros) is "vivimos".',
    tags: ['conjugation', '-ir-verbs', 'present', 'a1'],
  },
  // Irregular: ir
  {
    id: 'es-verb-conj-ir-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: 'irregular-verbs',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct form of "ir" (yo).',
    context: 'Yo ___ al mercado.',
    options: ['iro', 'voy', 'vas', 'imos'],
    answer: 1,
    explanation: '"Ir" is highly irregular: "yo voy" (not "iro").',
    tags: ['conjugation', 'irregular', 'ir', 'a1'],
  },
  {
    id: 'es-verb-conj-ir-002',
    type: 'multiselect',
    topic: 'verb conjugation',
    subtopic: 'irregular-verbs',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select ALL correct conjugations of "ir".',
    options: ['yo voy', 'tu iras', 'nosotros vamos', 'ellos van'],
    answers: [0, 2, 3],
    explanation: '"Yo voy", "nosotros vamos", and "ellos van" are correct present tense. "Tu iras" is future tense, not present.',
    tags: ['conjugation', 'irregular', 'ir'],
  },
  // Irregular: querer (stem-change e→ie)
  {
    id: 'es-verb-conj-querer-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: 'stem-changing-verbs',
    language: 'es',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct form of "querer" (yo).',
    context: 'Yo ___ aprender espanol.',
    options: ['quero', 'quiero', 'queres', 'queremos'],
    answer: 1,
    explanation: '"Querer" is a stem-changing verb (e→ie): "yo quiero". The stem vowel "e" becomes "ie" in stressed syllables.',
    tags: ['conjugation', 'stem-change', 'querer', 'a2'],
  },
  {
    id: 'es-verb-conj-querer-002',
    type: 'multiselect',
    topic: 'verb conjugation',
    subtopic: 'stem-changing-verbs',
    language: 'es',
    group: 'grammar',
    level: 'A2',
    difficulty: 4,
    prompt: 'Select ALL forms where "querer" has stem change (e→ie).',
    options: ['yo quiero', 'nosotros queremos', 'tu quieres', 'ellos quieren'],
    answers: [0, 2, 3],
    explanation: 'Stem-changing verbs only change in stressed forms: yo, tu, el/ella, ellos/ellas. "Nosotros queremos" keeps the original "e" because the stress falls on the ending, not the stem.',
    tags: ['conjugation', 'stem-change', 'querer', 'a2'],
  },
  // Irregular: poder (stem-change o→ue)
  {
    id: 'es-verb-conj-poder-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: 'stem-changing-verbs',
    language: 'es',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct form of "poder" (ellos).',
    context: 'Ellos ___ venir manana.',
    options: ['pueden', 'podemos', 'puedo', 'podes'],
    answer: 0,
    explanation: '"Poder" is a stem-changing verb (o→ue): "ellos pueden".',
    tags: ['conjugation', 'stem-change', 'poder', 'a2'],
  },
  // Irregular yo forms: hacer, venir, salir, tener
  {
    id: 'es-verb-conj-hacer-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: 'irregular-yo',
    language: 'es',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct form of "hacer" (yo).',
    context: 'Yo ___ ejercicio todos los dias.',
    options: ['haco', 'hace', 'hago', 'hacemos'],
    answer: 2,
    explanation: '"Hacer" has an irregular "yo" form: "yo hago" (not "haco").',
    tags: ['conjugation', 'irregular', 'yo-form', 'hacer', 'a2'],
  },
  {
    id: 'es-verb-conj-venir-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: 'irregular-yo',
    language: 'es',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct form of "venir" (yo).',
    context: 'Yo ___ de Argentina.',
    options: ['veno', 'vengo', 'viene', 'venimos'],
    answer: 1,
    explanation: '"Venir" has an irregular "yo" form: "yo vengo".',
    tags: ['conjugation', 'irregular', 'yo-form', 'venir', 'a2'],
  },
  {
    id: 'es-verb-conj-tener-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: 'irregular-yo',
    language: 'es',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct form of "tener" (yo).',
    context: 'Yo ___ mucho trabajo hoy.',
    options: ['teno', 'tiene', 'tengo', 'tenemos'],
    answer: 2,
    explanation: '"Tener" has an irregular "yo" form: "yo tengo".',
    tags: ['conjugation', 'irregular', 'yo-form', 'tener', 'a2'],
  },
  // Mixed review
  {
    id: 'es-verb-conj-review-001',
    type: 'multiselect',
    topic: 'verb conjugation',
    subtopic: 'mixed-review',
    language: 'es',
    group: 'grammar',
    level: 'A2',
    difficulty: 4,
    prompt: 'Select ALL grammatically correct sentences.',
    options: [
      'Yo hago la tarea.',
      'Ellos pueden venir.',
      'Tu quero un cafe.',
      'Nosotros vamos al parque.'
    ],
    answers: [0, 1, 3],
    explanation: '"Yo hago", "ellos pueden", and "nosotros vamos" are correct. "Tu quero" is wrong — the correct form is "tu quieres".',
    tags: ['conjugation', 'mixed', 'review'],
  },
]

export default exercises
