import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'es-foundations-articles-001',
    type: 'selection',
    topic: 'articles and gender',
    subtopic: 'definite-articles',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct article for "libro".',
    context: '___ libro es interesante.',
    options: ['el', 'la', 'los', 'las'],
    answer: 0,
    explanation: '"Libro" is masculine singular, so it takes "el".',
    tags: ['articles', 'gender', 'a1'],
  },
  {
    id: 'es-foundations-articles-002',
    type: 'selection',
    topic: 'articles and gender',
    subtopic: 'definite-articles',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct article for "casa".',
    context: '___ casa es grande.',
    options: ['el', 'la', 'los', 'unas'],
    answer: 1,
    explanation: '"Casa" is feminine singular, so it takes "la".',
    tags: ['articles', 'gender', 'a1'],
  },
  {
    id: 'es-foundations-ser-estar-001',
    type: 'selection',
    topic: 'ser vs estar',
    subtopic: 'present-tense',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct verb.',
    context: 'Madrid ___ en Espana.',
    options: ['es', 'esta', 'son', 'estan'],
    answer: 0,
    explanation: 'Use "ser" for permanent identity or origin/location of cities: "Madrid es..."',
    tags: ['ser', 'estar', 'a1'],
  },
  {
    id: 'es-foundations-ser-estar-002',
    type: 'selection',
    topic: 'ser vs estar',
    subtopic: 'present-tense',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct verb.',
    context: 'Yo ___ cansado hoy.',
    options: ['soy', 'estoy', 'eres', 'estas'],
    answer: 1,
    explanation: 'Use "estar" for temporary states: "estoy cansado".',
    tags: ['ser', 'estar', 'a1'],
  },
  {
    id: 'es-foundations-present-001',
    type: 'selection',
    topic: 'present tense basics',
    subtopic: 'high-frequency-verbs',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct form of "tener".',
    context: 'Nosotros ___ dos clases hoy.',
    options: ['tiene', 'tenemos', 'tienen', 'tengo'],
    answer: 1,
    explanation: 'The correct present tense form for "nosotros" is "tenemos".',
    tags: ['present-tense', 'tener'],
  },
  {
    id: 'es-foundations-present-002',
    type: 'selection',
    topic: 'present tense basics',
    subtopic: 'high-frequency-verbs',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct form of "vivir".',
    context: 'Ellos ___ en Barcelona.',
    options: ['vive', 'viven', 'vivimos', 'vivo'],
    answer: 1,
    explanation: 'The correct present tense form for "ellos" is "viven".',
    tags: ['present-tense', 'vivir'],
  },
  {
    id: 'es-foundations-questions-001',
    type: 'selection',
    topic: 'question words',
    subtopic: 'basic-questions',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct question word.',
    context: '___ vives? En Madrid o en Sevilla?',
    options: ['Quien', 'Donde', 'Cuando', 'Por que'],
    answer: 1,
    explanation: '"Donde" means "where".',
    tags: ['question-words', 'a1'],
  },
  {
    id: 'es-foundations-questions-002',
    type: 'selection',
    topic: 'question words',
    subtopic: 'basic-questions',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct question word.',
    context: '___ estudias espanol? Porque quiero viajar.',
    options: ['Por que', 'Que', 'Cuantos', 'Como'],
    answer: 0,
    explanation: '"Por que" asks for a reason: why?',
    tags: ['question-words', 'a1'],
  },
  {
    id: 'es-foundations-vocab-001',
    type: 'selection',
    topic: 'daily life vocabulary',
    subtopic: 'food-and-home',
    language: 'es',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "la mesa" mean?',
    options: ['window', 'table', 'chair', 'door'],
    answer: 1,
    explanation: '"La mesa" means "table".',
    tags: ['vocabulary', 'daily-life'],
  },
  {
    id: 'es-foundations-vocab-002',
    type: 'selection',
    topic: 'daily life vocabulary',
    subtopic: 'food-and-home',
    language: 'es',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "el agua" mean?',
    options: ['bread', 'water', 'milk', 'coffee'],
    answer: 1,
    explanation: '"El agua" means "water".',
    tags: ['vocabulary', 'daily-life'],
  },
  {
    id: 'es-foundations-multiselect-001',
    type: 'multiselect',
    topic: 'articles and gender',
    subtopic: 'gender-recognition',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select all nouns that usually take "la".',
    options: ['casa', 'libro', 'puerta', 'amigo'],
    answers: [0, 2],
    explanation: '"Casa" and "puerta" are feminine nouns and usually take "la".',
    tags: ['articles', 'gender'],
  },
  {
    id: 'es-foundations-multiselect-002',
    type: 'multiselect',
    topic: 'ser vs estar',
    subtopic: 'meaning-contrast',
    language: 'es',
    group: 'grammar',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select all situations where "estar" is normally used.',
    options: ['temporary mood', 'profession', 'current location', 'nationality'],
    answers: [0, 2],
    explanation: '"Estar" is commonly used for temporary states and current location.',
    tags: ['ser', 'estar'],
  },
]

export default exercises
