import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  // Transport vocabulary
  {
    id: 'es-travel-vocab-001',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'transport',
    language: 'es',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "el billete" mean?',
    options: ['platform', 'ticket', 'suitcase', 'departure'],
    answer: 1,
    explanation: '"El billete" means "ticket" (train, bus, plane, etc.). In Latin America "el boleto" is also common.',
    tags: ['travel', 'transport', 'vocabulary', 'a1'],
  },
  {
    id: 'es-travel-vocab-002',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'transport',
    language: 'es',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "el andén" mean?',
    options: ['gate', 'platform', 'runway', 'ticket office'],
    answer: 1,
    explanation: '"El andén" is the platform at a train or metro station.',
    tags: ['travel', 'train', 'vocabulary', 'a1'],
  },
  {
    id: 'es-travel-vocab-003',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'transport',
    language: 'es',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "ida y vuelta" mean?',
    options: ['one-way ticket', 'return ticket', 'first class', 'platform change'],
    answer: 1,
    explanation: '"Ida y vuelta" means "return ticket" (there and back). "Solo ida" is one-way.',
    tags: ['travel', 'transport', 'vocabulary', 'a1'],
  },
  {
    id: 'es-travel-vocab-004',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'transport',
    language: 'es',
    group: 'vocabulary',
    level: 'A2',
    difficulty: 2,
    prompt: 'What does "el transbordo" mean?',
    options: ['arrival', 'transfer / connection', 'luggage', 'seat reservation'],
    answer: 1,
    explanation: '"El transbordo" means a transfer or connection — when you change trains, buses, or metro lines.',
    tags: ['travel', 'transport', 'vocabulary', 'a2'],
  },
  {
    id: 'es-travel-vocab-005',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'transport',
    language: 'es',
    group: 'vocabulary',
    level: 'A2',
    difficulty: 2,
    prompt: 'What does "el horario" mean?',
    options: ['departure board', 'timetable / schedule', 'reservation', 'delay'],
    answer: 1,
    explanation: '"El horario" means the timetable or schedule.',
    tags: ['travel', 'transport', 'vocabulary', 'a2'],
  },
  // Airport vocabulary
  {
    id: 'es-travel-vocab-006',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'airport',
    language: 'es',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "la maleta" mean?',
    options: ['handbag', 'backpack', 'suitcase', 'boarding pass'],
    answer: 2,
    explanation: '"La maleta" means "suitcase".',
    tags: ['travel', 'airport', 'vocabulary', 'a1'],
  },
  {
    id: 'es-travel-vocab-007',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'airport',
    language: 'es',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 2,
    prompt: 'What does "la puerta de embarque" mean?',
    options: ['baggage claim', 'arrivals hall', 'boarding gate', 'customs'],
    answer: 2,
    explanation: '"La puerta de embarque" is the boarding gate — where you board the plane.',
    tags: ['travel', 'airport', 'vocabulary', 'a1'],
  },
  {
    id: 'es-travel-vocab-008',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'airport',
    language: 'es',
    group: 'vocabulary',
    level: 'A2',
    difficulty: 2,
    prompt: 'What does "facturar el equipaje" mean?',
    options: ['collect baggage', 'check in luggage', 'carry on luggage', 'weigh luggage'],
    answer: 1,
    explanation: '"Facturar el equipaje" means to check in your luggage at the airport counter.',
    tags: ['travel', 'airport', 'vocabulary', 'a2'],
  },
  {
    id: 'es-travel-vocab-009',
    type: 'multiselect',
    topic: 'travel vocabulary',
    subtopic: 'airport',
    language: 'es',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select ALL words or phrases you would typically find at an airport.',
    options: ['la tarjeta de embarque', 'el andén', 'la aduana', 'el pasaporte'],
    answers: [0, 2, 3],
    explanation: '"La tarjeta de embarque" (boarding pass), "la aduana" (customs), and "el pasaporte" are airport items. "El andén" is a train/metro platform.',
    tags: ['travel', 'airport', 'vocabulary'],
  },
  // Hotel vocabulary
  {
    id: 'es-travel-vocab-010',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'hotel',
    language: 'es',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "la habitacion" mean?',
    options: ['lobby', 'room', 'floor', 'key'],
    answer: 1,
    explanation: '"La habitacion" means "room" (as in a hotel room).',
    tags: ['travel', 'hotel', 'vocabulary', 'a1'],
  },
  {
    id: 'es-travel-vocab-011',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'hotel',
    language: 'es',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "la recepcion" mean in a hotel context?',
    options: ['restaurant', 'swimming pool', 'front desk / reception', 'elevator'],
    answer: 2,
    explanation: '"La recepcion" is the front desk or reception area of a hotel.',
    tags: ['travel', 'hotel', 'vocabulary', 'a1'],
  },
  {
    id: 'es-travel-vocab-012',
    type: 'multiselect',
    topic: 'travel vocabulary',
    subtopic: 'hotel',
    language: 'es',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select ALL words you might need at a hotel.',
    options: ['la llave', 'el andén', 'la reserva', 'el desayuno'],
    answers: [0, 2, 3],
    explanation: '"La llave" (key), "la reserva" (reservation), and "el desayuno" (breakfast) are hotel-related. "El andén" (platform) is a transport term.',
    tags: ['travel', 'hotel', 'vocabulary'],
  },
  // Asking for directions
  {
    id: 'es-travel-vocab-013',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'directions',
    language: 'es',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 2,
    prompt: 'What does "girar a la izquierda" mean?',
    options: ['go straight ahead', 'turn right', 'turn left', 'go back'],
    answer: 2,
    explanation: '"Girar a la izquierda" means "turn left". "A la derecha" is right, "todo recto" is straight ahead.',
    tags: ['travel', 'directions', 'vocabulary', 'a1'],
  },
  {
    id: 'es-travel-vocab-014',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'directions',
    language: 'es',
    group: 'vocabulary',
    level: 'A2',
    difficulty: 2,
    prompt: 'You ask "Donde esta la estacion de tren?" What are you looking for?',
    options: ['the hotel', 'the airport', 'the train station', 'the bus stop'],
    answer: 2,
    explanation: '"La estacion de tren" is the train station. "El aeropuerto" is the airport, "la parada de autobus" is the bus stop.',
    tags: ['travel', 'directions', 'vocabulary', 'a2'],
  },
  // Useful phrases
  {
    id: 'es-travel-vocab-015',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'useful-phrases',
    language: 'es',
    group: 'vocabulary',
    level: 'A2',
    difficulty: 3,
    prompt: 'What does "con retraso" mean?',
    options: ['on time', 'late / delayed', 'cancelled', 'early'],
    answer: 1,
    explanation: '"Con retraso" means late or delayed. "A tiempo" is on time, "cancelado" is cancelled.',
    tags: ['travel', 'phrases', 'vocabulary', 'a2'],
  },
]

export default exercises
