import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  // -ER verbs: parler
  {
    id: 'fr-verb-conj-parler-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: '-er-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form of "parler" (je).',
    context: 'Je ___ francais.',
    options: ['parle', 'parles', 'parlons', 'parlez'],
    answer: 0,
    explanation: '"Parler" in the first person singular (je) is "parle".',
    tags: ['conjugation', '-er-verbs', 'present', 'a1'],
  },
  {
    id: 'fr-verb-conj-parler-002',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: '-er-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct form of "parler" (vous).',
    context: 'Vous ___ trop vite.',
    options: ['parle', 'parlent', 'parlez', 'parlons'],
    answer: 2,
    explanation: '"Parler" in the second person plural (vous) is "parlez".',
    tags: ['conjugation', '-er-verbs', 'present', 'a1'],
  },
  {
    id: 'fr-verb-conj-parler-003',
    type: 'multiselect',
    topic: 'verb conjugation',
    subtopic: '-er-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select ALL correct conjugations of "parler" in the present tense.',
    options: ['tu parles', 'nous parlons', 'ils parlent', 'vous parler'],
    answers: [0, 1, 2],
    explanation: '"Tu parles", "nous parlons", and "ils parlent" are all correct. "Vous parler" is the infinitive, not a conjugated form.',
    tags: ['conjugation', '-er-verbs', 'present'],
  },
  // -ER verbs: manger (stem change)
  {
    id: 'fr-verb-conj-manger-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: '-er-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct form of "manger" (nous).',
    context: 'Nous ___ au restaurant ce soir.',
    options: ['mangons', 'mangeons', 'mangent', 'mangez'],
    answer: 1,
    explanation: 'Verbs ending in -ger keep the "e" before -ons to preserve the soft "g" sound: "nous mangeons".',
    tags: ['conjugation', '-ger-verbs', 'stem-change', 'a2'],
  },
  // -IR verbs: finir
  {
    id: 'fr-verb-conj-finir-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: '-ir-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct form of "finir" (ils).',
    context: 'Ils ___ le travail a 18h.',
    options: ['finis', 'finit', 'finissent', 'finissons'],
    answer: 2,
    explanation: '"Finir" in the third person plural (ils) is "finissent" — regular -ir verbs add "-iss-" in plural forms.',
    tags: ['conjugation', '-ir-verbs', 'present', 'a1'],
  },
  {
    id: 'fr-verb-conj-finir-002',
    type: 'multiselect',
    topic: 'verb conjugation',
    subtopic: '-ir-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Select ALL correct conjugations of "finir".',
    options: ['je finis', 'tu finissez', 'elle finit', 'nous finissons'],
    answers: [0, 2, 3],
    explanation: '"Je finis", "elle finit", and "nous finissons" are correct. "Tu finissez" is wrong — "tu" takes "finis".',
    tags: ['conjugation', '-ir-verbs', 'present'],
  },
  // Irregular: aller
  {
    id: 'fr-verb-conj-aller-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: 'irregular-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct form of "aller" (je).',
    context: 'Je ___ au marche.',
    options: ['ale', 'vas', 'vais', 'allons'],
    answer: 2,
    explanation: '"Aller" is highly irregular: "je vais" (not "je ale").',
    tags: ['conjugation', 'irregular', 'aller', 'a1'],
  },
  {
    id: 'fr-verb-conj-aller-002',
    type: 'multiselect',
    topic: 'verb conjugation',
    subtopic: 'irregular-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select ALL correct conjugations of "aller".',
    options: ['tu vas', 'ils alent', 'nous allons', 'elle va'],
    answers: [0, 2, 3],
    explanation: '"Tu vas", "nous allons", and "elle va" are correct. "Ils alent" does not exist — the correct form is "ils vont".',
    tags: ['conjugation', 'irregular', 'aller'],
  },
  // Irregular: faire
  {
    id: 'fr-verb-conj-faire-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: 'irregular-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct form of "faire" (nous).',
    context: 'Nous ___ du sport le matin.',
    options: ['faisons', 'faisez', 'font', 'faites'],
    answer: 0,
    explanation: '"Faire" in the first person plural (nous) is "faisons".',
    tags: ['conjugation', 'irregular', 'faire', 'a1'],
  },
  {
    id: 'fr-verb-conj-faire-002',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: 'irregular-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct form of "faire" (vous).',
    context: 'Qu\'est-ce que vous ___ ce week-end ?',
    options: ['faisez', 'faites', 'font', 'fais'],
    answer: 1,
    explanation: '"Vous faites" is correct — "faire" is irregular in the vous form (not "faisez").',
    tags: ['conjugation', 'irregular', 'faire', 'a2'],
  },
  // Irregular: vouloir / pouvoir
  {
    id: 'fr-verb-conj-vouloir-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: 'irregular-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct form of "vouloir" (il).',
    context: 'Il ___ un cafe.',
    options: ['veut', 'veux', 'voulons', 'voulez'],
    answer: 0,
    explanation: '"Vouloir" in the third person singular (il/elle) is "veut".',
    tags: ['conjugation', 'irregular', 'vouloir', 'a2'],
  },
  {
    id: 'fr-verb-conj-pouvoir-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: 'irregular-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A2',
    difficulty: 2,
    prompt: 'Choose the correct form of "pouvoir" (je).',
    context: 'Je ne ___ pas venir ce soir.',
    options: ['peux', 'peut', 'pouvons', 'pouvez'],
    answer: 0,
    explanation: '"Pouvoir" in the first person singular (je) is "peux".',
    tags: ['conjugation', 'irregular', 'pouvoir', 'a2'],
  },
  // Irregular: venir
  {
    id: 'fr-verb-conj-venir-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: 'irregular-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct form of "venir" (ils).',
    context: 'Ils ___ de Paris.',
    options: ['viennent', 'venons', 'venez', 'viens'],
    answer: 0,
    explanation: '"Venir" in the third person plural (ils) is "viennent" — note the double "n".',
    tags: ['conjugation', 'irregular', 'venir', 'a2'],
  },
  // Irregular: prendre
  {
    id: 'fr-verb-conj-prendre-001',
    type: 'selection',
    topic: 'verb conjugation',
    subtopic: 'irregular-verbs',
    language: 'fr',
    group: 'grammar',
    level: 'A2',
    difficulty: 3,
    prompt: 'Choose the correct form of "prendre" (tu).',
    context: 'Tu ___ le bus ou le metro ?',
    options: ['prend', 'prends', 'prenez', 'prennent'],
    answer: 1,
    explanation: '"Prendre" in the second person singular (tu) is "prends" — it keeps the final "d" as a silent letter.',
    tags: ['conjugation', 'irregular', 'prendre', 'a2'],
  },
  // Mixed review multiselect
  {
    id: 'fr-verb-conj-review-001',
    type: 'multiselect',
    topic: 'verb conjugation',
    subtopic: 'mixed-review',
    language: 'fr',
    group: 'grammar',
    level: 'A2',
    difficulty: 4,
    prompt: 'Select ALL grammatically correct sentences.',
    options: [
      'Vous faites du sport.',
      'Ils allent au cinema.',
      'Elle peut venir demain.',
      'Nous voulons une table.'
    ],
    answers: [0, 2, 3],
    explanation: '"Vous faites", "elle peut", and "nous voulons" are correct. "Ils allent" is wrong — the correct form is "ils vont".',
    tags: ['conjugation', 'mixed', 'review'],
  },
]

export default exercises
