import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  {
    id: 'fr-foundations-articles-001',
    type: 'selection',
    topic: 'articles and gender',
    subtopic: 'definite-articles',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct article for "livre".',
    context: '___ livre est interessant.',
    options: ['le', 'la', 'les', 'une'],
    answer: 0,
    explanation: '"Livre" is masculine singular, so it takes "le".',
    tags: ['articles', 'gender', 'a1'],
  },
  {
    id: 'fr-foundations-articles-002',
    type: 'selection',
    topic: 'articles and gender',
    subtopic: 'definite-articles',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 1,
    prompt: 'Choose the correct article for "maison".',
    context: '___ maison est grande.',
    options: ['le', 'la', 'les', 'des'],
    answer: 1,
    explanation: '"Maison" is feminine singular, so it takes "la".',
    tags: ['articles', 'gender', 'a1'],
  },
  {
    id: 'fr-foundations-etre-avoir-001',
    type: 'selection',
    topic: 'etre and avoir',
    subtopic: 'present-tense',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct verb.',
    context: 'Nous ___ une reservation.',
    options: ['sommes', 'avons', 'avez', 'est'],
    answer: 1,
    explanation: 'Use "avoir" for possession: "nous avons".',
    tags: ['avoir', 'present-tense'],
  },
  {
    id: 'fr-foundations-etre-avoir-002',
    type: 'selection',
    topic: 'etre and avoir',
    subtopic: 'present-tense',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct verb.',
    context: 'Je ___ fatigue aujourd\'hui.',
    options: ['ai', 'es', 'suis', 'sommes'],
    answer: 2,
    explanation: 'Use "etre" for identity or state: "je suis fatigue".',
    tags: ['etre', 'present-tense'],
  },
  {
    id: 'fr-foundations-negation-001',
    type: 'selection',
    topic: 'negation',
    subtopic: 'ne-pas',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct negation.',
    context: 'Je ___ parle ___ anglais.',
    options: ['ne / pas', 'pas / ne', 'ne / rien', 'n\' / jamais'],
    answer: 0,
    explanation: 'Basic negation in French is "ne ... pas" around the verb.',
    tags: ['negation', 'ne-pas'],
  },
  {
    id: 'fr-foundations-negation-002',
    type: 'selection',
    topic: 'negation',
    subtopic: 'ne-pas',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct sentence.',
    options: [
      'Il ne travaille pas le dimanche.',
      'Il travaille ne pas le dimanche.',
      'Il ne pas travaille le dimanche.',
      'Il pas ne travaille le dimanche.'
    ],
    answer: 0,
    explanation: 'In standard written French, "ne" goes before the verb and "pas" after it.',
    tags: ['negation', 'sentence-choice'],
  },
  {
    id: 'fr-foundations-questions-001',
    type: 'selection',
    topic: 'question words',
    subtopic: 'basic-questions',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct question word.',
    context: '___ habites-tu ? A Lyon.',
    options: ['Quand', 'Ou', 'Pourquoi', 'Comment'],
    answer: 1,
    explanation: '"Ou" means "where".',
    tags: ['question-words', 'a1'],
  },
  {
    id: 'fr-foundations-questions-002',
    type: 'selection',
    topic: 'question words',
    subtopic: 'basic-questions',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 2,
    prompt: 'Choose the correct question word.',
    context: '___ etudies-tu le francais ? Pour voyager.',
    options: ['Pourquoi', 'Qui', 'Combien', 'Ou'],
    answer: 0,
    explanation: '"Pourquoi" asks for a reason: why?',
    tags: ['question-words', 'a1'],
  },
  {
    id: 'fr-foundations-vocab-001',
    type: 'selection',
    topic: 'daily life vocabulary',
    subtopic: 'food-and-home',
    language: 'fr',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "la chaise" mean?',
    options: ['chair', 'kitchen', 'bag', 'window'],
    answer: 0,
    explanation: '"La chaise" means "chair".',
    tags: ['vocabulary', 'daily-life'],
  },
  {
    id: 'fr-foundations-vocab-002',
    type: 'selection',
    topic: 'daily life vocabulary',
    subtopic: 'food-and-home',
    language: 'fr',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "le pain" mean?',
    options: ['milk', 'bread', 'cheese', 'water'],
    answer: 1,
    explanation: '"Le pain" means "bread".',
    tags: ['vocabulary', 'daily-life'],
  },
  {
    id: 'fr-foundations-multiselect-001',
    type: 'multiselect',
    topic: 'articles and gender',
    subtopic: 'gender-recognition',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select all nouns that usually take "la".',
    options: ['maison', 'livre', 'table', 'garcon'],
    answers: [0, 2],
    explanation: '"Maison" and "table" are typically feminine and take "la".',
    tags: ['articles', 'gender'],
  },
  {
    id: 'fr-foundations-multiselect-002',
    type: 'multiselect',
    topic: 'etre and avoir',
    subtopic: 'meaning-contrast',
    language: 'fr',
    group: 'grammar',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select all contexts where "avoir" is commonly used.',
    options: ['age', 'possession', 'nationality', 'temporary hunger'],
    answers: [0, 1, 3],
    explanation: 'French uses "avoir" in many expressions like age and hunger, as well as possession.',
    tags: ['avoir', 'usage'],
  },
]

export default exercises
