import type { Exercise } from '../types/exercise'

const exercises: Exercise[] = [
  // Transport vocabulary
  {
    id: 'fr-travel-vocab-001',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'transport',
    language: 'fr',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "le billet" mean?',
    options: ['platform', 'ticket', 'luggage', 'departure'],
    answer: 1,
    explanation: '"Le billet" means "ticket" (train, bus, plane, etc.).',
    tags: ['travel', 'transport', 'vocabulary', 'a1'],
  },
  {
    id: 'fr-travel-vocab-002',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'transport',
    language: 'fr',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "le quai" mean?',
    options: ['gate', 'platform', 'runway', 'ticket office'],
    answer: 1,
    explanation: '"Le quai" is the platform at a train or metro station.',
    tags: ['travel', 'train', 'vocabulary', 'a1'],
  },
  {
    id: 'fr-travel-vocab-003',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'transport',
    language: 'fr',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "aller-retour" mean?',
    options: ['one-way ticket', 'return ticket', 'first class', 'platform change'],
    answer: 1,
    explanation: '"Aller-retour" means "return ticket" — going and coming back. "Aller simple" is one-way.',
    tags: ['travel', 'transport', 'vocabulary', 'a1'],
  },
  {
    id: 'fr-travel-vocab-004',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'transport',
    language: 'fr',
    group: 'vocabulary',
    level: 'A2',
    difficulty: 2,
    prompt: 'What does "composter le billet" mean?',
    options: ['buy a ticket', 'validate / stamp the ticket', 'lose the ticket', 'change trains'],
    answer: 1,
    explanation: 'In France, you must "composter" (validate) your train ticket in a machine on the platform before boarding.',
    tags: ['travel', 'train', 'culture', 'a2'],
  },
  {
    id: 'fr-travel-vocab-005',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'transport',
    language: 'fr',
    group: 'vocabulary',
    level: 'A2',
    difficulty: 2,
    prompt: 'What does "la correspondance" mean in a transport context?',
    options: ['a letter', 'a connection / transfer', 'a ticket', 'a delay'],
    answer: 1,
    explanation: '"La correspondance" in transport means a connection — changing trains, buses, or metro lines.',
    tags: ['travel', 'transport', 'vocabulary', 'a2'],
  },
  // Airport vocabulary
  {
    id: 'fr-travel-vocab-006',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'airport',
    language: 'fr',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "une valise" mean?',
    options: ['handbag', 'suitcase', 'backpack', 'boarding pass'],
    answer: 1,
    explanation: '"Une valise" means "a suitcase".',
    tags: ['travel', 'airport', 'vocabulary', 'a1'],
  },
  {
    id: 'fr-travel-vocab-007',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'airport',
    language: 'fr',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 2,
    prompt: 'What does "la porte d\'embarquement" mean?',
    options: ['baggage claim', 'departure lounge', 'boarding gate', 'customs'],
    answer: 2,
    explanation: '"La porte d\'embarquement" is the boarding gate — where you board the plane.',
    tags: ['travel', 'airport', 'vocabulary', 'a1'],
  },
  {
    id: 'fr-travel-vocab-008',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'airport',
    language: 'fr',
    group: 'vocabulary',
    level: 'A2',
    difficulty: 2,
    prompt: 'What does "enregistrer les bagages" mean?',
    options: ['collect baggage', 'check in luggage', 'carry on luggage', 'lose luggage'],
    answer: 1,
    explanation: '"Enregistrer les bagages" means to check in your luggage at the airport counter.',
    tags: ['travel', 'airport', 'vocabulary', 'a2'],
  },
  {
    id: 'fr-travel-vocab-009',
    type: 'multiselect',
    topic: 'travel vocabulary',
    subtopic: 'airport',
    language: 'fr',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select ALL words or phrases you would typically find at an airport.',
    options: ['la carte d\'embarquement', 'le quai', 'les douanes', 'le passeport'],
    answers: [0, 2, 3],
    explanation: '"La carte d\'embarquement" (boarding pass), "les douanes" (customs), and "le passeport" are airport items. "Le quai" is a train/metro platform.',
    tags: ['travel', 'airport', 'vocabulary'],
  },
  // Hotel vocabulary
  {
    id: 'fr-travel-vocab-010',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'hotel',
    language: 'fr',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "la chambre" mean?',
    options: ['lobby', 'room', 'floor', 'key'],
    answer: 1,
    explanation: '"La chambre" means "room" (as in a hotel room).',
    tags: ['travel', 'hotel', 'vocabulary', 'a1'],
  },
  {
    id: 'fr-travel-vocab-011',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'hotel',
    language: 'fr',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 1,
    prompt: 'What does "la reception" mean in a hotel context?',
    options: ['restaurant', 'breakfast room', 'front desk / reception', 'elevator'],
    answer: 2,
    explanation: '"La reception" is the front desk or reception area of a hotel.',
    tags: ['travel', 'hotel', 'vocabulary', 'a1'],
  },
  {
    id: 'fr-travel-vocab-012',
    type: 'multiselect',
    topic: 'travel vocabulary',
    subtopic: 'hotel',
    language: 'fr',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 3,
    prompt: 'Select ALL words you might need at a hotel.',
    options: ['la cle', 'l\'horaire', 'la reservation', 'le petit-dejeuner'],
    answers: [0, 2, 3],
    explanation: '"La cle" (key), "la reservation" (booking), and "le petit-dejeuner" (breakfast) are hotel-related. "L\'horaire" (schedule/timetable) is more associated with transport.',
    tags: ['travel', 'hotel', 'vocabulary'],
  },
  // Asking for directions
  {
    id: 'fr-travel-vocab-013',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'directions',
    language: 'fr',
    group: 'vocabulary',
    level: 'A1',
    difficulty: 2,
    prompt: 'What does "tourner a gauche" mean?',
    options: ['go straight ahead', 'turn right', 'turn left', 'go back'],
    answer: 2,
    explanation: '"Tourner a gauche" means "turn left". "A droite" is right, "tout droit" is straight ahead.',
    tags: ['travel', 'directions', 'vocabulary', 'a1'],
  },
  {
    id: 'fr-travel-vocab-014',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'directions',
    language: 'fr',
    group: 'vocabulary',
    level: 'A2',
    difficulty: 2,
    prompt: 'You ask "Ou se trouve la gare ?" What are you looking for?',
    options: ['the hotel', 'the airport', 'the train station', 'the bus stop'],
    answer: 2,
    explanation: '"La gare" is the train station. "L\'aeroport" is the airport, "l\'arret de bus" is the bus stop.',
    tags: ['travel', 'directions', 'vocabulary', 'a2'],
  },
  // Useful phrases
  {
    id: 'fr-travel-vocab-015',
    type: 'selection',
    topic: 'travel vocabulary',
    subtopic: 'useful-phrases',
    language: 'fr',
    group: 'vocabulary',
    level: 'A2',
    difficulty: 3,
    prompt: 'What does "en retard" mean?',
    options: ['on time', 'late / delayed', 'cancelled', 'early'],
    answer: 1,
    explanation: '"En retard" means late or delayed. "A l\'heure" is on time, "annule" is cancelled.',
    tags: ['travel', 'phrases', 'vocabulary', 'a2'],
  },
]

export default exercises
