import { expect, it } from 'vitest'
import { analyzeRemaining, type AnkiRemainingCard } from './ankiRemaining'
const fields=(v:Record<string,string>)=>Object.fromEntries(Object.entries(v).map(([k,value])=>[k,{value}]))
const art=(i:number,ord=0):AnkiRemainingCard=>({cardId:100+i*2+ord,note:1000+i,modelName:'Art-a7e12',deckName:ord?'Great Works of Art':'Great Works of Art::Artists',ord,fields:fields({Artwork:`<img src="art${i}.jpg">`,Artist:['Alpha','Beta','Gamma','Delta','Epsilon'][i],Title:`Painting ${i}`,Date:'1900'})})
const media=Object.fromEntries(Array.from({length:5},(_,i)=>[`art${i}.jpg`,{url:`anki-media:${i}`,alt:'Answer leak'}]))
it('preserves art directions, stable IDs, unique choices and neutral alt',()=>{const cards=Array.from({length:5},(_,i)=>[art(i),art(i,1)]).flat();const r=analyzeRemaining(cards,media).candidates;const a=r.filter(c=>c.status==='ready');expect(a).toHaveLength(10);expect(a[0].exercise.options[a[0].exercise.answer]).toBe('Alpha');expect(a[1].exercise.options[a[1].exercise.answer]).toBe('Painting 0');expect(a[0].exercise.id).toBe('anki-100-artist');expect(a[0].exercise.media?.alt).not.toContain('Answer leak');for(const c of a){expect(new Set(c.exercise.options).size).toBe(4);expect(Number.isInteger(c.exercise.answer)).toBe(true);expect(c.exercise.options[c.exercise.answer]).toBeDefined();expect(c.exercise.difficulty).toBe(2)}expect(analyzeRemaining([...cards].reverse(),media).candidates.find(c=>c.source.ankiCardId==='100')).toEqual(a[0])})
it('preserves all dog photos and splits answer from metadata',()=>{const cards=['Akbash','Beagle','Boxer','Borzoi'].map((b,i)=>({...art(i),modelName:'Basic-492c9',deckName:'Породы::Dog Breeds',fields:fields({Front:`<img src="dog's.jpg"><img src='second.jpg'>`,Back:`${b}<br>Country<br>Group`})}));const c=analyzeRemaining(cards,{"dog's.jpg":{url:'anki-media:a'},'second.jpg':{url:'anki-media:b'}}).candidates[0];expect(c.status).toBe('ready');if(c.status==='ready'){expect(c.exercise.mediaGallery).toHaveLength(2);expect(c.exercise.options[c.exercise.answer]).toBe('Akbash');expect(c.exercise.explanation).toContain('Country')}})
it('holds absent images, unknown templates and insufficient options',()=>{expect(analyzeRemaining([art(0)],media).candidates[0].status).toBe('needs_review');expect(analyzeRemaining([art(0),art(1),art(2),art(3)],{}).candidates.every(c=>c.status==='needs_review')).toBe(true);expect(analyzeRemaining([{...art(0),ord:9}],media).candidates[0].status).toBe('needs_review')})
it('excludes title aliases',()=>{const cards=Array.from({length:5},(_,i)=>art(i,1));cards[0].fields['Subtitle/Alternate Titles']={value:'Painting 1'};const c=analyzeRemaining(cards,media).candidates[0];expect(c.status).toBe('ready');if(c.status==='ready')expect(c.exercise.options).not.toContain('Painting 1')})
it('keeps cat translations in explanations',()=>{const cards=['Persian<br>Персидская','Bengal','Siamese','Maine Coon'].map((b,i)=>({...art(i),modelName:'Cat Breeds',deckName:'Породы::Cat Breeds',fields:fields({Image:`<img src="art${i}.jpg">`,Breed:b,Origin:'Country'})}));const c=analyzeRemaining(cards,media).candidates[0];expect(c.status).toBe('ready');if(c.status==='ready'){expect(c.exercise.options[c.exercise.answer]).toBe('Persian');expect(c.exercise.explanation).toContain('Персидская')}})

it('preserves suspended source status as review',()=>{const cards=Array.from({length:5},(_,i)=>art(i));cards[0].queue=-1;const c=analyzeRemaining(cards,media).candidates[0];expect(c.status).toBe('needs_review');if(c.status==='needs_review')expect(c.reason).toContain('suspended')})
