import fs from 'fs'
import path from 'path'
import { db } from '../db/database'

export interface SeedBundledExercisesResult {
  deckId: number
  upserted: number
}

/** Seeded by migration 012_decks.sql; the bundled packs are this deck's content. */
const DECK_SLUG = 'german-grammar-vocabulary'

interface BundledExercise {
  id: string
  [key: string]: unknown
}

/**
 * Loads the bundled German grammar/vocabulary packs from the vendored snapshot
 * (backend/data/bundled-exercises.json, regenerated by scripts/export-bundled-exercises.ts) into
 * Postgres, attached to the deck they belong to.
 *
 * Idempotent, and the same "re-running is the reconciliation mechanism" contract the
 * Einbürgerungstest import already uses: git is the source of truth for this content, so a
 * re-run overwrites the stored rows from the snapshot.
 *
 * This replaces the client-side bootstrap that used to upload the packs from a signed-in user's
 * browser on every sign-in — content delivery is an operator action, not something a visitor's
 * browser performs.
 */
export async function seedBundledExercises(): Promise<SeedBundledExercisesResult> {
  const dataPath = path.resolve(__dirname, '../../data/bundled-exercises.json')
  const exercises: BundledExercise[] = JSON.parse(fs.readFileSync(dataPath, 'utf-8'))

  const deckResult = await db.query<{ id: number }>('SELECT id FROM decks WHERE slug = $1', [DECK_SLUG])
  const deckId = deckResult.rows[0]?.id
  if (deckId === undefined) {
    throw new Error(`Deck "${DECK_SLUG}" not found — run migrations before seeding.`)
  }

  let upserted = 0
  for (const exercise of exercises) {
    // deck_id is set on update as well as insert: rows written by the old client-side bootstrap
    // never carried one, which left them out of every deck-scoped query.
    await db.query(
      `INSERT INTO exercises (exercise_id, data, deck_id)
       VALUES ($1, $2, $3)
       ON CONFLICT (exercise_id) DO UPDATE SET
         data = EXCLUDED.data,
         deck_id = EXCLUDED.deck_id,
         updated_at = NOW()`,
      [exercise.id, JSON.stringify(exercise), deckId]
    )
    upserted += 1
  }

  return { deckId, upserted }
}
